manifest:
  version: "1.2"
  remotes:
    - name: hardwario
      url-base: git@github.com:hardwario
  projects:
    - name: sticker-zephyr
      remote: hardwario
      revision: main
      path: zephyr
      import: true
  self:
    path: application
