//! Emits TOWER radio-frame KAT JSON (stdout) from the upstream TOWER crates.
//! Header layout mirrors firmware/src/radio/frame.rs (`Header::encode`, not a crate).

use aes::Aes128;
use aes::cipher::{BlockCipherEncrypt, KeyInit};
use tower_net_core::ack::{AckVerdict, AckWait, ack_meta};
use tower_net_core::nonce::nonce_for;
use tower_radio_core::ccm::{AesBlock, Ccm, TAG_LEN};

struct SwAes;
impl AesBlock for SwAes {
    fn encrypt_block(&mut self, key: &[u8; 16], block: &mut [u8; 16]) {
        let c = Aes128::new(key.into());
        c.encrypt_block(block.into());
    }
}

const VERSION: u8 = 1;
const KEY: [u8; 16] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
const GW: u32 = 0x4E42_0001;
const NODE: u32 = 0x0000_0413; // low32(DevEUI) of the bench STICKER 0413

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn header(ft: u8, flags: u8, src: u32, dest: u32, ctr: u32) -> Vec<u8> {
    let mut h = vec![(VERSION << 5) | (ft & 0x1F), flags];
    h.extend_from_slice(&src.to_le_bytes());
    h.extend_from_slice(&dest.to_le_bytes());
    h.extend_from_slice(&ctr.to_le_bytes());
    h
}

fn vector(name: &str, ft: u8, flags: u8, src: u32, dest: u32, ctr: u32, pt: &[u8]) -> (String, Vec<u8>) {
    let hdr = header(ft, flags, src, dest, ctr);
    let nonce = nonce_for(src, ctr, 0);
    let mut ccm = Ccm::new(SwAes);
    let mut ct = pt.to_vec();
    let tag = ccm.seal(&KEY, &nonce, &hdr, &mut ct);
    let mut frame = hdr.clone();
    frame.extend_from_slice(&ct);
    frame.extend_from_slice(&tag);
    // Round-trip through the reference open().
    let mut back = ct.clone();
    let t: [u8; TAG_LEN] = tag;
    assert!(ccm.open(&KEY, &nonce, &hdr, &mut back, &t));
    assert_eq!(back, pt);
    let j = format!(
        "  \"{name}\": {{\n    \"frame_type\": {ft},\n    \"flags\": {flags},\n    \"src\": {src},\n    \"dest\": {dest},\n    \"counter\": {ctr},\n    \"plaintext\": \"{}\",\n    \"header\": \"{}\",\n    \"nonce\": \"{}\",\n    \"ciphertext\": \"{}\",\n    \"tag\": \"{}\",\n    \"frame\": \"{}\",\n    \"frame_len\": {}\n  }}",
        hex(pt), hex(&hdr), hex(&nonce), hex(&ct), hex(&tag), hex(&frame), frame.len()
    );
    (j, frame)
}

fn ack_payload(acked: u32, rssi: i8, flags: u8) -> Vec<u8> {
    let mut p = acked.to_le_bytes().to_vec();
    p.push(rssi as u8);
    p.push(flags);
    p
}

fn main() {
    // Stage-1 data envelope 0x81 ‖ port ‖ protobuf (dummy protobuf bytes).
    let mut tel = vec![0x81, 0x02];
    tel.extend((0u8..28).map(|i| i.wrapping_mul(7)));
    let max: Vec<u8> = (0u8..74).collect();
    let ctrl = vec![0x91, 0x20, 0x00]; // control envelope: TimeReq, len 0

    let mut out = Vec::new();
    out.push(vector("uplink_unconfirmed", 0, 0x00, NODE, GW, 1, &tel).0);
    out.push(vector("uplink_confirmed", 0, 0x01, NODE, GW, 2, &tel).0);
    out.push(vector("ack_no_pending", 1, 0x00, GW, NODE, 100, &ack_payload(2, -57, 0)).0);
    let (j, ack_pend) = vector("ack_pending", 1, 0x00, GW, NODE, 101, &ack_payload(2, -57, 1));
    out.push(j);
    out.push(vector("downlink_data", 0, 0x00, GW, NODE, 102, &[0x81, 0x55, 0xAA, 0xBB, 0xCC]).0);
    out.push(vector("uplink_control_timereq", 0, 0x01, NODE, GW, 3, &ctrl).0);
    out.push(vector("uplink_max_payload", 0, 0x01, NODE, GW, 4, &max).0);
    out.push(vector("uplink_empty", 0, 0x00, NODE, GW, 5, &[]).0);
    out.push(vector("uplink_counter_high", 0, 0x01, NODE, GW, 0xFFFF_FFFE, &tel).0);

    // Cross-check the ACK vector against the reference ACK acceptance kernel.
    let mut w = AckWait::new(NODE, GW, 2);
    let p = &ack_pend[14..ack_pend.len() - TAG_LEN];
    let mut pt = p.to_vec();
    let mut ccm = Ccm::new(SwAes);
    let nonce = nonce_for(GW, 101, 0);
    let tag: [u8; TAG_LEN] = ack_pend[ack_pend.len() - TAG_LEN..].try_into().unwrap();
    assert!(ccm.open(&KEY, &nonce, &ack_pend[..14], &mut pt, &tag));
    assert_eq!(w.offer(true, GW, NODE, &pt), AckVerdict::Resolved);
    assert!(ack_meta(&pt).pending);

    println!("{{");
    println!("  \"_comment\": \"TOWER radio frame KAT (wire v1, hardwario/tower 24259e3). Header ver_type(1: ver<<5|type) flags(1) src(4 LE) dest(4 LE) counter(4 LE) = 14 B, all CCM AAD; nonce src(4 LE) counter(4 LE) bulk_idx(3 LE)=0 00 00; AES-128-CCM N=13 L=2 M=8. Types Data 0, Ack 1; flag CONFIRMED bit0. ACK payload acked(4 LE) rssi(i8) flags(PENDING bit0); ACK uses the ACKer's own counter. Data payload = stage-1 envelope 0x81 port protobuf / 0x91 control. Generated by ~/Documents/claude/Scripts/tower_kat_gen (tower-radio-core Ccm + tower-net-core nonce_for/AckWait).\",");
    println!("  \"key\": \"{}\",", hex(&KEY));
    println!("  \"gw_addr\": {GW},");
    println!("  \"node_addr\": {NODE},");
    println!("{}", out.join(",\n"));
    println!("}}");
}
