/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* GENERATED by `west sensorgen` from app_w1_slots.yaml — do not edit (#430).
 *
 * Sensor type registry: slot 0 is the motherboard, slots 1..4 are 1-Wire slots
 * whose type is configured per slot. Every type publishes a channel table; a
 * channel is addressed as (type, ch). Type ids and channel numbers are
 * append-only (a removed channel stays with APP_SENSOR_F_RETIRED). */

#ifndef APP_SENSOR_TYPES_H_
#define APP_SENSOR_TYPES_H_

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APP_SENSOR_REGISTRY_VERSION 1

/* Channel limits: the motherboard's valid mask is a uint32, a 1-Wire type's
 * reading array is sized APP_SENSOR_W1_CH_MAX (D6). */
#define APP_SENSOR_MB_CH_MAX 32
#define APP_SENSOR_W1_CH_MAX 10

enum app_sensor_type_id {
	APP_SENSOR_TYPE_NONE = 0,
	APP_SENSOR_TYPE_MOTHERBOARD = 1,
	APP_SENSOR_TYPE_DALLAS = 2,
	APP_SENSOR_TYPE_MACHINE_PROBE = 3,
};

/* motherboard channels */
enum app_sensor_ch_motherboard {
	APP_SENSOR_CH_MOTHERBOARD_TEMPERATURE = 0,
	APP_SENSOR_CH_MOTHERBOARD_HUMIDITY = 1,
	APP_SENSOR_CH_MOTHERBOARD_PRESSURE = 2,
	APP_SENSOR_CH_MOTHERBOARD_ILLUMINANCE = 3,
	APP_SENSOR_CH_MOTHERBOARD_TEMPERATURE_BARO = 4,
	APP_SENSOR_CH_MOTHERBOARD_HALL_LEFT_STATE = 5,
	APP_SENSOR_CH_MOTHERBOARD_HALL_LEFT_COUNT = 6,
	APP_SENSOR_CH_MOTHERBOARD_HALL_RIGHT_STATE = 7,
	APP_SENSOR_CH_MOTHERBOARD_HALL_RIGHT_COUNT = 8,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_A_STATE = 9,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_A_COUNT = 10,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_A_VOLTAGE = 11,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_B_STATE = 12,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_B_COUNT = 13,
	APP_SENSOR_CH_MOTHERBOARD_INPUT_B_VOLTAGE = 14,
	APP_SENSOR_CH_MOTHERBOARD_PIR_MOTION = 15,
	APP_SENSOR_CH_MOTHERBOARD_PIR_COUNT = 16,
	APP_SENSOR_CH_MOTHERBOARD_ACCEL_MOTION = 17,
	APP_SENSOR_CH_MOTHERBOARD_ACCEL_COUNT = 18,
	APP_SENSOR_CH_MOTHERBOARD_ACCEL_ORIENTATION = 19,
	APP_SENSOR_CH_MOTHERBOARD_BATTERY_VOLTAGE = 20,
	APP_SENSOR_CH_MOTHERBOARD_ALTITUDE = 21,
	APP_SENSOR_CH_MOTHERBOARD_COUNT
};

/* dallas channels */
enum app_sensor_ch_dallas {
	APP_SENSOR_CH_DALLAS_TEMPERATURE = 0,
	APP_SENSOR_CH_DALLAS_COUNT
};

/* machine-probe channels */
enum app_sensor_ch_machine_probe {
	APP_SENSOR_CH_MACHINE_PROBE_TEMPERATURE = 0,
	APP_SENSOR_CH_MACHINE_PROBE_HUMIDITY = 1,
	APP_SENSOR_CH_MACHINE_PROBE_TEMPERATURE_AUX = 2,
	APP_SENSOR_CH_MACHINE_PROBE_ILLUMINANCE = 3,
	APP_SENSOR_CH_MACHINE_PROBE_MAGNETIC_FIELD = 4,
	APP_SENSOR_CH_MACHINE_PROBE_TILT = 5,
	APP_SENSOR_CH_MACHINE_PROBE_ACCEL_X = 6,
	APP_SENSOR_CH_MACHINE_PROBE_ACCEL_Y = 7,
	APP_SENSOR_CH_MACHINE_PROBE_ACCEL_Z = 8,
	APP_SENSOR_CH_MACHINE_PROBE_COUNT
};

enum app_sensor_kind {
	APP_SENSOR_KIND_THRESHOLD, /* lo/hi/dwell */
	APP_SENSOR_KIND_STATE,     /* from/to/dwell (digital 0/1) */
	APP_SENSOR_KIND_RATE,      /* hi = max counter delta per report interval */
	APP_SENSOR_KIND_NONE,      /* value only, not an alarm target */
};

enum app_sensor_wire_type {
	APP_SENSOR_WIRE_SINT32,
	APP_SENSOR_WIRE_UINT32,
};

/* Fixed-width history encodings; the top value is the "absent" sentinel. */
enum app_sensor_hist_enc {
	APP_SENSOR_HIST_NONE, /* not recordable */
	APP_SENSOR_HIST_U8,
	APP_SENSOR_HIST_I16,
	APP_SENSOR_HIST_U16,
	APP_SENSOR_HIST_I32,
	APP_SENSOR_HIST_U32,
};

#define APP_SENSOR_F_MOMENTARY     0x01 /* pulse source, STATE rules are edge-only */
#define APP_SENSOR_F_COUNTER       0x02 /* raw uint32 counter (exact integer delta) */
#define APP_SENSOR_F_LIVENESS      0x04 /* watched by the no-data watchdog */
#define APP_SENSOR_F_WATCHDOG_ONLY 0x08 /* built-in watchdog input, not a rule target */
#define APP_SENSOR_F_RETIRED       0x10 /* kept for numbering only */
#define APP_SENSOR_F_RANGE         0x20 /* range_min/range_max are valid */

/* Capability gate of a motherboard channel: offset of its bool in struct
 * app_config, or APP_SENSOR_NO_CAP (always on / 1-Wire channel). */
#define APP_SENSOR_NO_CAP 0xFFFF

struct app_sensor_channel {
	const char *name;
	uint8_t kind;      /* enum app_sensor_kind */
	uint8_t flags;     /* APP_SENSOR_F_* */
	uint8_t wire_type; /* enum app_sensor_wire_type */
	uint8_t hist_enc;  /* enum app_sensor_hist_enc */
	uint16_t cap_off;  /* offsetof(struct app_config, cap_*) or APP_SENSOR_NO_CAP */
	float wire_scale;  /* wire value = round(phys * wire_scale) */
	float hist_scale;  /* history value = round(phys * hist_scale) */
	float range_min;   /* valid physical range (APP_SENSOR_F_RANGE) */
	float range_max;
};

struct app_sensor_type {
	const char *name;
	const struct app_sensor_channel *channels;
	uint8_t id;            /* enum app_sensor_type_id */
	uint8_t w1_family;     /* 1-Wire family code, 0 = motherboard */
	uint8_t channel_count; /* incl. retired channels */
};

/* Type by id / by 1-Wire family code / by name; NULL if unknown. */
const struct app_sensor_type *app_sensor_type_get(uint8_t id);
const struct app_sensor_type *app_sensor_type_by_family(uint8_t family);
const struct app_sensor_type *app_sensor_type_by_name(const char *name);

/* Channel `ch` of type `id`; NULL if the type or channel is unknown. */
const struct app_sensor_channel *app_sensor_channel_get(uint8_t id, uint8_t ch);

/* Channel number of `name` in type `id`, or -1. */
int app_sensor_channel_by_name(uint8_t id, const char *name);

#ifdef __cplusplus
}
#endif

#endif /* APP_SENSOR_TYPES_H_ */
