/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "app_cmd.h"
#include "app_config.h"
#include "app_log.h"
#include "app_lrw.h"

/* Nanopb includes */
#include <pb_decode.h>
#include <pb_encode.h>
#include "src/nfc_config.pb.h"

/* Zephyr includes */
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/sys/util.h>

/* Generated by Zephyr build (git describe of the app tree). */
#include <zephyr/version.h>

/* Standard includes */
#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

LOG_MODULE_REGISTER(app_cmd, LOG_LEVEL_DBG);

static void fill_info(DownlinkResponse_Info *info)
{
	strncpy(info->build_version, STRINGIFY(BUILD_VERSION),
		sizeof(info->build_version) - 1);
	info->build_version[sizeof(info->build_version) - 1] = '\0';

	memcpy(info->dev_eui.bytes, g_app_config.lrw_deveui, sizeof(g_app_config.lrw_deveui));
	info->dev_eui.size = sizeof(g_app_config.lrw_deveui);

	info->serial_number = g_app_config.serial_number;

	strncpy(info->board, STRINGIFY(CONFIG_BOARD_TARGET), sizeof(info->board) - 1);
	info->board[sizeof(info->board) - 1] = '\0';

	info->lrw_state = (uint32_t)app_lrw_get_state();
}

static void make_error(DownlinkResponse *resp, DownlinkResponse_Error_Code code,
		       const char *detail)
{
	resp->which_body = DownlinkResponse_error_tag;
	resp->body.error.code = code;
	resp->body.error.fault_field = 0;

	if (detail) {
		strncpy(resp->body.error.detail, detail, sizeof(resp->body.error.detail) - 1);
		resp->body.error.detail[sizeof(resp->body.error.detail) - 1] = '\0';
	} else {
		resp->body.error.detail[0] = '\0';
	}
}

static void dispatch(enum app_cmd_transport transport, const DownlinkCommand *cmd,
		     DownlinkResponse *resp)
{
	ARG_UNUSED(transport);

	resp->seq = cmd->seq;

	switch (cmd->which_body) {
	case DownlinkCommand_get_info_tag:
		resp->which_body = DownlinkResponse_info_tag;
		fill_info(&resp->body.info);
		break;

	default:
		LOG_WRN("Command tag %u not implemented in Phase 1", cmd->which_body);
		make_error(resp, DownlinkResponse_Error_Code_UNKNOWN,
			   "not implemented in phase 1");
		break;
	}
}

int app_cmd_handle(enum app_cmd_transport transport, const uint8_t *in, size_t in_len,
		   uint8_t *out, size_t out_cap, size_t *out_len)
{
	if (!in || !out || !out_len) {
		return -EINVAL;
	}

	*out_len = 0;

	DownlinkCommand cmd = DownlinkCommand_init_zero;
	DownlinkResponse resp = DownlinkResponse_init_zero;

	pb_istream_t istream = pb_istream_from_buffer(in, in_len);
	if (!pb_decode(&istream, DownlinkCommand_fields, &cmd)) {
		LOG_ERR_CALL_FAILED_STR("pb_decode", PB_GET_ERROR(&istream));
		resp.seq = 0;
		make_error(&resp, DownlinkResponse_Error_Code_BAD_REQUEST,
			   PB_GET_ERROR(&istream));
	} else {
		dispatch(transport, &cmd, &resp);
	}

	pb_ostream_t ostream = pb_ostream_from_buffer(out, out_cap);
	if (!pb_encode(&ostream, DownlinkResponse_fields, &resp)) {
		LOG_ERR_CALL_FAILED_STR("pb_encode", PB_GET_ERROR(&ostream));
		return -EMSGSIZE;
	}

	*out_len = ostream.bytes_written;
	return 0;
}
