/* WARNING: This file is auto-generated by `west configen`. Do not modify manually. */

/*
 * Copyright (c) 2025 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

/* Standard includes */
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum app_config_lrw_region {
	APP_CONFIG_LRW_REGION_EU868 = 0,
	APP_CONFIG_LRW_REGION_US915 = 1,
	APP_CONFIG_LRW_REGION_AU915 = 2,
};

enum app_config_lrw_network {
	APP_CONFIG_LRW_NETWORK_PUBLIC = 0,
	APP_CONFIG_LRW_NETWORK_PRIVATE = 1,
};

enum app_config_lrw_activation {
	APP_CONFIG_LRW_ACTIVATION_OTAA = 0,
	APP_CONFIG_LRW_ACTIVATION_ABP = 1,
};

enum app_config_motion_sensitivity {
	APP_CONFIG_MOTION_SENSITIVITY_OFF = 0,
	APP_CONFIG_MOTION_SENSITIVITY_LOW = 1,
	APP_CONFIG_MOTION_SENSITIVITY_MEDIUM = 2,
	APP_CONFIG_MOTION_SENSITIVITY_HIGH = 3,
};

#define APP_CONFIG_VERSION 3

struct app_config {
	uint32_t config_version;
	uint8_t secret_key[16];
	uint32_t serial_number;
	uint32_t nonce_counter;
	bool calibration;
	int interval_sample;
	int interval_report;
	bool history_enable;
	uint32_t history_sensors;
	int alarm_limit;
	int alarm_notif_time;
	enum app_config_lrw_region lrw_region;
	int lrw_sub_band;
	enum app_config_lrw_network lrw_network;
	bool lrw_adr;
	enum app_config_lrw_activation lrw_activation;
	uint8_t lrw_deveui[8];
	uint8_t lrw_joineui[8];
	uint8_t lrw_nwkkey[16];
	uint8_t lrw_appkey[16];
	uint8_t lrw_devaddr[4];
	uint8_t lrw_nwkskey[16];
	uint8_t lrw_appskey[16];
	bool cap_hall_left;
	bool cap_hall_right;
	bool cap_input_a;
	bool cap_input_b;
	bool cap_light_sensor;
	bool cap_barometer;
	bool cap_pir_detector;
	bool cap_w1_sensors;
	bool cap_accelerometer;
	bool hall_left_counter;
	bool hall_right_counter;
	bool input_a_counter;
	bool input_b_counter;
	float temperature_corr;
	float t1_corr;
	float t2_corr;
	enum app_config_motion_sensitivity accel_motion_sensitivity;
	uint8_t sensor1_rom[8];
	uint8_t sensor2_rom[8];
	uint8_t sensor3_rom[8];
	uint8_t sensor4_rom[8];
};

extern struct app_config g_app_config;

struct app_config *app_config(void);

#ifdef __cplusplus
}
#endif

#endif /* APP_CONFIG_H_ */
