/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by configen from app_config.yml — do not edit by hand.
 * Maps each proto config submessage to the flat app_config struct:
 *  - apply_<group>(): SetParam / NFC ingest (validates, records first FAULT)
 *  - fill_<group>():  GetConfig dump (only requested, non-secret fields)
 */

#include "app_config_ingest.h"
#include "app_config.h"
#include "app_log.h"

/* Zephyr includes */
#include <zephyr/logging/log.h>
#include <zephyr/sys/util.h>

/* Standard includes */
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config_ingest, LOG_LEVEL_DBG);

/* Record the first offending proto field tag and mark the result invalid. The
 * apply still processes the remaining fields (best effort) so NFC ingest keeps
 * its "skip invalid, apply the rest" behaviour; SetParam inspects fault_field. */
#define FAULT(tag)                                                                                 \
	do {                                                                                       \
		if (fault_field && *fault_field == 0) {                                            \
			*fault_field = (tag);                                                      \
		}                                                                                  \
		ret = -EINVAL;                                                                     \
	} while (0)

static bool requested(const uint32_t *ids, size_t n, uint32_t tag)
{
	for (size_t i = 0; i < n; i++) {
		if (ids[i] == tag) {
			return true;
		}
	}
	return false;
}

int app_config_apply_lorawan(const AppConfigMessage_Lorawan *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_region) {
		if ((int)src->region >= 0 && (int)src->region <= 2) {
			config->lrw_region = (enum app_config_lrw_region)src->region;
		} else {
			FAULT(1);
		}
	}
	if (src->has_sub_band) {
		int val = src->sub_band;

		if ((val >= 0 && val <= 8)) {
			config->lrw_sub_band = val;
		} else {
			FAULT(2);
		}
	}
	if (src->has_network) {
		if ((int)src->network >= 0 && (int)src->network <= 1) {
			config->lrw_network = (enum app_config_lrw_network)src->network;
		} else {
			FAULT(3);
		}
	}
	if (src->has_adr) {
		config->lrw_adr = src->adr;
	}
	if (src->has_activation) {
		if ((int)src->activation >= 0 && (int)src->activation <= 1) {
			config->lrw_activation = (enum app_config_lrw_activation)src->activation;
		} else {
			FAULT(5);
		}
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_deveui) {
		memcpy(config->lrw_deveui, src->deveui, sizeof(config->lrw_deveui));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_joineui) {
		memcpy(config->lrw_joineui, src->joineui, sizeof(config->lrw_joineui));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_nwkkey) {
		memcpy(config->lrw_nwkkey, src->nwkkey, sizeof(config->lrw_nwkkey));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_appkey) {
		memcpy(config->lrw_appkey, src->appkey, sizeof(config->lrw_appkey));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_devaddr) {
		memcpy(config->lrw_devaddr, src->devaddr, sizeof(config->lrw_devaddr));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_nwkskey) {
		memcpy(config->lrw_nwkskey, src->nwkskey, sizeof(config->lrw_nwkskey));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_appskey) {
		memcpy(config->lrw_appskey, src->appskey, sizeof(config->lrw_appskey));
	}
	if (src->has_link_check_interval) {
		int val = src->link_check_interval;

		if ((val >= 0 && val <= 255)) {
			config->lrw_link_check_interval = val;
		} else {
			FAULT(13);
		}
	}
	if (src->has_link_check_fail_rejoin) {
		int val = src->link_check_fail_rejoin;

		if ((val >= 1 && val <= 255)) {
			config->lrw_link_check_fail_rejoin = val;
		} else {
			FAULT(14);
		}
	}
	return ret;
}

void app_config_fill_lorawan(AppConfigMessage_Lorawan *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_region = true;
		dst->region = (AppConfigMessage_Lorawan_Region)c->lrw_region;
	}
	if (requested(ids, n, 2)) {
		dst->has_sub_band = true;
		dst->sub_band = c->lrw_sub_band;
	}
	if (requested(ids, n, 3)) {
		dst->has_network = true;
		dst->network = (AppConfigMessage_Lorawan_Network)c->lrw_network;
	}
	if (requested(ids, n, 4)) {
		dst->has_adr = true;
		dst->adr = c->lrw_adr;
	}
	if (requested(ids, n, 5)) {
		dst->has_activation = true;
		dst->activation = (AppConfigMessage_Lorawan_Activation)c->lrw_activation;
	}
	if (requested(ids, n, 6)) {
		dst->has_deveui = true;
		memcpy(dst->deveui, c->lrw_deveui, sizeof(c->lrw_deveui));
	}
	if (requested(ids, n, 7)) {
		dst->has_joineui = true;
		memcpy(dst->joineui, c->lrw_joineui, sizeof(c->lrw_joineui));
	}
	if (requested(ids, n, 8)) {
		dst->has_nwkkey = true;
		memcpy(dst->nwkkey, c->lrw_nwkkey, sizeof(c->lrw_nwkkey));
	}
	if (requested(ids, n, 9)) {
		dst->has_appkey = true;
		memcpy(dst->appkey, c->lrw_appkey, sizeof(c->lrw_appkey));
	}
	if (requested(ids, n, 10)) {
		dst->has_devaddr = true;
		memcpy(dst->devaddr, c->lrw_devaddr, sizeof(c->lrw_devaddr));
	}
	if (requested(ids, n, 11)) {
		dst->has_nwkskey = true;
		memcpy(dst->nwkskey, c->lrw_nwkskey, sizeof(c->lrw_nwkskey));
	}
	if (requested(ids, n, 12)) {
		dst->has_appskey = true;
		memcpy(dst->appskey, c->lrw_appskey, sizeof(c->lrw_appskey));
	}
	if (requested(ids, n, 13)) {
		dst->has_link_check_interval = true;
		dst->link_check_interval = c->lrw_link_check_interval;
	}
	if (requested(ids, n, 14)) {
		dst->has_link_check_fail_rejoin = true;
		dst->link_check_fail_rejoin = c->lrw_link_check_fail_rejoin;
	}
}

int app_config_apply_application(const AppConfigMessage_Application *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_calibration) {
		config->calibration = src->calibration;
	}
	if (src->has_interval_sample) {
		int val = src->interval_sample;

		if (val == 0 || (val >= 5 && val <= 3600)) {
			config->interval_sample = val;
		} else {
			FAULT(2);
		}
	}
	if (src->has_interval_report) {
		int val = src->interval_report;

		if ((val >= 60 && val <= 86400)) {
			config->interval_report = val;
		} else {
			FAULT(3);
		}
	}
	if (src->has_history_enable) {
		config->history_enable = src->history_enable;
	}
	if (src->has_history_sensors) {
		config->history_sensors = src->history_sensors;
	}
	return ret;
}

void app_config_fill_application(AppConfigMessage_Application *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_calibration = true;
		dst->calibration = c->calibration;
	}
	if (requested(ids, n, 2)) {
		dst->has_interval_sample = true;
		dst->interval_sample = c->interval_sample;
	}
	if (requested(ids, n, 3)) {
		dst->has_interval_report = true;
		dst->interval_report = c->interval_report;
	}
	if (requested(ids, n, 4)) {
		dst->has_history_enable = true;
		dst->history_enable = c->history_enable;
	}
	if (requested(ids, n, 5)) {
		dst->has_history_sensors = true;
		dst->history_sensors = c->history_sensors;
	}
}

int app_config_apply_sensors(const AppConfigMessage_Sensors *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_cap_hall_left) {
		config->cap_hall_left = src->cap_hall_left;
	}
	if (src->has_cap_hall_right) {
		config->cap_hall_right = src->cap_hall_right;
	}
	if (src->has_cap_input_a) {
		config->cap_input_a = src->cap_input_a;
	}
	if (src->has_cap_input_b) {
		config->cap_input_b = src->cap_input_b;
	}
	if (src->has_cap_light_sensor) {
		config->cap_light_sensor = src->cap_light_sensor;
	}
	if (src->has_cap_barometer) {
		config->cap_barometer = src->cap_barometer;
	}
	if (src->has_cap_pir_detector) {
		config->cap_pir_detector = src->cap_pir_detector;
	}
	if (src->has_cap_w1_sensors) {
		config->cap_w1_sensors = src->cap_w1_sensors;
	}
	if (src->has_cap_accelerometer) {
		config->cap_accelerometer = src->cap_accelerometer;
	}
	if (src->has_accel_motion_sensitivity) {
		if ((int)src->accel_motion_sensitivity >= 0 &&
		    (int)src->accel_motion_sensitivity <= 3) {
			config->accel_motion_sensitivity =
				(enum app_config_motion_sensitivity)src->accel_motion_sensitivity;
		} else {
			FAULT(10);
		}
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_sensor1_rom) {
		memcpy(config->sensor1_rom, src->sensor1_rom, sizeof(config->sensor1_rom));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_sensor2_rom) {
		memcpy(config->sensor2_rom, src->sensor2_rom, sizeof(config->sensor2_rom));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_sensor3_rom) {
		memcpy(config->sensor3_rom, src->sensor3_rom, sizeof(config->sensor3_rom));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_sensor4_rom) {
		memcpy(config->sensor4_rom, src->sensor4_rom, sizeof(config->sensor4_rom));
	}
	return ret;
}

void app_config_fill_sensors(AppConfigMessage_Sensors *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_cap_hall_left = true;
		dst->cap_hall_left = c->cap_hall_left;
	}
	if (requested(ids, n, 2)) {
		dst->has_cap_hall_right = true;
		dst->cap_hall_right = c->cap_hall_right;
	}
	if (requested(ids, n, 3)) {
		dst->has_cap_input_a = true;
		dst->cap_input_a = c->cap_input_a;
	}
	if (requested(ids, n, 4)) {
		dst->has_cap_input_b = true;
		dst->cap_input_b = c->cap_input_b;
	}
	if (requested(ids, n, 5)) {
		dst->has_cap_light_sensor = true;
		dst->cap_light_sensor = c->cap_light_sensor;
	}
	if (requested(ids, n, 6)) {
		dst->has_cap_barometer = true;
		dst->cap_barometer = c->cap_barometer;
	}
	if (requested(ids, n, 7)) {
		dst->has_cap_pir_detector = true;
		dst->cap_pir_detector = c->cap_pir_detector;
	}
	if (requested(ids, n, 8)) {
		dst->has_cap_w1_sensors = true;
		dst->cap_w1_sensors = c->cap_w1_sensors;
	}
	if (requested(ids, n, 9)) {
		dst->has_cap_accelerometer = true;
		dst->cap_accelerometer = c->cap_accelerometer;
	}
	if (requested(ids, n, 10)) {
		dst->has_accel_motion_sensitivity = true;
		dst->accel_motion_sensitivity =
			(AppConfigMessage_Sensors_MotionSensitivity)c->accel_motion_sensitivity;
	}
	if (requested(ids, n, 11)) {
		dst->has_sensor1_rom = true;
		memcpy(dst->sensor1_rom, c->sensor1_rom, sizeof(c->sensor1_rom));
	}
	if (requested(ids, n, 12)) {
		dst->has_sensor2_rom = true;
		memcpy(dst->sensor2_rom, c->sensor2_rom, sizeof(c->sensor2_rom));
	}
	if (requested(ids, n, 13)) {
		dst->has_sensor3_rom = true;
		memcpy(dst->sensor3_rom, c->sensor3_rom, sizeof(c->sensor3_rom));
	}
	if (requested(ids, n, 14)) {
		dst->has_sensor4_rom = true;
		memcpy(dst->sensor4_rom, c->sensor4_rom, sizeof(c->sensor4_rom));
	}
}

int app_config_apply_alarms(const AppConfigMessage_Alarms *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_alarm_limit) {
		int val = src->alarm_limit;

		if ((val >= 0 && val <= 3600)) {
			config->alarm_limit = val;
		} else {
			FAULT(1);
		}
	}
	if (src->has_alarm_notif_time) {
		int val = src->alarm_notif_time;

		if ((val >= 1 && val <= 60)) {
			config->alarm_notif_time = val;
		} else {
			FAULT(2);
		}
	}
	if (src->has_hall_left_counter) {
		config->hall_left_counter = src->hall_left_counter;
	}
	if (src->has_hall_right_counter) {
		config->hall_right_counter = src->hall_right_counter;
	}
	if (src->has_input_a_counter) {
		config->input_a_counter = src->input_a_counter;
	}
	if (src->has_input_b_counter) {
		config->input_b_counter = src->input_b_counter;
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_0) {
		memcpy(config->alarm_0, src->alarm_0, sizeof(config->alarm_0));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_1) {
		memcpy(config->alarm_1, src->alarm_1, sizeof(config->alarm_1));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_2) {
		memcpy(config->alarm_2, src->alarm_2, sizeof(config->alarm_2));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_3) {
		memcpy(config->alarm_3, src->alarm_3, sizeof(config->alarm_3));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_4) {
		memcpy(config->alarm_4, src->alarm_4, sizeof(config->alarm_4));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_5) {
		memcpy(config->alarm_5, src->alarm_5, sizeof(config->alarm_5));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_6) {
		memcpy(config->alarm_6, src->alarm_6, sizeof(config->alarm_6));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_7) {
		memcpy(config->alarm_7, src->alarm_7, sizeof(config->alarm_7));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_8) {
		memcpy(config->alarm_8, src->alarm_8, sizeof(config->alarm_8));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_9) {
		memcpy(config->alarm_9, src->alarm_9, sizeof(config->alarm_9));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_10) {
		memcpy(config->alarm_10, src->alarm_10, sizeof(config->alarm_10));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_11) {
		memcpy(config->alarm_11, src->alarm_11, sizeof(config->alarm_11));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_12) {
		memcpy(config->alarm_12, src->alarm_12, sizeof(config->alarm_12));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_13) {
		memcpy(config->alarm_13, src->alarm_13, sizeof(config->alarm_13));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_14) {
		memcpy(config->alarm_14, src->alarm_14, sizeof(config->alarm_14));
	}
	/* Native fixed_length bytes: nanopb decodes exactly sizeof(field) bytes. */
	if (src->has_alarm_15) {
		memcpy(config->alarm_15, src->alarm_15, sizeof(config->alarm_15));
	}
	return ret;
}

void app_config_fill_alarms(AppConfigMessage_Alarms *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_alarm_limit = true;
		dst->alarm_limit = c->alarm_limit;
	}
	if (requested(ids, n, 2)) {
		dst->has_alarm_notif_time = true;
		dst->alarm_notif_time = c->alarm_notif_time;
	}
	if (requested(ids, n, 3)) {
		dst->has_hall_left_counter = true;
		dst->hall_left_counter = c->hall_left_counter;
	}
	if (requested(ids, n, 4)) {
		dst->has_hall_right_counter = true;
		dst->hall_right_counter = c->hall_right_counter;
	}
	if (requested(ids, n, 5)) {
		dst->has_input_a_counter = true;
		dst->input_a_counter = c->input_a_counter;
	}
	if (requested(ids, n, 6)) {
		dst->has_input_b_counter = true;
		dst->input_b_counter = c->input_b_counter;
	}
	if (requested(ids, n, 7)) {
		dst->has_alarm_0 = true;
		memcpy(dst->alarm_0, c->alarm_0, sizeof(c->alarm_0));
	}
	if (requested(ids, n, 8)) {
		dst->has_alarm_1 = true;
		memcpy(dst->alarm_1, c->alarm_1, sizeof(c->alarm_1));
	}
	if (requested(ids, n, 9)) {
		dst->has_alarm_2 = true;
		memcpy(dst->alarm_2, c->alarm_2, sizeof(c->alarm_2));
	}
	if (requested(ids, n, 10)) {
		dst->has_alarm_3 = true;
		memcpy(dst->alarm_3, c->alarm_3, sizeof(c->alarm_3));
	}
	if (requested(ids, n, 11)) {
		dst->has_alarm_4 = true;
		memcpy(dst->alarm_4, c->alarm_4, sizeof(c->alarm_4));
	}
	if (requested(ids, n, 12)) {
		dst->has_alarm_5 = true;
		memcpy(dst->alarm_5, c->alarm_5, sizeof(c->alarm_5));
	}
	if (requested(ids, n, 13)) {
		dst->has_alarm_6 = true;
		memcpy(dst->alarm_6, c->alarm_6, sizeof(c->alarm_6));
	}
	if (requested(ids, n, 14)) {
		dst->has_alarm_7 = true;
		memcpy(dst->alarm_7, c->alarm_7, sizeof(c->alarm_7));
	}
	if (requested(ids, n, 15)) {
		dst->has_alarm_8 = true;
		memcpy(dst->alarm_8, c->alarm_8, sizeof(c->alarm_8));
	}
	if (requested(ids, n, 16)) {
		dst->has_alarm_9 = true;
		memcpy(dst->alarm_9, c->alarm_9, sizeof(c->alarm_9));
	}
	if (requested(ids, n, 17)) {
		dst->has_alarm_10 = true;
		memcpy(dst->alarm_10, c->alarm_10, sizeof(c->alarm_10));
	}
	if (requested(ids, n, 18)) {
		dst->has_alarm_11 = true;
		memcpy(dst->alarm_11, c->alarm_11, sizeof(c->alarm_11));
	}
	if (requested(ids, n, 19)) {
		dst->has_alarm_12 = true;
		memcpy(dst->alarm_12, c->alarm_12, sizeof(c->alarm_12));
	}
	if (requested(ids, n, 20)) {
		dst->has_alarm_13 = true;
		memcpy(dst->alarm_13, c->alarm_13, sizeof(c->alarm_13));
	}
	if (requested(ids, n, 21)) {
		dst->has_alarm_14 = true;
		memcpy(dst->alarm_14, c->alarm_14, sizeof(c->alarm_14));
	}
	if (requested(ids, n, 22)) {
		dst->has_alarm_15 = true;
		memcpy(dst->alarm_15, c->alarm_15, sizeof(c->alarm_15));
	}
}

bool app_config_ingest(const AppConfigMessage *message)
{
	if (message->has_factory && message->factory) {
		LOG_INF("Factory reset requested via NFC");
		return true;
	}

	/* NFC keeps best-effort semantics: apply valid fields, ignore invalid. */
	if (message->has_lorawan) {
		app_config_apply_lorawan(&message->lorawan, NULL);
	}
	if (message->has_application) {
		app_config_apply_application(&message->application, NULL);
	}
	if (message->has_sensors) {
		app_config_apply_sensors(&message->sensors, NULL);
	}
	if (message->has_alarms) {
		app_config_apply_alarms(&message->alarms, NULL);
	}
	return false;
}
