/* WARNING: This file is auto-generated by `west configen`. Do not modify manually. */

/*
 * Copyright (c) 2025 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "app_config.h"

/* Zephyr includes */
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/shell/shell.h>

/* Standard includes */
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config, LOG_LEVEL_DBG);

#define SETTINGS_PFX "config"

struct app_config g_app_config;

static const struct app_config m_app_config_defaults = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 3,
	.battery_level = 2400,
	.vendor_reset_allow = true,
	.alarm_limit = 10,
	.radio_mode = APP_CONFIG_RADIO_MODE_OFF,
	.lrw_sub_band = 2,
	.lrw_adr = true,
	.lrw_link_check_interval = 5,
	.lrw_link_check_fail_rejoin = 5,
	.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_OFF,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
	.p2p_frequency = 868100000,
	.p2p_spreading_factor = 10,
	.p2p_tx_power = 14,
};

/* Set by h_commit when a schema version migration ran; init persists the
 * migrated config so the stored version is bumped exactly once. */
static bool m_app_config_migrated;

/* Set by init when settings_load fails (corrupt/unreadable NVS): the device then
 * boots on compile-time defaults with its identity + provisioning gone. Queryable
 * so the app can surface a distinct state (LED / GetInfo) instead of silently
 * looking like a blank device (H-4). */
static bool m_app_config_load_failed;

bool app_config_load_failed(void)
{
	return m_app_config_load_failed;
}

static struct app_config m_app_config = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 3,
	.battery_level = 2400,
	.vendor_reset_allow = true,
	.alarm_limit = 10,
	.radio_mode = APP_CONFIG_RADIO_MODE_OFF,
	.lrw_sub_band = 2,
	.lrw_adr = true,
	.lrw_link_check_interval = 5,
	.lrw_link_check_fail_rejoin = 5,
	.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_OFF,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
	.p2p_frequency = 868100000,
	.p2p_spreading_factor = 10,
	.p2p_tx_power = 14,
};

/* Guards m_app_config/g_app_config against concurrent mutation:
 * SetParam (app_cmd.c) and the reset ops below are both reachable from
 * shell/LRW/NFC on different threads with no other synchronization (#340
 * M27) — SetParam takes this via app_config_lock()/_unlock(). */
static K_MUTEX_DEFINE(m_app_config_lock);

void app_config_lock(void)
{
	k_mutex_lock(&m_app_config_lock, K_FOREVER);
}

void app_config_unlock(void)
{
	k_mutex_unlock(&m_app_config_lock);
}

static int h_set(const char *key, size_t len, settings_read_cb read_cb, void *cb_arg)
{
	int ret;
	const char *next;

#define SETTINGS_SET(_key, _var, _size)                                                            \
	do {                                                                                       \
		if (settings_name_steq(key, _key, &next) && !next) {                               \
			if (len != _size) {                                                        \
				return -EINVAL;                                                    \
			}                                                                          \
                                                                                                   \
			ret = read_cb(cb_arg, _var, len);                                          \
                                                                                                   \
			if (ret < 0) {                                                             \
				LOG_ERR("Call `read_cb` failed: %d", ret);                         \
				return ret;                                                        \
			}                                                                          \
                                                                                                   \
			return 0;                                                                  \
		}                                                                                  \
	} while (0)

	SETTINGS_SET("config-version", &m_app_config.config_version,
		     sizeof(m_app_config.config_version));
	SETTINGS_SET("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	SETTINGS_SET("serial-number", &m_app_config.serial_number,
		     sizeof(m_app_config.serial_number));
	SETTINGS_SET("nonce-counter", &m_app_config.nonce_counter,
		     sizeof(m_app_config.nonce_counter));
	SETTINGS_SET("claim-token", m_app_config.claim_token, sizeof(m_app_config.claim_token));
	SETTINGS_SET("vendor-token", m_app_config.vendor_token, sizeof(m_app_config.vendor_token));
	SETTINGS_SET("calibration", &m_app_config.calibration, sizeof(m_app_config.calibration));
	SETTINGS_SET("interval-sample", &m_app_config.interval_sample,
		     sizeof(m_app_config.interval_sample));
	SETTINGS_SET("interval-report", &m_app_config.interval_report,
		     sizeof(m_app_config.interval_report));
	SETTINGS_SET("history-enable", &m_app_config.history_enable,
		     sizeof(m_app_config.history_enable));
	SETTINGS_SET("history-sensors", &m_app_config.history_sensors,
		     sizeof(m_app_config.history_sensors));
	SETTINGS_SET("battery-level", &m_app_config.battery_level,
		     sizeof(m_app_config.battery_level));
	SETTINGS_SET("vendor-reset-allow", &m_app_config.vendor_reset_allow,
		     sizeof(m_app_config.vendor_reset_allow));
	SETTINGS_SET("alarm-limit", &m_app_config.alarm_limit, sizeof(m_app_config.alarm_limit));
	SETTINGS_SET("lrw-region", &m_app_config.lrw_region, sizeof(m_app_config.lrw_region));
	SETTINGS_SET("radio-mode", &m_app_config.radio_mode, sizeof(m_app_config.radio_mode));
	SETTINGS_SET("lrw-sub-band", &m_app_config.lrw_sub_band, sizeof(m_app_config.lrw_sub_band));
	SETTINGS_SET("lrw-network", &m_app_config.lrw_network, sizeof(m_app_config.lrw_network));
	SETTINGS_SET("lrw-adr", &m_app_config.lrw_adr, sizeof(m_app_config.lrw_adr));
	SETTINGS_SET("lrw-activation", &m_app_config.lrw_activation,
		     sizeof(m_app_config.lrw_activation));
	SETTINGS_SET("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	SETTINGS_SET("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	SETTINGS_SET("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	SETTINGS_SET("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	SETTINGS_SET("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	SETTINGS_SET("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	SETTINGS_SET("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	SETTINGS_SET("lrw-link-check-interval", &m_app_config.lrw_link_check_interval,
		     sizeof(m_app_config.lrw_link_check_interval));
	SETTINGS_SET("lrw-link-check-fail-rejoin", &m_app_config.lrw_link_check_fail_rejoin,
		     sizeof(m_app_config.lrw_link_check_fail_rejoin));
	SETTINGS_SET("cap-hall-left", &m_app_config.cap_hall_left,
		     sizeof(m_app_config.cap_hall_left));
	SETTINGS_SET("cap-hall-right", &m_app_config.cap_hall_right,
		     sizeof(m_app_config.cap_hall_right));
	SETTINGS_SET("cap-input-a", &m_app_config.cap_input_a, sizeof(m_app_config.cap_input_a));
	SETTINGS_SET("cap-input-b", &m_app_config.cap_input_b, sizeof(m_app_config.cap_input_b));
	SETTINGS_SET("cap-light-sensor", &m_app_config.cap_light_sensor,
		     sizeof(m_app_config.cap_light_sensor));
	SETTINGS_SET("cap-barometer", &m_app_config.cap_barometer,
		     sizeof(m_app_config.cap_barometer));
	SETTINGS_SET("cap-pir-detector", &m_app_config.cap_pir_detector,
		     sizeof(m_app_config.cap_pir_detector));
	SETTINGS_SET("cap-buzzer", &m_app_config.cap_buzzer, sizeof(m_app_config.cap_buzzer));
	SETTINGS_SET("cap-w1-sensors", &m_app_config.cap_w1_sensors,
		     sizeof(m_app_config.cap_w1_sensors));
	SETTINGS_SET("cap-accelerometer", &m_app_config.cap_accelerometer,
		     sizeof(m_app_config.cap_accelerometer));
	SETTINGS_SET("alarm-0", m_app_config.alarm_0, sizeof(m_app_config.alarm_0));
	SETTINGS_SET("alarm-1", m_app_config.alarm_1, sizeof(m_app_config.alarm_1));
	SETTINGS_SET("alarm-2", m_app_config.alarm_2, sizeof(m_app_config.alarm_2));
	SETTINGS_SET("alarm-3", m_app_config.alarm_3, sizeof(m_app_config.alarm_3));
	SETTINGS_SET("alarm-4", m_app_config.alarm_4, sizeof(m_app_config.alarm_4));
	SETTINGS_SET("alarm-5", m_app_config.alarm_5, sizeof(m_app_config.alarm_5));
	SETTINGS_SET("alarm-6", m_app_config.alarm_6, sizeof(m_app_config.alarm_6));
	SETTINGS_SET("alarm-7", m_app_config.alarm_7, sizeof(m_app_config.alarm_7));
	SETTINGS_SET("alarm-8", m_app_config.alarm_8, sizeof(m_app_config.alarm_8));
	SETTINGS_SET("alarm-9", m_app_config.alarm_9, sizeof(m_app_config.alarm_9));
	SETTINGS_SET("alarm-10", m_app_config.alarm_10, sizeof(m_app_config.alarm_10));
	SETTINGS_SET("alarm-11", m_app_config.alarm_11, sizeof(m_app_config.alarm_11));
	SETTINGS_SET("alarm-12", m_app_config.alarm_12, sizeof(m_app_config.alarm_12));
	SETTINGS_SET("alarm-13", m_app_config.alarm_13, sizeof(m_app_config.alarm_13));
	SETTINGS_SET("alarm-14", m_app_config.alarm_14, sizeof(m_app_config.alarm_14));
	SETTINGS_SET("alarm-15", m_app_config.alarm_15, sizeof(m_app_config.alarm_15));
	SETTINGS_SET("alarm-buzzer-mode", &m_app_config.alarm_buzzer_mode,
		     sizeof(m_app_config.alarm_buzzer_mode));
	SETTINGS_SET("accel-motion-sensitivity", &m_app_config.accel_motion_sensitivity,
		     sizeof(m_app_config.accel_motion_sensitivity));
	SETTINGS_SET("sensor1-rom", m_app_config.sensor1_rom, sizeof(m_app_config.sensor1_rom));
	SETTINGS_SET("sensor2-rom", m_app_config.sensor2_rom, sizeof(m_app_config.sensor2_rom));
	SETTINGS_SET("sensor3-rom", m_app_config.sensor3_rom, sizeof(m_app_config.sensor3_rom));
	SETTINGS_SET("sensor4-rom", m_app_config.sensor4_rom, sizeof(m_app_config.sensor4_rom));
	SETTINGS_SET("hall-left-counter", &m_app_config.hall_left_counter,
		     sizeof(m_app_config.hall_left_counter));
	SETTINGS_SET("hall-right-counter", &m_app_config.hall_right_counter,
		     sizeof(m_app_config.hall_right_counter));
	SETTINGS_SET("input-a-counter", &m_app_config.input_a_counter,
		     sizeof(m_app_config.input_a_counter));
	SETTINGS_SET("input-b-counter", &m_app_config.input_b_counter,
		     sizeof(m_app_config.input_b_counter));
	SETTINGS_SET("p2p-frequency", &m_app_config.p2p_frequency,
		     sizeof(m_app_config.p2p_frequency));
	SETTINGS_SET("p2p-spreading-factor", &m_app_config.p2p_spreading_factor,
		     sizeof(m_app_config.p2p_spreading_factor));
	SETTINGS_SET("p2p-tx-power", &m_app_config.p2p_tx_power, sizeof(m_app_config.p2p_tx_power));

#undef SETTINGS_SET

	return -ENOENT;
}

static int h_commit(void)
{
	LOG_DBG("Loaded settings in full");

	/* L-33: migrate only on an UPGRADE (stored < current). Using != also fired on
	 * a downgrade and reset the application parameters to the older firmware's
	 * defaults; a downgrade should keep the stored config as-is (values are clamped
	 * below anyway). */
	if (m_app_config.config_version < APP_CONFIG_VERSION) {
		LOG_WRN("Config version older than firmware (stored=%u, expected=%u), migrating",
			m_app_config.config_version, APP_CONFIG_VERSION);

		/* Reset application parameters to defaults, but carry over factory
		 * identity and network credentials (the `device_reset` persistent
		 * tier in the YAML, #299) so a schema bump never un-provisions a
		 * field device. */
		struct app_config stored = m_app_config;

		m_app_config = m_app_config_defaults;
		memcpy(m_app_config.secret_key, stored.secret_key, sizeof(m_app_config.secret_key));
		m_app_config.serial_number = stored.serial_number;
		m_app_config.nonce_counter = stored.nonce_counter;
		memcpy(m_app_config.claim_token, stored.claim_token,
		       sizeof(m_app_config.claim_token));
		memcpy(m_app_config.vendor_token, stored.vendor_token,
		       sizeof(m_app_config.vendor_token));
		m_app_config.vendor_reset_allow = stored.vendor_reset_allow;
		m_app_config.lrw_region = stored.lrw_region;
		m_app_config.radio_mode = stored.radio_mode;
		m_app_config.lrw_sub_band = stored.lrw_sub_band;
		m_app_config.lrw_network = stored.lrw_network;
		m_app_config.lrw_adr = stored.lrw_adr;
		m_app_config.lrw_activation = stored.lrw_activation;
		memcpy(m_app_config.lrw_deveui, stored.lrw_deveui, sizeof(m_app_config.lrw_deveui));
		memcpy(m_app_config.lrw_joineui, stored.lrw_joineui,
		       sizeof(m_app_config.lrw_joineui));
		memcpy(m_app_config.lrw_nwkkey, stored.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
		memcpy(m_app_config.lrw_appkey, stored.lrw_appkey, sizeof(m_app_config.lrw_appkey));
		memcpy(m_app_config.lrw_devaddr, stored.lrw_devaddr,
		       sizeof(m_app_config.lrw_devaddr));
		memcpy(m_app_config.lrw_nwkskey, stored.lrw_nwkskey,
		       sizeof(m_app_config.lrw_nwkskey));
		memcpy(m_app_config.lrw_appskey, stored.lrw_appskey,
		       sizeof(m_app_config.lrw_appskey));
		m_app_config.p2p_frequency = stored.p2p_frequency;
		m_app_config.p2p_spreading_factor = stored.p2p_spreading_factor;
		m_app_config.p2p_tx_power = stored.p2p_tx_power;

		m_app_config_migrated = true;
	}

	/* Clamp loaded values into their configured ranges so a corrupted or forged
	 * NVS record can't leave the device in a broken state (e.g. interval=0 ->
	 * K_SECONDS(0), or an out-of-range enum that no code path expects). */
	if (m_app_config.interval_sample < 5 && m_app_config.interval_sample != 0) {
		m_app_config.interval_sample = 5;
	}
	if (m_app_config.interval_sample > 3600) {
		m_app_config.interval_sample = 3600;
	}
	if (m_app_config.interval_report < 60) {
		m_app_config.interval_report = 60;
	}
	if (m_app_config.interval_report > 86400) {
		m_app_config.interval_report = 86400;
	}
	if (m_app_config.battery_level < 1000) {
		m_app_config.battery_level = 1000;
	}
	if (m_app_config.battery_level > 3600) {
		m_app_config.battery_level = 3600;
	}
	if (m_app_config.alarm_limit < 0) {
		m_app_config.alarm_limit = 0;
	}
	if (m_app_config.alarm_limit > 3600) {
		m_app_config.alarm_limit = 3600;
	}
	if ((int)m_app_config.lrw_region < 0 || (int)m_app_config.lrw_region > 2) {
		m_app_config.lrw_region = 0;
	}
	if ((int)m_app_config.radio_mode < 0 || (int)m_app_config.radio_mode > 2) {
		m_app_config.radio_mode = APP_CONFIG_RADIO_MODE_OFF;
	}
	if (m_app_config.lrw_sub_band < 0) {
		m_app_config.lrw_sub_band = 0;
	}
	if (m_app_config.lrw_sub_band > 8) {
		m_app_config.lrw_sub_band = 8;
	}
	if ((int)m_app_config.lrw_network < 0 || (int)m_app_config.lrw_network > 1) {
		m_app_config.lrw_network = 0;
	}
	if ((int)m_app_config.lrw_activation < 0 || (int)m_app_config.lrw_activation > 1) {
		m_app_config.lrw_activation = 0;
	}
	if (m_app_config.lrw_link_check_interval < 0) {
		m_app_config.lrw_link_check_interval = 0;
	}
	if (m_app_config.lrw_link_check_interval > 255) {
		m_app_config.lrw_link_check_interval = 255;
	}
	if (m_app_config.lrw_link_check_fail_rejoin < 1) {
		m_app_config.lrw_link_check_fail_rejoin = 1;
	}
	if (m_app_config.lrw_link_check_fail_rejoin > 255) {
		m_app_config.lrw_link_check_fail_rejoin = 255;
	}
	if ((int)m_app_config.alarm_buzzer_mode < 0 || (int)m_app_config.alarm_buzzer_mode > 7) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_OFF;
	}
	if ((int)m_app_config.accel_motion_sensitivity < 0 ||
	    (int)m_app_config.accel_motion_sensitivity > 3) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF;
	}
	if (m_app_config.p2p_frequency < 863000000) {
		m_app_config.p2p_frequency = 863000000;
	}
	if (m_app_config.p2p_frequency > 870000000) {
		m_app_config.p2p_frequency = 870000000;
	}
	if (m_app_config.p2p_spreading_factor < 6) {
		m_app_config.p2p_spreading_factor = 6;
	}
	if (m_app_config.p2p_spreading_factor > 12) {
		m_app_config.p2p_spreading_factor = 12;
	}
	if (m_app_config.p2p_tx_power < 2) {
		m_app_config.p2p_tx_power = 2;
	}
	if (m_app_config.p2p_tx_power > 22) {
		m_app_config.p2p_tx_power = 22;
	}

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));
	return 0;
}

static int h_export(int (*export_func)(const char *name, const void *val, size_t val_len))
{
#define EXPORT_FUNC(_key, _var, _size)                                                             \
	do {                                                                                       \
		(void)export_func(SETTINGS_PFX "/" _key, _var, _size);                             \
	} while (0)

	EXPORT_FUNC("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	EXPORT_FUNC("serial-number", &m_app_config.serial_number,
		    sizeof(m_app_config.serial_number));
	EXPORT_FUNC("nonce-counter", &m_app_config.nonce_counter,
		    sizeof(m_app_config.nonce_counter));
	EXPORT_FUNC("claim-token", m_app_config.claim_token, sizeof(m_app_config.claim_token));
	EXPORT_FUNC("vendor-token", m_app_config.vendor_token, sizeof(m_app_config.vendor_token));
	EXPORT_FUNC("calibration", &m_app_config.calibration, sizeof(m_app_config.calibration));
	EXPORT_FUNC("interval-sample", &m_app_config.interval_sample,
		    sizeof(m_app_config.interval_sample));
	EXPORT_FUNC("interval-report", &m_app_config.interval_report,
		    sizeof(m_app_config.interval_report));
	EXPORT_FUNC("history-enable", &m_app_config.history_enable,
		    sizeof(m_app_config.history_enable));
	EXPORT_FUNC("history-sensors", &m_app_config.history_sensors,
		    sizeof(m_app_config.history_sensors));
	EXPORT_FUNC("battery-level", &m_app_config.battery_level,
		    sizeof(m_app_config.battery_level));
	EXPORT_FUNC("vendor-reset-allow", &m_app_config.vendor_reset_allow,
		    sizeof(m_app_config.vendor_reset_allow));
	EXPORT_FUNC("alarm-limit", &m_app_config.alarm_limit, sizeof(m_app_config.alarm_limit));
	EXPORT_FUNC("lrw-region", &m_app_config.lrw_region, sizeof(m_app_config.lrw_region));
	EXPORT_FUNC("radio-mode", &m_app_config.radio_mode, sizeof(m_app_config.radio_mode));
	EXPORT_FUNC("lrw-sub-band", &m_app_config.lrw_sub_band, sizeof(m_app_config.lrw_sub_band));
	EXPORT_FUNC("lrw-network", &m_app_config.lrw_network, sizeof(m_app_config.lrw_network));
	EXPORT_FUNC("lrw-adr", &m_app_config.lrw_adr, sizeof(m_app_config.lrw_adr));
	EXPORT_FUNC("lrw-activation", &m_app_config.lrw_activation,
		    sizeof(m_app_config.lrw_activation));
	EXPORT_FUNC("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	EXPORT_FUNC("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	EXPORT_FUNC("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	EXPORT_FUNC("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	EXPORT_FUNC("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	EXPORT_FUNC("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	EXPORT_FUNC("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	EXPORT_FUNC("lrw-link-check-interval", &m_app_config.lrw_link_check_interval,
		    sizeof(m_app_config.lrw_link_check_interval));
	EXPORT_FUNC("lrw-link-check-fail-rejoin", &m_app_config.lrw_link_check_fail_rejoin,
		    sizeof(m_app_config.lrw_link_check_fail_rejoin));
	EXPORT_FUNC("cap-hall-left", &m_app_config.cap_hall_left,
		    sizeof(m_app_config.cap_hall_left));
	EXPORT_FUNC("cap-hall-right", &m_app_config.cap_hall_right,
		    sizeof(m_app_config.cap_hall_right));
	EXPORT_FUNC("cap-input-a", &m_app_config.cap_input_a, sizeof(m_app_config.cap_input_a));
	EXPORT_FUNC("cap-input-b", &m_app_config.cap_input_b, sizeof(m_app_config.cap_input_b));
	EXPORT_FUNC("cap-light-sensor", &m_app_config.cap_light_sensor,
		    sizeof(m_app_config.cap_light_sensor));
	EXPORT_FUNC("cap-barometer", &m_app_config.cap_barometer,
		    sizeof(m_app_config.cap_barometer));
	EXPORT_FUNC("cap-pir-detector", &m_app_config.cap_pir_detector,
		    sizeof(m_app_config.cap_pir_detector));
	EXPORT_FUNC("cap-buzzer", &m_app_config.cap_buzzer, sizeof(m_app_config.cap_buzzer));
	EXPORT_FUNC("cap-w1-sensors", &m_app_config.cap_w1_sensors,
		    sizeof(m_app_config.cap_w1_sensors));
	EXPORT_FUNC("cap-accelerometer", &m_app_config.cap_accelerometer,
		    sizeof(m_app_config.cap_accelerometer));
	EXPORT_FUNC("alarm-0", m_app_config.alarm_0, sizeof(m_app_config.alarm_0));
	EXPORT_FUNC("alarm-1", m_app_config.alarm_1, sizeof(m_app_config.alarm_1));
	EXPORT_FUNC("alarm-2", m_app_config.alarm_2, sizeof(m_app_config.alarm_2));
	EXPORT_FUNC("alarm-3", m_app_config.alarm_3, sizeof(m_app_config.alarm_3));
	EXPORT_FUNC("alarm-4", m_app_config.alarm_4, sizeof(m_app_config.alarm_4));
	EXPORT_FUNC("alarm-5", m_app_config.alarm_5, sizeof(m_app_config.alarm_5));
	EXPORT_FUNC("alarm-6", m_app_config.alarm_6, sizeof(m_app_config.alarm_6));
	EXPORT_FUNC("alarm-7", m_app_config.alarm_7, sizeof(m_app_config.alarm_7));
	EXPORT_FUNC("alarm-8", m_app_config.alarm_8, sizeof(m_app_config.alarm_8));
	EXPORT_FUNC("alarm-9", m_app_config.alarm_9, sizeof(m_app_config.alarm_9));
	EXPORT_FUNC("alarm-10", m_app_config.alarm_10, sizeof(m_app_config.alarm_10));
	EXPORT_FUNC("alarm-11", m_app_config.alarm_11, sizeof(m_app_config.alarm_11));
	EXPORT_FUNC("alarm-12", m_app_config.alarm_12, sizeof(m_app_config.alarm_12));
	EXPORT_FUNC("alarm-13", m_app_config.alarm_13, sizeof(m_app_config.alarm_13));
	EXPORT_FUNC("alarm-14", m_app_config.alarm_14, sizeof(m_app_config.alarm_14));
	EXPORT_FUNC("alarm-15", m_app_config.alarm_15, sizeof(m_app_config.alarm_15));
	EXPORT_FUNC("alarm-buzzer-mode", &m_app_config.alarm_buzzer_mode,
		    sizeof(m_app_config.alarm_buzzer_mode));
	EXPORT_FUNC("accel-motion-sensitivity", &m_app_config.accel_motion_sensitivity,
		    sizeof(m_app_config.accel_motion_sensitivity));
	EXPORT_FUNC("sensor1-rom", m_app_config.sensor1_rom, sizeof(m_app_config.sensor1_rom));
	EXPORT_FUNC("sensor2-rom", m_app_config.sensor2_rom, sizeof(m_app_config.sensor2_rom));
	EXPORT_FUNC("sensor3-rom", m_app_config.sensor3_rom, sizeof(m_app_config.sensor3_rom));
	EXPORT_FUNC("sensor4-rom", m_app_config.sensor4_rom, sizeof(m_app_config.sensor4_rom));
	EXPORT_FUNC("hall-left-counter", &m_app_config.hall_left_counter,
		    sizeof(m_app_config.hall_left_counter));
	EXPORT_FUNC("hall-right-counter", &m_app_config.hall_right_counter,
		    sizeof(m_app_config.hall_right_counter));
	EXPORT_FUNC("input-a-counter", &m_app_config.input_a_counter,
		    sizeof(m_app_config.input_a_counter));
	EXPORT_FUNC("input-b-counter", &m_app_config.input_b_counter,
		    sizeof(m_app_config.input_b_counter));
	EXPORT_FUNC("p2p-frequency", &m_app_config.p2p_frequency,
		    sizeof(m_app_config.p2p_frequency));
	EXPORT_FUNC("p2p-spreading-factor", &m_app_config.p2p_spreading_factor,
		    sizeof(m_app_config.p2p_spreading_factor));
	EXPORT_FUNC("p2p-tx-power", &m_app_config.p2p_tx_power, sizeof(m_app_config.p2p_tx_power));
	/* Export config-version LAST: settings_save is per-key atomic, so writing
	 * the schema marker after every value means a brownout mid-save leaves an
	 * old version with a partial new payload rather than a new version flagging
	 * data as fully migrated. Paired with the migration restore in h_commit. */
	EXPORT_FUNC("config-version", &m_app_config.config_version,
		    sizeof(m_app_config.config_version));

#undef EXPORT_FUNC

	return 0;
}

#if defined(CONFIG_SHELL)

static const char m_msg_invalid_args[] = "invalid number of arguments";
static const char m_msg_invalid_range[] = "invalid argument range";
static const char m_msg_invalid_value[] = "invalid argument value";
static const char m_msg_cmd_success[] = "command succeeded";

typedef void (*print_func_t)(const struct shell *shell);

/* Largest shell-settable byte field is 16 B (the LoRaWAN keys); the guard keeps
 * the fixed scratch safe should a longer field ever be added. */
#define CMD_BYTES_MAX 32

static void print_bytes(const struct shell *shell, const char *key, const uint8_t *value,
			size_t size)
{
	char buf[2 * CMD_BYTES_MAX + 1];

	if (size > CMD_BYTES_MAX) {
		return;
	}

	int ret = bin2hex(value, size, buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " %s %s", key, buf);
}

static int cmd_bytes(const struct shell *shell, size_t argc, char **argv, uint8_t *value,
		     size_t size, bool write_once, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (size > CMD_BYTES_MAX || strlen(argv[1]) != 2 * size) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[CMD_BYTES_MAX];

	int ret = hex2bin(argv[1], strlen(argv[1]), tmp, size);
	if (ret != (int)size) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (write_once) {
		/* write-once (#170): refuse to overwrite a value that is already set. The
		 * all-zero state is the "unset" sentinel; once any byte is non-zero the
		 * field is locked (commission once, then immutable). */
		for (size_t i = 0; i < size; i++) {
			if (value[i] != 0) {
				shell_error(shell, "%s already set (immutable)", argv[0]);
				return -EACCES;
			}
		}
	}

	memcpy(value, tmp, size);

	return 0;
}

static int cmd_bool(const struct shell *shell, size_t argc, char **argv, bool *param,
		    print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "true")) {
		*param = true;
	} else if (!strcmp(argv[1], "false")) {
		*param = false;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_int(const struct shell *shell, size_t argc, char **argv, int *param, int min,
		   int max, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	long value = strtol(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < min || value > max) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	*param = (int)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static void print_secret_key(const struct shell *shell)
{
	print_bytes(shell, "secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
}

static void print_serial_number(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " serial-number %010u", m_app_config.serial_number);
}

static void print_nonce_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " nonce-counter %u", m_app_config.nonce_counter);
}

static void print_claim_token(const struct shell *shell)
{
	print_bytes(shell, "claim-token", m_app_config.claim_token,
		    sizeof(m_app_config.claim_token));
}

static void print_vendor_token(const struct shell *shell)
{
	print_bytes(shell, "vendor-token", m_app_config.vendor_token,
		    sizeof(m_app_config.vendor_token));
}

static void print_calibration(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " calibration %s",
		    m_app_config.calibration ? "true" : "false");
}

static void print_interval_sample(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-sample %d", m_app_config.interval_sample);
}

static void print_interval_report(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-report %d", m_app_config.interval_report);
}

static void print_history_enable(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " history-enable %s",
		    m_app_config.history_enable ? "true" : "false");
}

static void print_history_sensors(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " history-sensors %u", m_app_config.history_sensors);
}

static void print_battery_level(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " battery-level %d", m_app_config.battery_level);
}

static void print_vendor_reset_allow(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " vendor-reset-allow %s",
		    m_app_config.vendor_reset_allow ? "true" : "false");
}

static void print_alarm_limit(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-limit %d", m_app_config.alarm_limit);
}

static void print_lrw_region(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_region) {
	case APP_CONFIG_LRW_REGION_EU868:
		str = "eu868";
		break;
	case APP_CONFIG_LRW_REGION_US915:
		str = "us915";
		break;
	case APP_CONFIG_LRW_REGION_AU915:
		str = "au915";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-region %s", str);
}

static void print_radio_mode(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.radio_mode) {
	case APP_CONFIG_RADIO_MODE_OFF:
		str = "off";
		break;
	case APP_CONFIG_RADIO_MODE_LORAWAN:
		str = "lorawan";
		break;
	case APP_CONFIG_RADIO_MODE_P2P:
		str = "p2p";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " radio-mode %s", str);
}

static void print_lrw_sub_band(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-sub-band %d", m_app_config.lrw_sub_band);
}

static void print_lrw_network(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_network) {
	case APP_CONFIG_LRW_NETWORK_PUBLIC:
		str = "public";
		break;
	case APP_CONFIG_LRW_NETWORK_PRIVATE:
		str = "private";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-network %s", str);
}

static void print_lrw_adr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-adr %s", m_app_config.lrw_adr ? "true" : "false");
}

static void print_lrw_activation(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_activation) {
	case APP_CONFIG_LRW_ACTIVATION_OTAA:
		str = "otaa";
		break;
	case APP_CONFIG_LRW_ACTIVATION_ABP:
		str = "abp";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-activation %s", str);
}

static void print_lrw_deveui(const struct shell *shell)
{
	print_bytes(shell, "lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
}

static void print_lrw_joineui(const struct shell *shell)
{
	print_bytes(shell, "lrw-joineui", m_app_config.lrw_joineui,
		    sizeof(m_app_config.lrw_joineui));
}

static void print_lrw_nwkkey(const struct shell *shell)
{
	print_bytes(shell, "lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
}

static void print_lrw_appkey(const struct shell *shell)
{
	print_bytes(shell, "lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
}

static void print_lrw_devaddr(const struct shell *shell)
{
	print_bytes(shell, "lrw-devaddr", m_app_config.lrw_devaddr,
		    sizeof(m_app_config.lrw_devaddr));
}

static void print_lrw_nwkskey(const struct shell *shell)
{
	print_bytes(shell, "lrw-nwkskey", m_app_config.lrw_nwkskey,
		    sizeof(m_app_config.lrw_nwkskey));
}

static void print_lrw_appskey(const struct shell *shell)
{
	print_bytes(shell, "lrw-appskey", m_app_config.lrw_appskey,
		    sizeof(m_app_config.lrw_appskey));
}

static void print_lrw_link_check_interval(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-link-check-interval %d",
		    m_app_config.lrw_link_check_interval);
}

static void print_lrw_link_check_fail_rejoin(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-link-check-fail-rejoin %d",
		    m_app_config.lrw_link_check_fail_rejoin);
}

static void print_cap_hall_left(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-left %s",
		    m_app_config.cap_hall_left ? "true" : "false");
}

static void print_cap_hall_right(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-right %s",
		    m_app_config.cap_hall_right ? "true" : "false");
}

static void print_cap_input_a(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-a %s",
		    m_app_config.cap_input_a ? "true" : "false");
}

static void print_cap_input_b(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-b %s",
		    m_app_config.cap_input_b ? "true" : "false");
}

static void print_cap_light_sensor(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-light-sensor %s",
		    m_app_config.cap_light_sensor ? "true" : "false");
}

static void print_cap_barometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-barometer %s",
		    m_app_config.cap_barometer ? "true" : "false");
}

static void print_cap_pir_detector(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-pir-detector %s",
		    m_app_config.cap_pir_detector ? "true" : "false");
}

static void print_cap_buzzer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-buzzer %s",
		    m_app_config.cap_buzzer ? "true" : "false");
}

static void print_cap_w1_sensors(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-w1-sensors %s",
		    m_app_config.cap_w1_sensors ? "true" : "false");
}

static void print_cap_accelerometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-accelerometer %s",
		    m_app_config.cap_accelerometer ? "true" : "false");
}

static void print_alarm_buzzer_mode(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.alarm_buzzer_mode) {
	case APP_CONFIG_ALARM_BUZZER_MODE_OFF:
		str = "off";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_ONCE:
		str = "once";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_SLOW:
		str = "slow";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_NORMAL:
		str = "normal";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_FAST:
		str = "fast";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_CONTINUOUS:
		str = "continuous";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_RESERVED_6:
		str = "reserved6";
		break;
	case APP_CONFIG_ALARM_BUZZER_MODE_RESERVED_7:
		str = "reserved7";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " alarm-buzzer-mode %s", str);
}

static void print_accel_motion_sensitivity(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.accel_motion_sensitivity) {
	case APP_CONFIG_MOTION_SENSITIVITY_OFF:
		str = "off";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_LOW:
		str = "low";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_MEDIUM:
		str = "medium";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_HIGH:
		str = "high";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " accel-motion-sensitivity %s", str);
}

static void print_sensor1_rom(const struct shell *shell)
{
	print_bytes(shell, "sensor1-rom", m_app_config.sensor1_rom,
		    sizeof(m_app_config.sensor1_rom));
}

static void print_sensor2_rom(const struct shell *shell)
{
	print_bytes(shell, "sensor2-rom", m_app_config.sensor2_rom,
		    sizeof(m_app_config.sensor2_rom));
}

static void print_sensor3_rom(const struct shell *shell)
{
	print_bytes(shell, "sensor3-rom", m_app_config.sensor3_rom,
		    sizeof(m_app_config.sensor3_rom));
}

static void print_sensor4_rom(const struct shell *shell)
{
	print_bytes(shell, "sensor4-rom", m_app_config.sensor4_rom,
		    sizeof(m_app_config.sensor4_rom));
}

static void print_hall_left_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-left-counter %s",
		    m_app_config.hall_left_counter ? "true" : "false");
}

static void print_hall_right_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-right-counter %s",
		    m_app_config.hall_right_counter ? "true" : "false");
}

static void print_input_a_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-a-counter %s",
		    m_app_config.input_a_counter ? "true" : "false");
}

static void print_input_b_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-b-counter %s",
		    m_app_config.input_b_counter ? "true" : "false");
}

static void print_p2p_frequency(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " p2p-frequency %d", m_app_config.p2p_frequency);
}

static void print_p2p_spreading_factor(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " p2p-spreading-factor %d",
		    m_app_config.p2p_spreading_factor);
}

static void print_p2p_tx_power(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " p2p-tx-power %d", m_app_config.p2p_tx_power);
}

static int cmd_show(const struct shell *shell, size_t argc, char **argv)
{
	print_secret_key(shell);
	print_serial_number(shell);
	print_nonce_counter(shell);
	print_claim_token(shell);
	print_vendor_token(shell);
	print_calibration(shell);
	print_interval_sample(shell);
	print_interval_report(shell);
	print_history_enable(shell);
	print_history_sensors(shell);
	print_battery_level(shell);
	print_vendor_reset_allow(shell);
	print_alarm_limit(shell);
	print_lrw_region(shell);
	print_radio_mode(shell);
	print_lrw_sub_band(shell);
	print_lrw_network(shell);
	print_lrw_adr(shell);
	print_lrw_activation(shell);
	print_lrw_deveui(shell);
	print_lrw_joineui(shell);
	print_lrw_nwkkey(shell);
	print_lrw_appkey(shell);
	print_lrw_devaddr(shell);
	print_lrw_nwkskey(shell);
	print_lrw_appskey(shell);
	print_lrw_link_check_interval(shell);
	print_lrw_link_check_fail_rejoin(shell);
	print_cap_hall_left(shell);
	print_cap_hall_right(shell);
	print_cap_input_a(shell);
	print_cap_input_b(shell);
	print_cap_light_sensor(shell);
	print_cap_barometer(shell);
	print_cap_pir_detector(shell);
	print_cap_buzzer(shell);
	print_cap_w1_sensors(shell);
	print_cap_accelerometer(shell);
	print_alarm_buzzer_mode(shell);
	print_accel_motion_sensitivity(shell);
	print_sensor1_rom(shell);
	print_sensor2_rom(shell);
	print_sensor3_rom(shell);
	print_sensor4_rom(shell);
	print_hall_left_counter(shell);
	print_hall_right_counter(shell);
	print_input_a_counter(shell);
	print_input_b_counter(shell);
	print_p2p_frequency(shell);
	print_p2p_spreading_factor(shell);
	print_p2p_tx_power(shell);

	return 0;
}

static int cmd_secret_key(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.secret_key,
			 sizeof(m_app_config.secret_key), false, print_secret_key);
}

static int cmd_serial_number(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_serial_number(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	size_t len = strlen(argv[1]);

	if (len != 10) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	for (size_t i = 0; i < len; i++) {
		if (!isdigit((int)argv[1][i])) {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
	}

	errno = 0;
	unsigned long value = strtoul(argv[1], NULL, 10);

	if (errno == ERANGE || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	m_app_config.serial_number = (uint32_t)value;

	return 0;
}

static int cmd_nonce_counter(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_nonce_counter(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (argv[1][0] == '-') {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	char *endptr;

	errno = 0;
	unsigned long value = strtoul(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* errno==ERANGE catches strtoul saturating an out-of-range input to
	 * ULONG_MAX on 32-bit (e.g. a giant nonce-counter), which would otherwise
	 * slip past the max check when max is itself UINT32_MAX. */
	if (errno == ERANGE || value < 0 || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.nonce_counter = (uint32_t)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_claim_token(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.claim_token,
			 sizeof(m_app_config.claim_token), true, print_claim_token);
}

static int cmd_vendor_token(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.vendor_token,
			 sizeof(m_app_config.vendor_token), true, print_vendor_token);
}

static int cmd_calibration(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.calibration, print_calibration);
}

static int cmd_interval_sample(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_interval_sample(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	int a = strtol(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (a != 0 && (a < 5 || a > 3600)) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.interval_sample = a;

	return 0;
}

static int cmd_interval_report(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.interval_report, 60, 86400,
		       print_interval_report);
}

static int cmd_history_enable(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.history_enable, print_history_enable);
}

static int cmd_history_sensors(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_history_sensors(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (argv[1][0] == '-') {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	char *endptr;

	errno = 0;
	unsigned long value = strtoul(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* errno==ERANGE catches strtoul saturating an out-of-range input to
	 * ULONG_MAX on 32-bit (e.g. a giant nonce-counter), which would otherwise
	 * slip past the max check when max is itself UINT32_MAX. */
	if (errno == ERANGE || value < 0 || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.history_sensors = (uint32_t)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_battery_level(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.battery_level, 1000, 3600,
		       print_battery_level);
}

static int cmd_vendor_reset_allow(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.vendor_reset_allow,
			print_vendor_reset_allow);
}

static int cmd_alarm_limit(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.alarm_limit, 0, 3600, print_alarm_limit);
}

static int cmd_lrw_region(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_region(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: eu868, us915, au915");
		return 0;
	}

	if (!strcmp(argv[1], "eu868")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_EU868;
	} else if (!strcmp(argv[1], "us915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_US915;
	} else if (!strcmp(argv[1], "au915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_AU915;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: eu868, us915, au915");
		return -EINVAL;
	}

	return 0;
}

static int cmd_radio_mode(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_radio_mode(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: off, lorawan, p2p");
		return 0;
	}

	if (!strcmp(argv[1], "off")) {
		m_app_config.radio_mode = APP_CONFIG_RADIO_MODE_OFF;
	} else if (!strcmp(argv[1], "lorawan")) {
		m_app_config.radio_mode = APP_CONFIG_RADIO_MODE_LORAWAN;
	} else if (!strcmp(argv[1], "p2p")) {
		m_app_config.radio_mode = APP_CONFIG_RADIO_MODE_P2P;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: off, lorawan, p2p");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_sub_band(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.lrw_sub_band, 0, 8, print_lrw_sub_band);
}

static int cmd_lrw_network(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_network(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: public, private");
		return 0;
	}

	if (!strcmp(argv[1], "public")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PUBLIC;
	} else if (!strcmp(argv[1], "private")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PRIVATE;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: public, private");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_adr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.lrw_adr, print_lrw_adr);
}

static int cmd_lrw_activation(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_activation(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: otaa, abp");
		return 0;
	}

	if (!strcmp(argv[1], "otaa")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_OTAA;
	} else if (!strcmp(argv[1], "abp")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_ABP;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: otaa, abp");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_deveui(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_deveui,
			 sizeof(m_app_config.lrw_deveui), false, print_lrw_deveui);
}

static int cmd_lrw_joineui(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_joineui,
			 sizeof(m_app_config.lrw_joineui), false, print_lrw_joineui);
}

static int cmd_lrw_nwkkey(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_nwkkey,
			 sizeof(m_app_config.lrw_nwkkey), false, print_lrw_nwkkey);
}

static int cmd_lrw_appkey(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_appkey,
			 sizeof(m_app_config.lrw_appkey), false, print_lrw_appkey);
}

static int cmd_lrw_devaddr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_devaddr,
			 sizeof(m_app_config.lrw_devaddr), false, print_lrw_devaddr);
}

static int cmd_lrw_nwkskey(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_nwkskey,
			 sizeof(m_app_config.lrw_nwkskey), false, print_lrw_nwkskey);
}

static int cmd_lrw_appskey(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.lrw_appskey,
			 sizeof(m_app_config.lrw_appskey), false, print_lrw_appskey);
}

static int cmd_lrw_link_check_interval(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.lrw_link_check_interval, 0, 255,
		       print_lrw_link_check_interval);
}

static int cmd_lrw_link_check_fail_rejoin(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.lrw_link_check_fail_rejoin, 1, 255,
		       print_lrw_link_check_fail_rejoin);
}

static int cmd_cap_hall_left(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_left, print_cap_hall_left);
}

static int cmd_cap_hall_right(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_right, print_cap_hall_right);
}

static int cmd_cap_input_a(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_a, print_cap_input_a);
}

static int cmd_cap_input_b(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_b, print_cap_input_b);
}

static int cmd_cap_light_sensor(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_light_sensor, print_cap_light_sensor);
}

static int cmd_cap_barometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_barometer, print_cap_barometer);
}

static int cmd_cap_pir_detector(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_pir_detector, print_cap_pir_detector);
}

static int cmd_cap_buzzer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_buzzer, print_cap_buzzer);
}

static int cmd_cap_w1_sensors(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_w1_sensors, print_cap_w1_sensors);
}

static int cmd_cap_accelerometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_accelerometer,
			print_cap_accelerometer);
}

static int cmd_alarm_buzzer_mode(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_alarm_buzzer_mode(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: off, once, slow, normal, fast, continuous, "
				   "reserved6, reserved7");
		return 0;
	}

	if (!strcmp(argv[1], "off")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_OFF;
	} else if (!strcmp(argv[1], "once")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_ONCE;
	} else if (!strcmp(argv[1], "slow")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_SLOW;
	} else if (!strcmp(argv[1], "normal")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_NORMAL;
	} else if (!strcmp(argv[1], "fast")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_FAST;
	} else if (!strcmp(argv[1], "continuous")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_CONTINUOUS;
	} else if (!strcmp(argv[1], "reserved6")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_RESERVED_6;
	} else if (!strcmp(argv[1], "reserved7")) {
		m_app_config.alarm_buzzer_mode = APP_CONFIG_ALARM_BUZZER_MODE_RESERVED_7;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: off, once, slow, normal, fast, continuous, "
				   "reserved6, reserved7");
		return -EINVAL;
	}

	return 0;
}

static int cmd_accel_motion_sensitivity(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_accel_motion_sensitivity(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: off, low, medium, high");
		return 0;
	}

	if (!strcmp(argv[1], "off")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF;
	} else if (!strcmp(argv[1], "low")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_LOW;
	} else if (!strcmp(argv[1], "medium")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_MEDIUM;
	} else if (!strcmp(argv[1], "high")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_HIGH;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: off, low, medium, high");
		return -EINVAL;
	}

	return 0;
}

static int cmd_sensor1_rom(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.sensor1_rom,
			 sizeof(m_app_config.sensor1_rom), false, print_sensor1_rom);
}

static int cmd_sensor2_rom(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.sensor2_rom,
			 sizeof(m_app_config.sensor2_rom), false, print_sensor2_rom);
}

static int cmd_sensor3_rom(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.sensor3_rom,
			 sizeof(m_app_config.sensor3_rom), false, print_sensor3_rom);
}

static int cmd_sensor4_rom(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bytes(shell, argc, argv, m_app_config.sensor4_rom,
			 sizeof(m_app_config.sensor4_rom), false, print_sensor4_rom);
}

static int cmd_hall_left_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_left_counter,
			print_hall_left_counter);
}

static int cmd_hall_right_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_right_counter,
			print_hall_right_counter);
}

static int cmd_input_a_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_a_counter, print_input_a_counter);
}

static int cmd_input_b_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_b_counter, print_input_b_counter);
}

static int cmd_p2p_frequency(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.p2p_frequency, 863000000, 870000000,
		       print_p2p_frequency);
}

static int cmd_p2p_spreading_factor(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.p2p_spreading_factor, 6, 12,
		       print_p2p_spreading_factor);
}

static int cmd_p2p_tx_power(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.p2p_tx_power, 2, 22, print_p2p_tx_power);
}

static int print_help(const struct shell *shell, size_t argc, char **argv)
{
	if (argc > 1) {
		shell_error(shell, "command not found: %s", argv[1]);
		shell_help(shell);
		return -EINVAL;
	}

	shell_help(shell);

	return 0;
}

/* clang-format off */

SHELL_STATIC_SUBCMD_SET_CREATE(
	sub_config,

	SHELL_CMD_ARG(show, NULL,
	              "Show all configuration.",
	              cmd_show, 1, 0),

	SHELL_CMD_ARG(secret-key, NULL,
	              "Get/Set device secret key (32 hexadecimal digits).",
	              cmd_secret_key, 1, 1),

	SHELL_CMD_ARG(serial-number, NULL,
	              "Get/Set device serial number (10 decimal digits).",
	              cmd_serial_number, 1, 1),

	SHELL_CMD_ARG(nonce-counter, NULL,
	              "Get/Set nonce counter (unsigned integer).",
	              cmd_nonce_counter, 1, 1),

	SHELL_CMD_ARG(claim-token, NULL,
	              "Get/Set device claim token (32 hexadecimal digits); write-once at commissioning.",
	              cmd_claim_token, 1, 1),

	SHELL_CMD_ARG(vendor-token, NULL,
	              "Get/Set vendor token (32 hexadecimal digits); write-once at commissioning.",
	              cmd_vendor_token, 1, 1),

	SHELL_CMD_ARG(calibration, NULL,
	              "Get/Set calibration mode (true/false).",
	              cmd_calibration, 1, 1),

	SHELL_CMD_ARG(interval-sample, NULL,
	              "Get/Set sample interval (range 5 to 3600 seconds; 0 = precede report).",
	              cmd_interval_sample, 1, 1),

	SHELL_CMD_ARG(interval-report, NULL,
	              "Get/Set report interval (range 60 to 86400 seconds).",
	              cmd_interval_report, 1, 1),

	SHELL_CMD_ARG(history-enable, NULL,
	              "Get/Set sensor history store-and-forward (true/false).",
	              cmd_history_enable, 1, 1),

	SHELL_CMD_ARG(history-sensors, NULL,
	              "Get/Set history sensor selection bitmask (literal, bit i = enum app_history_sensor i; 0 = no channels). Default 0x0003 = temperature + humidity.",
	              cmd_history_sensors, 1, 1),

	SHELL_CMD_ARG(battery-level, NULL,
	              "Get/Set low-battery alarm threshold in mV (default 2400; Li cells discharge non-linearly). Alarm on fPort 3 (source=battery) when supply drops below this.",
	              cmd_battery_level, 1, 1),

	SHELL_CMD_ARG(vendor-reset-allow, NULL,
	              "Get/Set whether vendor_reset is accepted (true/false); over the air, settable only over the vendor NFC channel.",
	              cmd_vendor_reset_allow, 1, 1),

	SHELL_CMD_ARG(alarm-limit, NULL,
	              "Get/Set minimum interval between alarm uplinks in seconds (0 = disabled).",
	              cmd_alarm_limit, 1, 1),

	SHELL_CMD_ARG(lrw-region, NULL,
	              "Get/Set LoRaWAN region (eu868/us915/au915).",
	              cmd_lrw_region, 1, 1),

	SHELL_CMD_ARG(radio-mode, NULL,
	              "Get/Set radio mode (off/lorawan/p2p). off = radio-silent, sensor/history still run.",
	              cmd_radio_mode, 1, 1),

	SHELL_CMD_ARG(lrw-sub-band, NULL,
	              "Get/Set US915/AU915 sub-band (1-8, 0 = all channels). Default 2 matches TTN/Helium/ChirpStack.",
	              cmd_lrw_sub_band, 1, 1),

	SHELL_CMD_ARG(lrw-network, NULL,
	              "Get/Set LoRaWAN network (public/private).",
	              cmd_lrw_network, 1, 1),

	SHELL_CMD_ARG(lrw-adr, NULL,
	              "Get/Set LoRaWAN ADR (true/false).",
	              cmd_lrw_adr, 1, 1),

	SHELL_CMD_ARG(lrw-activation, NULL,
	              "Get/Set LoRaWAN activation (otaa/abp).",
	              cmd_lrw_activation, 1, 1),

	SHELL_CMD_ARG(lrw-deveui, NULL,
	              "Get/Set LoRaWAN DevEUI (16 hex digits).",
	              cmd_lrw_deveui, 1, 1),

	SHELL_CMD_ARG(lrw-joineui, NULL,
	              "Get/Set LoRaWAN JoinEUI (16 hex digits).",
	              cmd_lrw_joineui, 1, 1),

	SHELL_CMD_ARG(lrw-nwkkey, NULL,
	              "Get/Set LoRaWAN NwkKey (32 hex digits).",
	              cmd_lrw_nwkkey, 1, 1),

	SHELL_CMD_ARG(lrw-appkey, NULL,
	              "Get/Set LoRaWAN AppKey (32 hex digits).",
	              cmd_lrw_appkey, 1, 1),

	SHELL_CMD_ARG(lrw-devaddr, NULL,
	              "Get/Set LoRaWAN DevAddr (8 hex digits).",
	              cmd_lrw_devaddr, 1, 1),

	SHELL_CMD_ARG(lrw-nwkskey, NULL,
	              "Get/Set LoRaWAN NwkSKey (32 hexadecimal digits).",
	              cmd_lrw_nwkskey, 1, 1),

	SHELL_CMD_ARG(lrw-appskey, NULL,
	              "Get/Set LoRaWAN AppSKey (32 hexadecimal digits).",
	              cmd_lrw_appskey, 1, 1),

	SHELL_CMD_ARG(lrw-link-check-interval, NULL,
	              "Get/Set link-check cadence: request a LinkCheckReq every N-th uplink (0 = disabled).",
	              cmd_lrw_link_check_interval, 1, 1),

	SHELL_CMD_ARG(lrw-link-check-fail-rejoin, NULL,
	              "Get/Set link-check failures (while degraded) before an OTAA rejoin is attempted.",
	              cmd_lrw_link_check_fail_rejoin, 1, 1),

	SHELL_CMD_ARG(cap-hall-left, NULL,
	              "Get/Set hall left capability (true/false).",
	              cmd_cap_hall_left, 1, 1),

	SHELL_CMD_ARG(cap-hall-right, NULL,
	              "Get/Set hall right capability (true/false).",
	              cmd_cap_hall_right, 1, 1),

	SHELL_CMD_ARG(cap-input-a, NULL,
	              "Get/Set input A capability (true/false).",
	              cmd_cap_input_a, 1, 1),

	SHELL_CMD_ARG(cap-input-b, NULL,
	              "Get/Set input B capability (true/false).",
	              cmd_cap_input_b, 1, 1),

	SHELL_CMD_ARG(cap-light-sensor, NULL,
	              "Get/Set light sensor capability (true/false).",
	              cmd_cap_light_sensor, 1, 1),

	SHELL_CMD_ARG(cap-barometer, NULL,
	              "Get/Set barometer capability (true/false).",
	              cmd_cap_barometer, 1, 1),

	SHELL_CMD_ARG(cap-pir-detector, NULL,
	              "Get/Set PIR detector capability (true/false).",
	              cmd_cap_pir_detector, 1, 1),

	SHELL_CMD_ARG(cap-buzzer, NULL,
	              "Get/Set buzzer capability (true/false). Shares GPIO pins with the PIR detector — mutually exclusive with cap_pir_detector (PIR wins if both are enabled).",
	              cmd_cap_buzzer, 1, 1),

	SHELL_CMD_ARG(cap-w1-sensors, NULL,
	              "Get/Set 1-Wire sensor bus capability — enables the bus + auto-detects attached sensors (true/false).",
	              cmd_cap_w1_sensors, 1, 1),

	SHELL_CMD_ARG(cap-accelerometer, NULL,
	              "Get/Set accelerometer capability — orientation, motion and free-fall (true/false).",
	              cmd_cap_accelerometer, 1, 1),

	SHELL_CMD_ARG(alarm-buzzer-mode, NULL,
	              "Get/Set buzzer alarm indication mode: every non-off mode beeps immediately on each newly activated alarm, then repeats while any alarm stays active — once = no repeat, slow/normal/fast = every 120/30/10 s, continuous = back-to-back (reserved6/7 behave like normal). Requires cap_buzzer.",
	              cmd_alarm_buzzer_mode, 1, 1),

	SHELL_CMD_ARG(accel-motion-sensitivity, NULL,
	              "Get/Set accelerometer motion detection sensitivity (off/low/medium/high).",
	              cmd_accel_motion_sensitivity, 1, 1),

	SHELL_CMD_ARG(sensor1-rom, NULL,
	              "Get/Set 1-Wire slot 1 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor1_rom, 1, 1),

	SHELL_CMD_ARG(sensor2-rom, NULL,
	              "Get/Set 1-Wire slot 2 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor2_rom, 1, 1),

	SHELL_CMD_ARG(sensor3-rom, NULL,
	              "Get/Set 1-Wire slot 3 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor3_rom, 1, 1),

	SHELL_CMD_ARG(sensor4-rom, NULL,
	              "Get/Set 1-Wire slot 4 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor4_rom, 1, 1),

	SHELL_CMD_ARG(hall-left-counter, NULL,
	              "Get/Set hall left switch counter enabled (true/false).",
	              cmd_hall_left_counter, 1, 1),

	SHELL_CMD_ARG(hall-right-counter, NULL,
	              "Get/Set hall right switch counter enabled (true/false).",
	              cmd_hall_right_counter, 1, 1),

	SHELL_CMD_ARG(input-a-counter, NULL,
	              "Get/Set input A counter enabled (true/false).",
	              cmd_input_a_counter, 1, 1),

	SHELL_CMD_ARG(input-b-counter, NULL,
	              "Get/Set input B counter enabled (true/false).",
	              cmd_input_b_counter, 1, 1),

	SHELL_CMD_ARG(p2p-frequency, NULL,
	              "Get/Set P2P carrier frequency in Hz (EU868 band).",
	              cmd_p2p_frequency, 1, 1),

	SHELL_CMD_ARG(p2p-spreading-factor, NULL,
	              "Get/Set P2P spreading factor (6-12; higher = longer range, lower rate).",
	              cmd_p2p_spreading_factor, 1, 1),

	SHELL_CMD_ARG(p2p-tx-power, NULL,
	              "Get/Set P2P TX power in dBm.",
	              cmd_p2p_tx_power, 1, 1),

	SHELL_SUBCMD_SET_END
);

/* clang-format on */

SHELL_CMD_REGISTER(config, &sub_config, "Configuration commands.", print_help);

#endif /* defined(CONFIG_SHELL) */

struct app_config *app_config(void)
{
	return &m_app_config;
}

/* Reset every parameter to its compiled-in default EXCEPT the fields tagged
 * `persistent: [device_reset, ...]` in the YAML (factory identity + full
 * LoRaWAN), then persist. Backs the `device_reset` command (renamed from
 * today's `factory_reset`, #299) so the device keeps its LoRaWAN session; the
 * shell `settings erase` still does a full NVS wipe. Returns 0 or a negative
 * errno. The caller reboots so every module re-reads the restored config. */
int app_config_device_reset(void)
{
	int ret;

	/* #340 M27: brackets the whole read-modify-write against concurrent
	 * mutation from another transport (mirrors SetParam's own lock scope,
	 * which likewise snapshots-then-mutates under the same lock and saves
	 * outside of it). */
	app_config_lock();

	struct app_config preserved = m_app_config;

	m_app_config = m_app_config_defaults;
	memcpy(m_app_config.secret_key, preserved.secret_key, sizeof(m_app_config.secret_key));
	m_app_config.serial_number = preserved.serial_number;
	m_app_config.nonce_counter = preserved.nonce_counter;
	memcpy(m_app_config.claim_token, preserved.claim_token, sizeof(m_app_config.claim_token));
	memcpy(m_app_config.vendor_token, preserved.vendor_token,
	       sizeof(m_app_config.vendor_token));
	m_app_config.vendor_reset_allow = preserved.vendor_reset_allow;
	m_app_config.lrw_region = preserved.lrw_region;
	m_app_config.radio_mode = preserved.radio_mode;
	m_app_config.lrw_sub_band = preserved.lrw_sub_band;
	m_app_config.lrw_network = preserved.lrw_network;
	m_app_config.lrw_adr = preserved.lrw_adr;
	m_app_config.lrw_activation = preserved.lrw_activation;
	memcpy(m_app_config.lrw_deveui, preserved.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	memcpy(m_app_config.lrw_joineui, preserved.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	memcpy(m_app_config.lrw_nwkkey, preserved.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	memcpy(m_app_config.lrw_appkey, preserved.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	memcpy(m_app_config.lrw_devaddr, preserved.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	memcpy(m_app_config.lrw_nwkskey, preserved.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	memcpy(m_app_config.lrw_appskey, preserved.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	m_app_config.p2p_frequency = preserved.p2p_frequency;
	m_app_config.p2p_spreading_factor = preserved.p2p_spreading_factor;
	m_app_config.p2p_tx_power = preserved.p2p_tx_power;

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));

	app_config_unlock();

	ret = settings_save_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		return ret;
	}

	LOG_INF("device_reset: config restored to defaults");
	return 0;
}

/* Narrower than device_reset (#299): also drops the LoRaWAN session/keys,
 * keeping only identity (serial_number/vendor_token/secret_key/DevEUI/
 * JoinEUI/claim_token) — the device must re-join after this. Returns 0 or a
 * negative errno; the caller reboots. */
int app_config_factory_reset(void)
{
	int ret;

	/* #340 M27: brackets the whole read-modify-write against concurrent
	 * mutation from another transport (mirrors SetParam's own lock scope,
	 * which likewise snapshots-then-mutates under the same lock and saves
	 * outside of it). */
	app_config_lock();

	struct app_config preserved = m_app_config;

	m_app_config = m_app_config_defaults;
	memcpy(m_app_config.secret_key, preserved.secret_key, sizeof(m_app_config.secret_key));
	m_app_config.serial_number = preserved.serial_number;
	m_app_config.nonce_counter = preserved.nonce_counter;
	memcpy(m_app_config.claim_token, preserved.claim_token, sizeof(m_app_config.claim_token));
	memcpy(m_app_config.vendor_token, preserved.vendor_token,
	       sizeof(m_app_config.vendor_token));
	m_app_config.vendor_reset_allow = preserved.vendor_reset_allow;
	memcpy(m_app_config.lrw_deveui, preserved.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	memcpy(m_app_config.lrw_joineui, preserved.lrw_joineui, sizeof(m_app_config.lrw_joineui));

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));

	app_config_unlock();

	ret = settings_save_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		return ret;
	}

	LOG_INF("factory_reset: config restored to defaults");
	return 0;
}

/* Narrowest tier (#299): keeps only serial_number + vendor_token. The caller
 * (app_settings_vendor_reset) erases the storage+history flash areas first,
 * then calls this to re-provision the snapshot before saving + rebooting.
 * Returns 0 or a negative errno. */
int app_config_vendor_reset(void)
{
	int ret;

	/* #340 M27: brackets the whole read-modify-write against concurrent
	 * mutation from another transport (mirrors SetParam's own lock scope,
	 * which likewise snapshots-then-mutates under the same lock and saves
	 * outside of it). */
	app_config_lock();

	struct app_config preserved = m_app_config;

	m_app_config = m_app_config_defaults;
	m_app_config.serial_number = preserved.serial_number;
	m_app_config.nonce_counter = preserved.nonce_counter;
	memcpy(m_app_config.vendor_token, preserved.vendor_token,
	       sizeof(m_app_config.vendor_token));

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));

	app_config_unlock();

	ret = settings_save_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		return ret;
	}

	LOG_INF("vendor_reset: config restored to defaults");
	return 0;
}

static int app_config_init(void)
{
	int ret;

	ret = settings_subsys_init();
	if (ret) {
		LOG_ERR("Call `settings_subsys_init` failed: %d", ret);
		return ret;
	}

	static struct settings_handler sh = {
		.name = SETTINGS_PFX,
		.h_set = h_set,
		.h_commit = h_commit,
		.h_export = h_export,
	};

	ret = settings_register(&sh);
	if (ret) {
		LOG_ERR("Call `settings_register` failed: %d", ret);
		return ret;
	}

	ret = settings_load_subtree(SETTINGS_PFX);
	if (ret) {
		/* H-4: do not silently swallow a load failure. SYS_INIT discards our
		 * return value, so returning here just lets the device boot on defaults
		 * (identity + provisioning gone) with no signal. Flag it instead so the
		 * app can show a distinct state; the in-RAM defaults keep the device
		 * running rather than dead. */
		LOG_ERR("Call `settings_load_subtree` failed: %d — booting on defaults", ret);
		m_app_config_load_failed = true;
	}

	if (m_app_config_migrated) {
		m_app_config_migrated = false;

		/* Persist the migrated config right away so the stored schema
		 * version is bumped and the migration does not repeat on every
		 * boot. A failure here is not fatal: the in-RAM config is valid
		 * and the migration simply runs again next boot. */
		ret = settings_save_subtree(SETTINGS_PFX);
		if (ret) {
			LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		} else {
			LOG_INF("Config migrated to version %u and persisted", APP_CONFIG_VERSION);
		}
	}

	return 0;
}

SYS_INIT(app_config_init, APPLICATION, 0);
