/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by configen from app_config.yml — do not edit by hand.
 * Emits one rodata cfg_field_desc[] per proto submessage group; the generic
 * cfg_apply/cfg_fill/cfg_slot_empty interpreter in app_config_table.c walks it
 * (table-driven config, #262). Public entry points (unchanged signatures):
 *  - apply_<group>(): SetParam / NFC ingest (validates, records first FAULT)
 *  - fill_<group>():  GetConfig dump (only requested, dumpable fields)
 */

#include "app_config_ingest.h"
#include "app_config.h"
#include "app_config_table.h"

/* Zephyr includes */
#include <zephyr/sys/util.h>

/* Standard includes */
#include <stddef.h>
#include <stdint.h>

static const struct cfg_field_desc lorawan_desc[] = {
	{
		.tag = 1,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_region),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_region),
		.src_off = offsetof(AppConfigMessage_Lorawan, region),
		.dst_off = offsetof(struct app_config, lrw_region),
		.min = 0,
		.max = 2,
	},
	{
		.tag = 2,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_sub_band),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_sub_band),
		.src_off = offsetof(AppConfigMessage_Lorawan, sub_band),
		.dst_off = offsetof(struct app_config, lrw_sub_band),
		.min = 0,
		.max = 8,
	},
	{
		.tag = 3,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_network),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_network),
		.src_off = offsetof(AppConfigMessage_Lorawan, network),
		.dst_off = offsetof(struct app_config, lrw_network),
		.min = 0,
		.max = 1,
	},
	{
		.tag = 4,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->lrw_adr),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_adr),
		.src_off = offsetof(AppConfigMessage_Lorawan, adr),
		.dst_off = offsetof(struct app_config, lrw_adr),
	},
	{
		.tag = 5,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_activation),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_activation),
		.src_off = offsetof(AppConfigMessage_Lorawan, activation),
		.dst_off = offsetof(struct app_config, lrw_activation),
		.min = 0,
		.max = 1,
	},
	{
		.tag = 6,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_deveui),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_deveui),
		.src_off = offsetof(AppConfigMessage_Lorawan, deveui),
		.dst_off = offsetof(struct app_config, lrw_deveui),
	},
	{
		.tag = 7,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_joineui),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_joineui),
		.src_off = offsetof(AppConfigMessage_Lorawan, joineui),
		.dst_off = offsetof(struct app_config, lrw_joineui),
	},
	{
		.tag = 8,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_nwkkey),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_nwkkey),
		.src_off = offsetof(AppConfigMessage_Lorawan, nwkkey),
		.dst_off = offsetof(struct app_config, lrw_nwkkey),
	},
	{
		.tag = 9,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_appkey),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_appkey),
		.src_off = offsetof(AppConfigMessage_Lorawan, appkey),
		.dst_off = offsetof(struct app_config, lrw_appkey),
	},
	{
		.tag = 10,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_devaddr),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_devaddr),
		.src_off = offsetof(AppConfigMessage_Lorawan, devaddr),
		.dst_off = offsetof(struct app_config, lrw_devaddr),
	},
	{
		.tag = 11,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_nwkskey),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_nwkskey),
		.src_off = offsetof(AppConfigMessage_Lorawan, nwkskey),
		.dst_off = offsetof(struct app_config, lrw_nwkskey),
	},
	{
		.tag = 12,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->lrw_appskey),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_appskey),
		.src_off = offsetof(AppConfigMessage_Lorawan, appskey),
		.dst_off = offsetof(struct app_config, lrw_appskey),
	},
	{
		.tag = 13,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_link_check_interval),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_link_check_interval),
		.src_off = offsetof(AppConfigMessage_Lorawan, link_check_interval),
		.dst_off = offsetof(struct app_config, lrw_link_check_interval),
		.min = 0,
		.max = 255,
	},
	{
		.tag = 14,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->lrw_link_check_fail_rejoin),
		.flags = CFG_F_DUMP | CFG_F_NO_WR_LRW,
		.has_off = offsetof(AppConfigMessage_Lorawan, has_link_check_fail_rejoin),
		.src_off = offsetof(AppConfigMessage_Lorawan, link_check_fail_rejoin),
		.dst_off = offsetof(struct app_config, lrw_link_check_fail_rejoin),
		.min = 1,
		.max = 255,
	},
};

int app_config_apply_lorawan(enum app_cmd_transport tp, const AppConfigMessage_Lorawan *src,
			     uint32_t *fault_field)
{
	return cfg_apply(lorawan_desc, ARRAY_SIZE(lorawan_desc), tp, src, app_config(),
			 fault_field);
}

void app_config_fill_lorawan(AppConfigMessage_Lorawan *dst, const uint32_t *ids, size_t n)
{
	cfg_fill(lorawan_desc, ARRAY_SIZE(lorawan_desc), dst, app_config(), ids, n);
}

static const struct cfg_field_desc application_desc[] = {
	{
		.tag = 1,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->calibration),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Application, has_calibration),
		.src_off = offsetof(AppConfigMessage_Application, calibration),
		.dst_off = offsetof(struct app_config, calibration),
	},
	{
		.tag = 2,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->interval_sample),
		.flags = CFG_F_DUMP | CFG_F_ZERO_OK,
		.has_off = offsetof(AppConfigMessage_Application, has_interval_sample),
		.src_off = offsetof(AppConfigMessage_Application, interval_sample),
		.dst_off = offsetof(struct app_config, interval_sample),
		.min = 5,
		.max = 3600,
	},
	{
		.tag = 3,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->interval_report),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Application, has_interval_report),
		.src_off = offsetof(AppConfigMessage_Application, interval_report),
		.dst_off = offsetof(struct app_config, interval_report),
		.min = 60,
		.max = 86400,
	},
	{
		.tag = 4,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->history_enable),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Application, has_history_enable),
		.src_off = offsetof(AppConfigMessage_Application, history_enable),
		.dst_off = offsetof(struct app_config, history_enable),
	},
	{
		.tag = 5,
		.kind = CFG_KIND_PLAIN,
		.size = sizeof(((struct app_config *)0)->history_sensors),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Application, has_history_sensors),
		.src_off = offsetof(AppConfigMessage_Application, history_sensors),
		.dst_off = offsetof(struct app_config, history_sensors),
	},
	{
		.tag = 6,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->battery_level),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Application, has_battery_level),
		.src_off = offsetof(AppConfigMessage_Application, battery_level),
		.dst_off = offsetof(struct app_config, battery_level),
		.min = 1000,
		.max = 3600,
	},
};

int app_config_apply_application(enum app_cmd_transport tp, const AppConfigMessage_Application *src,
				 uint32_t *fault_field)
{
	return cfg_apply(application_desc, ARRAY_SIZE(application_desc), tp, src, app_config(),
			 fault_field);
}

void app_config_fill_application(AppConfigMessage_Application *dst, const uint32_t *ids, size_t n)
{
	cfg_fill(application_desc, ARRAY_SIZE(application_desc), dst, app_config(), ids, n);
}

static const struct cfg_field_desc sensors_desc[] = {
	{
		.tag = 1,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_hall_left),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_hall_left),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_hall_left),
		.dst_off = offsetof(struct app_config, cap_hall_left),
	},
	{
		.tag = 2,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_hall_right),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_hall_right),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_hall_right),
		.dst_off = offsetof(struct app_config, cap_hall_right),
	},
	{
		.tag = 3,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_input_a),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_input_a),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_input_a),
		.dst_off = offsetof(struct app_config, cap_input_a),
	},
	{
		.tag = 4,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_input_b),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_input_b),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_input_b),
		.dst_off = offsetof(struct app_config, cap_input_b),
	},
	{
		.tag = 5,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_light_sensor),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_light_sensor),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_light_sensor),
		.dst_off = offsetof(struct app_config, cap_light_sensor),
	},
	{
		.tag = 6,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_barometer),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_barometer),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_barometer),
		.dst_off = offsetof(struct app_config, cap_barometer),
	},
	{
		.tag = 7,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_pir_detector),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_pir_detector),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_pir_detector),
		.dst_off = offsetof(struct app_config, cap_pir_detector),
	},
	{
		.tag = 8,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_w1_sensors),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_w1_sensors),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_w1_sensors),
		.dst_off = offsetof(struct app_config, cap_w1_sensors),
	},
	{
		.tag = 9,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->cap_accelerometer),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_cap_accelerometer),
		.src_off = offsetof(AppConfigMessage_Sensors, cap_accelerometer),
		.dst_off = offsetof(struct app_config, cap_accelerometer),
	},
	{
		.tag = 10,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->accel_motion_sensitivity),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_accel_motion_sensitivity),
		.src_off = offsetof(AppConfigMessage_Sensors, accel_motion_sensitivity),
		.dst_off = offsetof(struct app_config, accel_motion_sensitivity),
		.min = 0,
		.max = 3,
	},
	{
		.tag = 11,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->sensor1_rom),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_sensor1_rom),
		.src_off = offsetof(AppConfigMessage_Sensors, sensor1_rom),
		.dst_off = offsetof(struct app_config, sensor1_rom),
	},
	{
		.tag = 12,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->sensor2_rom),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_sensor2_rom),
		.src_off = offsetof(AppConfigMessage_Sensors, sensor2_rom),
		.dst_off = offsetof(struct app_config, sensor2_rom),
	},
	{
		.tag = 13,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->sensor3_rom),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_sensor3_rom),
		.src_off = offsetof(AppConfigMessage_Sensors, sensor3_rom),
		.dst_off = offsetof(struct app_config, sensor3_rom),
	},
	{
		.tag = 14,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->sensor4_rom),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_sensor4_rom),
		.src_off = offsetof(AppConfigMessage_Sensors, sensor4_rom),
		.dst_off = offsetof(struct app_config, sensor4_rom),
	},
	{
		.tag = 15,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->hall_left_counter),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_hall_left_counter),
		.src_off = offsetof(AppConfigMessage_Sensors, hall_left_counter),
		.dst_off = offsetof(struct app_config, hall_left_counter),
	},
	{
		.tag = 16,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->hall_right_counter),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_hall_right_counter),
		.src_off = offsetof(AppConfigMessage_Sensors, hall_right_counter),
		.dst_off = offsetof(struct app_config, hall_right_counter),
	},
	{
		.tag = 17,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->input_a_counter),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_input_a_counter),
		.src_off = offsetof(AppConfigMessage_Sensors, input_a_counter),
		.dst_off = offsetof(struct app_config, input_a_counter),
	},
	{
		.tag = 18,
		.kind = CFG_KIND_BOOL,
		.size = sizeof(((struct app_config *)0)->input_b_counter),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Sensors, has_input_b_counter),
		.src_off = offsetof(AppConfigMessage_Sensors, input_b_counter),
		.dst_off = offsetof(struct app_config, input_b_counter),
	},
};

int app_config_apply_sensors(enum app_cmd_transport tp, const AppConfigMessage_Sensors *src,
			     uint32_t *fault_field)
{
	return cfg_apply(sensors_desc, ARRAY_SIZE(sensors_desc), tp, src, app_config(),
			 fault_field);
}

void app_config_fill_sensors(AppConfigMessage_Sensors *dst, const uint32_t *ids, size_t n)
{
	cfg_fill(sensors_desc, ARRAY_SIZE(sensors_desc), dst, app_config(), ids, n);
}

static const struct cfg_field_desc alarms_desc[] = {
	{
		.tag = 1,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->alarm_limit),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_limit),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_limit),
		.dst_off = offsetof(struct app_config, alarm_limit),
		.min = 0,
		.max = 3600,
	},
	{
		.tag = 2,
		.kind = CFG_KIND_RANGED,
		.size = sizeof(((struct app_config *)0)->alarm_notif_time),
		.flags = CFG_F_DUMP,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_notif_time),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_notif_time),
		.dst_off = offsetof(struct app_config, alarm_notif_time),
		.min = 1,
		.max = 60,
	},
	{
		.tag = 3,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_0),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_0),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_0),
		.dst_off = offsetof(struct app_config, alarm_0),
	},
	{
		.tag = 4,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_1),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_1),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_1),
		.dst_off = offsetof(struct app_config, alarm_1),
	},
	{
		.tag = 5,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_2),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_2),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_2),
		.dst_off = offsetof(struct app_config, alarm_2),
	},
	{
		.tag = 6,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_3),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_3),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_3),
		.dst_off = offsetof(struct app_config, alarm_3),
	},
	{
		.tag = 7,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_4),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_4),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_4),
		.dst_off = offsetof(struct app_config, alarm_4),
	},
	{
		.tag = 8,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_5),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_5),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_5),
		.dst_off = offsetof(struct app_config, alarm_5),
	},
	{
		.tag = 9,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_6),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_6),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_6),
		.dst_off = offsetof(struct app_config, alarm_6),
	},
	{
		.tag = 10,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_7),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_7),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_7),
		.dst_off = offsetof(struct app_config, alarm_7),
	},
	{
		.tag = 11,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_8),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_8),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_8),
		.dst_off = offsetof(struct app_config, alarm_8),
	},
	{
		.tag = 12,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_9),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_9),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_9),
		.dst_off = offsetof(struct app_config, alarm_9),
	},
	{
		.tag = 13,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_10),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_10),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_10),
		.dst_off = offsetof(struct app_config, alarm_10),
	},
	{
		.tag = 14,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_11),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_11),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_11),
		.dst_off = offsetof(struct app_config, alarm_11),
	},
	{
		.tag = 15,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_12),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_12),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_12),
		.dst_off = offsetof(struct app_config, alarm_12),
	},
	{
		.tag = 16,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_13),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_13),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_13),
		.dst_off = offsetof(struct app_config, alarm_13),
	},
	{
		.tag = 17,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_14),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_14),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_14),
		.dst_off = offsetof(struct app_config, alarm_14),
	},
	{
		.tag = 18,
		.kind = CFG_KIND_BYTES,
		.size = sizeof(((struct app_config *)0)->alarm_15),
		.flags = CFG_F_DUMP | CFG_F_OMIT_ZERO,
		.has_off = offsetof(AppConfigMessage_Alarms, has_alarm_15),
		.src_off = offsetof(AppConfigMessage_Alarms, alarm_15),
		.dst_off = offsetof(struct app_config, alarm_15),
	},
};

int app_config_apply_alarms(enum app_cmd_transport tp, const AppConfigMessage_Alarms *src,
			    uint32_t *fault_field)
{
	return cfg_apply(alarms_desc, ARRAY_SIZE(alarms_desc), tp, src, app_config(), fault_field);
}

void app_config_fill_alarms(AppConfigMessage_Alarms *dst, const uint32_t *ids, size_t n)
{
	cfg_fill(alarms_desc, ARRAY_SIZE(alarms_desc), dst, app_config(), ids, n);
}

bool app_config_alarms_slot_empty(uint32_t tag)
{
	return cfg_slot_empty(alarms_desc, ARRAY_SIZE(alarms_desc), app_config(), tag);
}
