/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* GENERATED by `west sensorgen` from app_w1_slots.yaml — do not edit (#430). */

#include "app_sensor_types.h"
#include "app_config.h"

/* Zephyr includes */
#include <zephyr/sys/util.h>

/* Standard includes */
#include <stddef.h>
#include <string.h>

static const struct app_sensor_channel m_ch_motherboard[] =
	{
		[APP_SENSOR_CH_MOTHERBOARD_TEMPERATURE] =
			{
				.name = "temperature",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_SINT32,
				.hist_enc = APP_SENSOR_HIST_I16,
				.cap_off = APP_SENSOR_NO_CAP,
				.wire_scale = 100.0f,
				.hist_scale = 100.0f,
				.range_min = -40.0f,
				.range_max = 125.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_HUMIDITY] =
			{
				.name = "humidity",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U8,
				.cap_off = APP_SENSOR_NO_CAP,
				.wire_scale = 2.0f,
				.hist_scale = 2.0f,
				.range_min = 0.0f,
				.range_max = 100.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_PRESSURE] =
			{
				.name = "pressure",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U16,
				.cap_off = offsetof(struct app_config, cap_barometer),
				.wire_scale = 10.0f,
				.hist_scale = 10.0f,
				.range_min = 200.0f,
				.range_max = 1100.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_ILLUMINANCE] =
			{
				.name = "illuminance",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U16,
				.cap_off = offsetof(struct app_config, cap_light_sensor),
				.wire_scale = 1.0f,
				.hist_scale = 0.5f,
				.range_min = 0.0f,
				.range_max = 83865.6f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_TEMPERATURE_BARO] =
			{
				.name = "temperature-baro",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_SINT32,
				.hist_enc = APP_SENSOR_HIST_I16,
				.cap_off = offsetof(struct app_config, cap_barometer),
				.wire_scale = 100.0f,
				.hist_scale = 100.0f,
				.range_min = -40.0f,
				.range_max = 85.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_HALL_LEFT_STATE] =
			{
				.name = "hall-left-state",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = 0,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_hall_left),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_HALL_LEFT_COUNT] =
			{
				.name = "hall-left-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_hall_left),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_HALL_RIGHT_STATE] =
			{
				.name = "hall-right-state",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = 0,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_hall_right),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_HALL_RIGHT_COUNT] =
			{
				.name = "hall-right-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_hall_right),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_A_STATE] =
			{
				.name = "input-a-state",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = 0,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_input_a),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_A_COUNT] =
			{
				.name = "input-a-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_input_a),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_A_VOLTAGE] =
			{
				.name = "input-a-voltage",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U16,
				.cap_off = APP_SENSOR_NO_CAP, /* cap_analog_a: pending (not in
								 app_config yet) */
				.wire_scale = 1000.0f,
				.hist_scale = 1000.0f,
				.range_min = 0.0f,
				.range_max = 30.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_B_STATE] =
			{
				.name = "input-b-state",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = 0,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_input_b),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_B_COUNT] =
			{
				.name = "input-b-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_input_b),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_INPUT_B_VOLTAGE] =
			{
				.name = "input-b-voltage",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U16,
				.cap_off = APP_SENSOR_NO_CAP, /* cap_analog_b: pending (not in
								 app_config yet) */
				.wire_scale = 1000.0f,
				.hist_scale = 1000.0f,
				.range_min = 0.0f,
				.range_max = 30.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_PIR_MOTION] =
			{
				.name = "pir-motion",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = APP_SENSOR_F_MOMENTARY,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_pir_detector),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_PIR_COUNT] =
			{
				.name = "pir-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_pir_detector),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_ACCEL_MOTION] =
			{
				.name = "accel-motion",
				.kind = APP_SENSOR_KIND_STATE,
				.flags = APP_SENSOR_F_MOMENTARY,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_NONE,
				.cap_off = offsetof(struct app_config, cap_accelerometer),
				.wire_scale = 1.0f,
				.hist_scale = 0.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_ACCEL_COUNT] =
			{
				.name = "accel-count",
				.kind = APP_SENSOR_KIND_RATE,
				.flags = APP_SENSOR_F_COUNTER,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U32,
				.cap_off = offsetof(struct app_config, cap_accelerometer),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_ACCEL_ORIENTATION] =
			{
				.name = "accel-orientation",
				.kind = APP_SENSOR_KIND_NONE,
				.flags = 0,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U8,
				.cap_off = offsetof(struct app_config, cap_accelerometer),
				.wire_scale = 1.0f,
				.hist_scale = 1.0f,
				.range_min = 0.0f,
				.range_max = 0.0f,
			},
		[APP_SENSOR_CH_MOTHERBOARD_BATTERY_VOLTAGE] =
			{
				.name = "battery-voltage",
				.kind = APP_SENSOR_KIND_THRESHOLD,
				.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_WATCHDOG_ONLY |
					 APP_SENSOR_F_RANGE,
				.wire_type = APP_SENSOR_WIRE_UINT32,
				.hist_enc = APP_SENSOR_HIST_U16,
				.cap_off = APP_SENSOR_NO_CAP,
				.wire_scale = 1000.0f,
				.hist_scale = 1000.0f,
				.range_min = 0.0f,
				.range_max = 4.0f,
			},
};

static const struct app_sensor_channel m_ch_dallas[] = {
	[APP_SENSOR_CH_DALLAS_TEMPERATURE] =
		{
			.name = "temperature",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -55.0f,
			.range_max = 125.0f,
		},
};

static const struct app_sensor_channel m_ch_machine_probe[] = {
	[APP_SENSOR_CH_MACHINE_PROBE_TEMPERATURE] =
		{
			.name = "temperature",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_LIVENESS | APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -40.0f,
			.range_max = 125.0f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_HUMIDITY] =
		{
			.name = "humidity",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_UINT32,
			.hist_enc = APP_SENSOR_HIST_U8,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 2.0f,
			.hist_scale = 2.0f,
			.range_min = 0.0f,
			.range_max = 100.0f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_TEMPERATURE_AUX] =
		{
			.name = "temperature-aux",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -40.0f,
			.range_max = 125.0f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_ILLUMINANCE] =
		{
			.name = "illuminance",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_UINT32,
			.hist_enc = APP_SENSOR_HIST_U16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 1.0f,
			.hist_scale = 0.5f,
			.range_min = 0.0f,
			.range_max = 83865.6f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_MAGNETIC_FIELD] =
		{
			.name = "magnetic-field",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 1000.0f,
			.hist_scale = 100.0f,
			.range_min = -204.7f,
			.range_max = 204.7f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_TILT] =
		{
			.name = "tilt",
			.kind = APP_SENSOR_KIND_STATE,
			.flags = 0,
			.wire_type = APP_SENSOR_WIRE_UINT32,
			.hist_enc = APP_SENSOR_HIST_U8,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 1.0f,
			.hist_scale = 1.0f,
			.range_min = 0.0f,
			.range_max = 0.0f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_ACCEL_X] =
		{
			.name = "accel-x",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -156.9f,
			.range_max = 156.9f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_ACCEL_Y] =
		{
			.name = "accel-y",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -156.9f,
			.range_max = 156.9f,
		},
	[APP_SENSOR_CH_MACHINE_PROBE_ACCEL_Z] =
		{
			.name = "accel-z",
			.kind = APP_SENSOR_KIND_THRESHOLD,
			.flags = APP_SENSOR_F_RANGE,
			.wire_type = APP_SENSOR_WIRE_SINT32,
			.hist_enc = APP_SENSOR_HIST_I16,
			.cap_off = APP_SENSOR_NO_CAP,
			.wire_scale = 100.0f,
			.hist_scale = 100.0f,
			.range_min = -156.9f,
			.range_max = 156.9f,
		},
};

BUILD_ASSERT(ARRAY_SIZE(m_ch_motherboard) <= APP_SENSOR_MB_CH_MAX, "motherboard channel limit");
BUILD_ASSERT(ARRAY_SIZE(m_ch_dallas) <= APP_SENSOR_W1_CH_MAX, "dallas channel limit");
BUILD_ASSERT(ARRAY_SIZE(m_ch_machine_probe) <= APP_SENSOR_W1_CH_MAX, "machine-probe channel limit");
/* cap_off must not collide with the APP_SENSOR_NO_CAP marker. */
BUILD_ASSERT(sizeof(struct app_config) < APP_SENSOR_NO_CAP,
	     "struct app_config too large for cap_off");

static const struct app_sensor_type m_types[] = {
	{
		.name = "motherboard",
		.channels = m_ch_motherboard,
		.id = APP_SENSOR_TYPE_MOTHERBOARD,
		.w1_family = 0x00,
		.channel_count = ARRAY_SIZE(m_ch_motherboard),
	},
	{
		.name = "dallas",
		.channels = m_ch_dallas,
		.id = APP_SENSOR_TYPE_DALLAS,
		.w1_family = 0x28,
		.channel_count = ARRAY_SIZE(m_ch_dallas),
	},
	{
		.name = "machine-probe",
		.channels = m_ch_machine_probe,
		.id = APP_SENSOR_TYPE_MACHINE_PROBE,
		.w1_family = 0x19,
		.channel_count = ARRAY_SIZE(m_ch_machine_probe),
	},
};

const struct app_sensor_type *app_sensor_type_get(uint8_t id)
{
	for (size_t i = 0; i < ARRAY_SIZE(m_types); i++) {
		if (m_types[i].id == id) {
			return &m_types[i];
		}
	}
	return NULL;
}

const struct app_sensor_type *app_sensor_type_by_family(uint8_t family)
{
	for (size_t i = 0; i < ARRAY_SIZE(m_types); i++) {
		if (family != 0 && m_types[i].w1_family == family) {
			return &m_types[i];
		}
	}
	return NULL;
}

const struct app_sensor_type *app_sensor_type_by_name(const char *name)
{
	for (size_t i = 0; i < ARRAY_SIZE(m_types); i++) {
		if (strcmp(m_types[i].name, name) == 0) {
			return &m_types[i];
		}
	}
	return NULL;
}

const struct app_sensor_channel *app_sensor_channel_get(uint8_t id, uint8_t ch)
{
	const struct app_sensor_type *t = app_sensor_type_get(id);

	if (t == NULL || ch >= t->channel_count) {
		return NULL;
	}
	return &t->channels[ch];
}

int app_sensor_channel_by_name(uint8_t id, const char *name)
{
	const struct app_sensor_type *t = app_sensor_type_get(id);

	if (t == NULL) {
		return -1;
	}
	for (uint8_t ch = 0; ch < t->channel_count; ch++) {
		if (strcmp(t->channels[ch].name, name) == 0) {
			return ch;
		}
	}
	return -1;
}
