/*
 * Copyright (c) 2026 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by configen from app_config.yml — do not edit by hand.
 * Maps each proto config submessage to the flat app_config struct:
 *  - apply_<group>(): SetParam / NFC ingest (validates, records first FAULT)
 *  - fill_<group>():  GetConfig dump (only requested, non-secret fields)
 */

#include "app_config_ingest.h"
#include "app_config.h"
#include "app_log.h"

/* Zephyr includes */
#include <zephyr/logging/log.h>
#include <zephyr/sys/util.h>

/* Standard includes */
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config_ingest, LOG_LEVEL_DBG);

/* Record the first offending proto field tag and mark the result invalid. The
 * apply still processes the remaining fields (best effort) so NFC ingest keeps
 * its "skip invalid, apply the rest" behaviour; SetParam inspects fault_field. */
#define FAULT(tag)                                                                                 \
	do {                                                                                       \
		if (fault_field && *fault_field == 0) {                                            \
			*fault_field = (tag);                                                      \
		}                                                                                  \
		ret = -EINVAL;                                                                     \
	} while (0)

static bool parse_hex_string(const char *hex_str, uint8_t *buf, size_t buf_len)
{
	if (!hex_str || !buf) {
		return false;
	}

	size_t str_len = strlen(hex_str);
	if (str_len != 2 * buf_len) {
		LOG_ERR("Invalid hex string length: expected %zu, got %zu", 2 * buf_len, str_len);
		return false;
	}

	/* Decode into a temp buffer first: hex2bin writes byte-by-byte into the
	 * destination and bails (returning 0) on the first invalid nibble, so
	 * decoding straight into the config field would leave a half-overwritten
	 * value that a later save would persist (#91). Commit only on full success. */
	uint8_t tmp[16];
	if (buf_len > sizeof(tmp)) {
		LOG_ERR("hex buffer too large: %zu", buf_len);
		return false;
	}

	if (hex2bin(hex_str, str_len, tmp, buf_len) != buf_len) {
		LOG_ERR_CALL_FAILED("hex2bin");
		return false;
	}

	memcpy(buf, tmp, buf_len);
	return true;
}

static bool requested(const uint32_t *ids, size_t n, uint32_t tag)
{
	for (size_t i = 0; i < n; i++) {
		if (ids[i] == tag) {
			return true;
		}
	}
	return false;
}

int app_config_apply_lorawan(const AppConfigMessage_Lorawan *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_region) {
		if ((int)src->region >= 0 && (int)src->region <= 2) {
			config->lrw_region = (enum app_config_lrw_region)src->region;
		} else {
			FAULT(1);
		}
	}
	if (src->has_network) {
		if ((int)src->network >= 0 && (int)src->network <= 1) {
			config->lrw_network = (enum app_config_lrw_network)src->network;
		} else {
			FAULT(2);
		}
	}
	if (src->has_adr) {
		config->lrw_adr = src->adr;
	}
	if (src->has_activation) {
		if ((int)src->activation >= 0 && (int)src->activation <= 1) {
			config->lrw_activation = (enum app_config_lrw_activation)src->activation;
		} else {
			FAULT(4);
		}
	}
	if (src->has_deveui &&
	    !parse_hex_string(src->deveui, config->lrw_deveui, sizeof(config->lrw_deveui))) {
		FAULT(5);
	}
	if (src->has_joineui &&
	    !parse_hex_string(src->joineui, config->lrw_joineui, sizeof(config->lrw_joineui))) {
		FAULT(6);
	}
	if (src->has_nwkkey &&
	    !parse_hex_string(src->nwkkey, config->lrw_nwkkey, sizeof(config->lrw_nwkkey))) {
		FAULT(7);
	}
	if (src->has_appkey &&
	    !parse_hex_string(src->appkey, config->lrw_appkey, sizeof(config->lrw_appkey))) {
		FAULT(8);
	}
	if (src->has_devaddr &&
	    !parse_hex_string(src->devaddr, config->lrw_devaddr, sizeof(config->lrw_devaddr))) {
		FAULT(9);
	}
	if (src->has_nwkskey &&
	    !parse_hex_string(src->nwkskey, config->lrw_nwkskey, sizeof(config->lrw_nwkskey))) {
		FAULT(10);
	}
	if (src->has_appskey &&
	    !parse_hex_string(src->appskey, config->lrw_appskey, sizeof(config->lrw_appskey))) {
		FAULT(11);
	}
	if (src->has_sub_band) {
		int val = src->sub_band;

		if ((val >= 0 && val <= 8)) {
			config->lrw_sub_band = val;
		} else {
			FAULT(12);
		}
	}
	if (src->has_link_check_interval) {
		int val = src->link_check_interval;

		if ((val >= 0 && val <= 255)) {
			config->lrw_link_check_interval = val;
		} else {
			FAULT(13);
		}
	}
	if (src->has_link_check_fail_rejoin) {
		int val = src->link_check_fail_rejoin;

		if ((val >= 1 && val <= 255)) {
			config->lrw_link_check_fail_rejoin = val;
		} else {
			FAULT(14);
		}
	}
	return ret;
}

void app_config_fill_lorawan(AppConfigMessage_Lorawan *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_region = true;
		dst->region = (AppConfigMessage_Lorawan_Region)c->lrw_region;
	}
	if (requested(ids, n, 2)) {
		dst->has_network = true;
		dst->network = (AppConfigMessage_Lorawan_Network)c->lrw_network;
	}
	if (requested(ids, n, 3)) {
		dst->has_adr = true;
		dst->adr = c->lrw_adr;
	}
	if (requested(ids, n, 4)) {
		dst->has_activation = true;
		dst->activation = (AppConfigMessage_Lorawan_Activation)c->lrw_activation;
	}
	if (requested(ids, n, 5)) {
		dst->has_deveui = true;
		bin2hex(c->lrw_deveui, sizeof(c->lrw_deveui), dst->deveui, sizeof(dst->deveui));
	}
	if (requested(ids, n, 6)) {
		dst->has_joineui = true;
		bin2hex(c->lrw_joineui, sizeof(c->lrw_joineui), dst->joineui, sizeof(dst->joineui));
	}
	if (requested(ids, n, 9)) {
		dst->has_devaddr = true;
		bin2hex(c->lrw_devaddr, sizeof(c->lrw_devaddr), dst->devaddr, sizeof(dst->devaddr));
	}
	if (requested(ids, n, 12)) {
		dst->has_sub_band = true;
		dst->sub_band = c->lrw_sub_band;
	}
	if (requested(ids, n, 13)) {
		dst->has_link_check_interval = true;
		dst->link_check_interval = c->lrw_link_check_interval;
	}
	if (requested(ids, n, 14)) {
		dst->has_link_check_fail_rejoin = true;
		dst->link_check_fail_rejoin = c->lrw_link_check_fail_rejoin;
	}
}

int app_config_apply_application(const AppConfigMessage_Application *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_calibration) {
		config->calibration = src->calibration;
	}
	if (src->has_interval_sample) {
		int val = src->interval_sample;

		if (val == 0 || (val >= 5 && val <= 3600)) {
			config->interval_sample = val;
		} else {
			FAULT(2);
		}
	}
	if (src->has_interval_report) {
		int val = src->interval_report;

		if ((val >= 60 && val <= 86400)) {
			config->interval_report = val;
		} else {
			FAULT(4);
		}
	}
	if (src->has_history_enable) {
		config->history_enable = src->history_enable;
	}
	if (src->has_history_sensors) {
		config->history_sensors = src->history_sensors;
	}
	return ret;
}

void app_config_fill_application(AppConfigMessage_Application *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 1)) {
		dst->has_calibration = true;
		dst->calibration = c->calibration;
	}
	if (requested(ids, n, 2)) {
		dst->has_interval_sample = true;
		dst->interval_sample = c->interval_sample;
	}
	if (requested(ids, n, 4)) {
		dst->has_interval_report = true;
		dst->interval_report = c->interval_report;
	}
	if (requested(ids, n, 49)) {
		dst->has_history_enable = true;
		dst->history_enable = c->history_enable;
	}
	if (requested(ids, n, 50)) {
		dst->has_history_sensors = true;
		dst->history_sensors = c->history_sensors;
	}
}

int app_config_apply_sensors(const AppConfigMessage_Sensors *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_cap_hall_left) {
		config->cap_hall_left = src->cap_hall_left;
	}
	if (src->has_cap_hall_right) {
		config->cap_hall_right = src->cap_hall_right;
	}
	if (src->has_cap_input_a) {
		config->cap_input_a = src->cap_input_a;
	}
	if (src->has_cap_input_b) {
		config->cap_input_b = src->cap_input_b;
	}
	if (src->has_cap_light_sensor) {
		config->cap_light_sensor = src->cap_light_sensor;
	}
	if (src->has_cap_barometer) {
		config->cap_barometer = src->cap_barometer;
	}
	if (src->has_cap_pir_detector) {
		config->cap_pir_detector = src->cap_pir_detector;
	}
	if (src->has_accel_motion_sensitivity) {
		if ((int)src->accel_motion_sensitivity >= 0 &&
		    (int)src->accel_motion_sensitivity <= 3) {
			config->accel_motion_sensitivity =
				(enum app_config_motion_sensitivity)src->accel_motion_sensitivity;
		} else {
			FAULT(54);
		}
	}
	if (src->has_cap_accelerometer) {
		config->cap_accelerometer = src->cap_accelerometer;
	}
	if (src->has_sensor1_rom &&
	    !parse_hex_string(src->sensor1_rom, config->sensor1_rom, sizeof(config->sensor1_rom))) {
		FAULT(56);
	}
	if (src->has_sensor2_rom &&
	    !parse_hex_string(src->sensor2_rom, config->sensor2_rom, sizeof(config->sensor2_rom))) {
		FAULT(57);
	}
	if (src->has_sensor3_rom &&
	    !parse_hex_string(src->sensor3_rom, config->sensor3_rom, sizeof(config->sensor3_rom))) {
		FAULT(58);
	}
	if (src->has_sensor4_rom &&
	    !parse_hex_string(src->sensor4_rom, config->sensor4_rom, sizeof(config->sensor4_rom))) {
		FAULT(59);
	}
	if (src->has_cap_w1_sensors) {
		config->cap_w1_sensors = src->cap_w1_sensors;
	}
	return ret;
}

void app_config_fill_sensors(AppConfigMessage_Sensors *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 40)) {
		dst->has_cap_hall_left = true;
		dst->cap_hall_left = c->cap_hall_left;
	}
	if (requested(ids, n, 41)) {
		dst->has_cap_hall_right = true;
		dst->cap_hall_right = c->cap_hall_right;
	}
	if (requested(ids, n, 42)) {
		dst->has_cap_input_a = true;
		dst->cap_input_a = c->cap_input_a;
	}
	if (requested(ids, n, 43)) {
		dst->has_cap_input_b = true;
		dst->cap_input_b = c->cap_input_b;
	}
	if (requested(ids, n, 44)) {
		dst->has_cap_light_sensor = true;
		dst->cap_light_sensor = c->cap_light_sensor;
	}
	if (requested(ids, n, 45)) {
		dst->has_cap_barometer = true;
		dst->cap_barometer = c->cap_barometer;
	}
	if (requested(ids, n, 46)) {
		dst->has_cap_pir_detector = true;
		dst->cap_pir_detector = c->cap_pir_detector;
	}
	if (requested(ids, n, 54)) {
		dst->has_accel_motion_sensitivity = true;
		dst->accel_motion_sensitivity =
			(AppConfigMessage_Sensors_MotionSensitivity)c->accel_motion_sensitivity;
	}
	if (requested(ids, n, 55)) {
		dst->has_cap_accelerometer = true;
		dst->cap_accelerometer = c->cap_accelerometer;
	}
	if (requested(ids, n, 56)) {
		dst->has_sensor1_rom = true;
		bin2hex(c->sensor1_rom, sizeof(c->sensor1_rom), dst->sensor1_rom,
			sizeof(dst->sensor1_rom));
	}
	if (requested(ids, n, 57)) {
		dst->has_sensor2_rom = true;
		bin2hex(c->sensor2_rom, sizeof(c->sensor2_rom), dst->sensor2_rom,
			sizeof(dst->sensor2_rom));
	}
	if (requested(ids, n, 58)) {
		dst->has_sensor3_rom = true;
		bin2hex(c->sensor3_rom, sizeof(c->sensor3_rom), dst->sensor3_rom,
			sizeof(dst->sensor3_rom));
	}
	if (requested(ids, n, 59)) {
		dst->has_sensor4_rom = true;
		bin2hex(c->sensor4_rom, sizeof(c->sensor4_rom), dst->sensor4_rom,
			sizeof(dst->sensor4_rom));
	}
	if (requested(ids, n, 60)) {
		dst->has_cap_w1_sensors = true;
		dst->cap_w1_sensors = c->cap_w1_sensors;
	}
}

int app_config_apply_alarms(const AppConfigMessage_Alarms *src, uint32_t *fault_field)
{
	struct app_config *config = app_config();
	int ret = 0;

	if (fault_field) {
		*fault_field = 0;
	}

	if (src->has_hall_left_counter) {
		config->hall_left_counter = src->hall_left_counter;
	}
	if (src->has_hall_right_counter) {
		config->hall_right_counter = src->hall_right_counter;
	}
	if (src->has_input_a_counter) {
		config->input_a_counter = src->input_a_counter;
	}
	if (src->has_input_b_counter) {
		config->input_b_counter = src->input_b_counter;
	}
	if (src->has_alarm_limit) {
		int val = src->alarm_limit;

		if ((val >= 0 && val <= 3600)) {
			config->alarm_limit = val;
		} else {
			FAULT(51);
		}
	}
	if (src->has_alarm_notif_time) {
		int val = src->alarm_notif_time;

		if ((val >= 1 && val <= 60)) {
			config->alarm_notif_time = val;
		} else {
			FAULT(52);
		}
	}
	return ret;
}

void app_config_fill_alarms(AppConfigMessage_Alarms *dst, const uint32_t *ids, size_t n)
{
	const struct app_config *c = app_config();

	if (requested(ids, n, 25)) {
		dst->has_hall_left_counter = true;
		dst->hall_left_counter = c->hall_left_counter;
	}
	if (requested(ids, n, 28)) {
		dst->has_hall_right_counter = true;
		dst->hall_right_counter = c->hall_right_counter;
	}
	if (requested(ids, n, 31)) {
		dst->has_input_a_counter = true;
		dst->input_a_counter = c->input_a_counter;
	}
	if (requested(ids, n, 34)) {
		dst->has_input_b_counter = true;
		dst->input_b_counter = c->input_b_counter;
	}
	if (requested(ids, n, 51)) {
		dst->has_alarm_limit = true;
		dst->alarm_limit = c->alarm_limit;
	}
	if (requested(ids, n, 52)) {
		dst->has_alarm_notif_time = true;
		dst->alarm_notif_time = c->alarm_notif_time;
	}
}

bool app_config_ingest(const AppConfigMessage *message)
{
	if (message->has_factory && message->factory) {
		LOG_INF("Factory reset requested via NFC");
		return true;
	}

	/* NFC keeps best-effort semantics: apply valid fields, ignore invalid. */
	if (message->has_lorawan) {
		app_config_apply_lorawan(&message->lorawan, NULL);
	}
	if (message->has_application) {
		app_config_apply_application(&message->application, NULL);
	}
	if (message->has_sensors) {
		app_config_apply_sensors(&message->sensors, NULL);
	}
	if (message->has_alarms) {
		app_config_apply_alarms(&message->alarms, NULL);
	}
	return false;
}
