/* WARNING: This file is auto-generated by `west configen`. Do not modify manually. */

/*
 * Copyright (c) 2025 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "app_config.h"

/* Zephyr includes */
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/shell/shell.h>

/* Standard includes */
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config, LOG_LEVEL_DBG);

#define SETTINGS_PFX "config"

struct app_config g_app_config;

static const struct app_config m_app_config_defaults = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 0,
	.battery_level = 2400,
	.alarm_limit = 0,
	.alarm_notif_time = 10,
	.lrw_sub_band = 2,
	.lrw_link_check_interval = 5,
	.lrw_link_check_fail_rejoin = 5,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
};

/* Set by h_commit when a schema version migration ran; init persists the
 * migrated config so the stored version is bumped exactly once. */
static bool m_app_config_migrated;

/* Set by init when settings_load fails (corrupt/unreadable NVS): the device then
 * boots on compile-time defaults with its identity + provisioning gone. Queryable
 * so the app can surface a distinct state (LED / GetInfo) instead of silently
 * looking like a blank device (H-4). */
static bool m_app_config_load_failed;

bool app_config_load_failed(void)
{
	return m_app_config_load_failed;
}

static struct app_config m_app_config = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 0,
	.battery_level = 2400,
	.alarm_limit = 0,
	.alarm_notif_time = 10,
	.lrw_sub_band = 2,
	.lrw_link_check_interval = 5,
	.lrw_link_check_fail_rejoin = 5,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
};

/* Flat settings descriptor: maps each NVS key to its offset+size in the config
 * struct. One rodata table drives both load (h_set) and export (h_export),
 * replacing the per-key SETTINGS_SET/EXPORT_FUNC expansions (table-driven config,
 * #262 Phase 2). config-version is the LAST entry so h_export writes it after
 * every value (its schema-marker ordering guarantee, see h_export). */
struct app_config_setting {
	const char *key;
	uint16_t off;
	uint16_t size;
};

#define CFG_SETTING(_key, _member)                                                                 \
	{(_key), offsetof(struct app_config, _member), sizeof(m_app_config._member)}

static const struct app_config_setting m_app_config_settings[] = {
	CFG_SETTING("secret-key", secret_key),
	CFG_SETTING("serial-number", serial_number),
	CFG_SETTING("nonce-counter", nonce_counter),
	CFG_SETTING("claim-token", claim_token),
	CFG_SETTING("calibration", calibration),
	CFG_SETTING("interval-sample", interval_sample),
	CFG_SETTING("interval-report", interval_report),
	CFG_SETTING("history-enable", history_enable),
	CFG_SETTING("history-sensors", history_sensors),
	CFG_SETTING("battery-level", battery_level),
	CFG_SETTING("alarm-limit", alarm_limit),
	CFG_SETTING("alarm-notif-time", alarm_notif_time),
	CFG_SETTING("lrw-region", lrw_region),
	CFG_SETTING("lrw-sub-band", lrw_sub_band),
	CFG_SETTING("lrw-network", lrw_network),
	CFG_SETTING("lrw-adr", lrw_adr),
	CFG_SETTING("lrw-activation", lrw_activation),
	CFG_SETTING("lrw-deveui", lrw_deveui),
	CFG_SETTING("lrw-joineui", lrw_joineui),
	CFG_SETTING("lrw-nwkkey", lrw_nwkkey),
	CFG_SETTING("lrw-appkey", lrw_appkey),
	CFG_SETTING("lrw-devaddr", lrw_devaddr),
	CFG_SETTING("lrw-nwkskey", lrw_nwkskey),
	CFG_SETTING("lrw-appskey", lrw_appskey),
	CFG_SETTING("lrw-link-check-interval", lrw_link_check_interval),
	CFG_SETTING("lrw-link-check-fail-rejoin", lrw_link_check_fail_rejoin),
	CFG_SETTING("cap-hall-left", cap_hall_left),
	CFG_SETTING("cap-hall-right", cap_hall_right),
	CFG_SETTING("cap-input-a", cap_input_a),
	CFG_SETTING("cap-input-b", cap_input_b),
	CFG_SETTING("cap-light-sensor", cap_light_sensor),
	CFG_SETTING("cap-barometer", cap_barometer),
	CFG_SETTING("cap-pir-detector", cap_pir_detector),
	CFG_SETTING("cap-w1-sensors", cap_w1_sensors),
	CFG_SETTING("cap-accelerometer", cap_accelerometer),
	CFG_SETTING("alarm-0", alarm_0),
	CFG_SETTING("alarm-1", alarm_1),
	CFG_SETTING("alarm-2", alarm_2),
	CFG_SETTING("alarm-3", alarm_3),
	CFG_SETTING("alarm-4", alarm_4),
	CFG_SETTING("alarm-5", alarm_5),
	CFG_SETTING("alarm-6", alarm_6),
	CFG_SETTING("alarm-7", alarm_7),
	CFG_SETTING("alarm-8", alarm_8),
	CFG_SETTING("alarm-9", alarm_9),
	CFG_SETTING("alarm-10", alarm_10),
	CFG_SETTING("alarm-11", alarm_11),
	CFG_SETTING("alarm-12", alarm_12),
	CFG_SETTING("alarm-13", alarm_13),
	CFG_SETTING("alarm-14", alarm_14),
	CFG_SETTING("alarm-15", alarm_15),
	CFG_SETTING("accel-motion-sensitivity", accel_motion_sensitivity),
	CFG_SETTING("sensor1-rom", sensor1_rom),
	CFG_SETTING("sensor2-rom", sensor2_rom),
	CFG_SETTING("sensor3-rom", sensor3_rom),
	CFG_SETTING("sensor4-rom", sensor4_rom),
	CFG_SETTING("hall-left-counter", hall_left_counter),
	CFG_SETTING("hall-right-counter", hall_right_counter),
	CFG_SETTING("input-a-counter", input_a_counter),
	CFG_SETTING("input-b-counter", input_b_counter),
	CFG_SETTING("config-version", config_version),
};

static int h_set(const char *key, size_t len, settings_read_cb read_cb, void *cb_arg)
{
	const char *next;

	for (size_t i = 0; i < ARRAY_SIZE(m_app_config_settings); i++) {
		const struct app_config_setting *s = &m_app_config_settings[i];

		if (!settings_name_steq(key, s->key, &next) || next) {
			continue;
		}

		if (len != s->size) {
			return -EINVAL;
		}

		int ret = read_cb(cb_arg, (uint8_t *)&m_app_config + s->off, len);

		if (ret < 0) {
			LOG_ERR("Call `read_cb` failed: %d", ret);
			return ret;
		}

		return 0;
	}

	return -ENOENT;
}

static int h_commit(void)
{
	LOG_DBG("Loaded settings in full");

	/* L-33: migrate only on an UPGRADE (stored < current). Using != also fired on
	 * a downgrade and reset the application parameters to the older firmware's
	 * defaults; a downgrade should keep the stored config as-is (values are clamped
	 * below anyway). */
	if (m_app_config.config_version < APP_CONFIG_VERSION) {
		LOG_WRN("Config version older than firmware (stored=%u, expected=%u), migrating",
			m_app_config.config_version, APP_CONFIG_VERSION);

		/* Reset application parameters to defaults, but carry over factory
		 * identity and network credentials (preserve_on_reset in the
		 * YAML) so a schema bump never un-provisions a field device. */
		struct app_config stored = m_app_config;

		m_app_config = m_app_config_defaults;
		memcpy(m_app_config.secret_key, stored.secret_key, sizeof(m_app_config.secret_key));
		m_app_config.serial_number = stored.serial_number;
		m_app_config.nonce_counter = stored.nonce_counter;
		memcpy(m_app_config.claim_token, stored.claim_token,
		       sizeof(m_app_config.claim_token));
		m_app_config.lrw_region = stored.lrw_region;
		m_app_config.lrw_sub_band = stored.lrw_sub_band;
		m_app_config.lrw_network = stored.lrw_network;
		m_app_config.lrw_adr = stored.lrw_adr;
		m_app_config.lrw_activation = stored.lrw_activation;
		memcpy(m_app_config.lrw_deveui, stored.lrw_deveui, sizeof(m_app_config.lrw_deveui));
		memcpy(m_app_config.lrw_joineui, stored.lrw_joineui,
		       sizeof(m_app_config.lrw_joineui));
		memcpy(m_app_config.lrw_nwkkey, stored.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
		memcpy(m_app_config.lrw_appkey, stored.lrw_appkey, sizeof(m_app_config.lrw_appkey));
		memcpy(m_app_config.lrw_devaddr, stored.lrw_devaddr,
		       sizeof(m_app_config.lrw_devaddr));
		memcpy(m_app_config.lrw_nwkskey, stored.lrw_nwkskey,
		       sizeof(m_app_config.lrw_nwkskey));
		memcpy(m_app_config.lrw_appskey, stored.lrw_appskey,
		       sizeof(m_app_config.lrw_appskey));

		m_app_config_migrated = true;
	}

	/* Clamp loaded values into their configured ranges so a corrupted or forged
	 * NVS record can't leave the device in a broken state (e.g. interval=0 ->
	 * K_SECONDS(0), or an out-of-range enum that no code path expects). */
	if (m_app_config.interval_sample < 5 && m_app_config.interval_sample != 0) {
		m_app_config.interval_sample = 5;
	}
	if (m_app_config.interval_sample > 3600) {
		m_app_config.interval_sample = 3600;
	}
	if (m_app_config.interval_report < 60) {
		m_app_config.interval_report = 60;
	}
	if (m_app_config.interval_report > 86400) {
		m_app_config.interval_report = 86400;
	}
	if (m_app_config.battery_level < 1000) {
		m_app_config.battery_level = 1000;
	}
	if (m_app_config.battery_level > 3600) {
		m_app_config.battery_level = 3600;
	}
	if (m_app_config.alarm_limit < 0) {
		m_app_config.alarm_limit = 0;
	}
	if (m_app_config.alarm_limit > 3600) {
		m_app_config.alarm_limit = 3600;
	}
	if (m_app_config.alarm_notif_time < 1) {
		m_app_config.alarm_notif_time = 1;
	}
	if (m_app_config.alarm_notif_time > 60) {
		m_app_config.alarm_notif_time = 60;
	}
	if ((int)m_app_config.lrw_region < 0 || (int)m_app_config.lrw_region > 2) {
		m_app_config.lrw_region = 0;
	}
	if (m_app_config.lrw_sub_band < 0) {
		m_app_config.lrw_sub_band = 0;
	}
	if (m_app_config.lrw_sub_band > 8) {
		m_app_config.lrw_sub_band = 8;
	}
	if ((int)m_app_config.lrw_network < 0 || (int)m_app_config.lrw_network > 1) {
		m_app_config.lrw_network = 0;
	}
	if ((int)m_app_config.lrw_activation < 0 || (int)m_app_config.lrw_activation > 1) {
		m_app_config.lrw_activation = 0;
	}
	if (m_app_config.lrw_link_check_interval < 0) {
		m_app_config.lrw_link_check_interval = 0;
	}
	if (m_app_config.lrw_link_check_interval > 255) {
		m_app_config.lrw_link_check_interval = 255;
	}
	if (m_app_config.lrw_link_check_fail_rejoin < 1) {
		m_app_config.lrw_link_check_fail_rejoin = 1;
	}
	if (m_app_config.lrw_link_check_fail_rejoin > 255) {
		m_app_config.lrw_link_check_fail_rejoin = 255;
	}
	if ((int)m_app_config.accel_motion_sensitivity < 0 ||
	    (int)m_app_config.accel_motion_sensitivity > 3) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF;
	}

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));
	return 0;
}

static int h_export(int (*export_func)(const char *name, const void *val, size_t val_len))
{
	/* m_app_config_settings lists config-version LAST: settings_save is
	 * per-key atomic, so writing the schema marker after every value means a
	 * brownout mid-save leaves an old version with a partial new payload rather
	 * than a new version flagging data as fully migrated. Paired with the
	 * migration restore in h_commit. */
	for (size_t i = 0; i < ARRAY_SIZE(m_app_config_settings); i++) {
		const struct app_config_setting *s = &m_app_config_settings[i];
		/* buffer = "config/" + longest key (26) + NUL */
		char name[sizeof(SETTINGS_PFX "/") + 26];

		(void)snprintf(name, sizeof(name), SETTINGS_PFX "/%s", s->key);
		(void)export_func(name, (const uint8_t *)&m_app_config + s->off, s->size);
	}

	return 0;
}

#if defined(CONFIG_SHELL)

static const char m_msg_invalid_args[] = "invalid number of arguments";
static const char m_msg_invalid_range[] = "invalid argument range";
static const char m_msg_invalid_value[] = "invalid argument value";
static const char m_msg_cmd_success[] = "command succeeded";

/* Table-driven config shell (#262 Phase 3): one generic getter (print_field) +
 * setter (cmd_field) walk a rodata descriptor per settable field, replacing the
 * per-parameter print_<name>()/cmd_<name>() pair. Validation, messages and
 * display formats are preserved 1:1. */

/* Largest shell-settable byte field is 16 B (the LoRaWAN keys); the guard keeps
 * the fixed scratch safe should a longer field ever be added. */
#define CMD_BYTES_MAX 32

enum cfg_shell_kind {
	CSK_BOOL = 0,
	CSK_INT,   /* signed, range [min, max] (0 always allowed if CSK_F_ZERO_OK) */
	CSK_UINT,  /* unsigned, range [min, max]; exactly `digits` decimals if digits > 0 */
	CSK_ENUM,  /* token <-> value via cfg_enum_tokens */
	CSK_BYTES, /* hex <-> raw; write-once if CSK_F_WRITE_ONCE */
};

#define CSK_F_READONLY   (1U << 0) /* shell read-only: any invocation just prints */
#define CSK_F_HIDDEN     (1U << 1) /* omitted from `config show` */
#define CSK_F_WRITE_ONCE (1U << 2) /* BYTES: refuse to overwrite a non-zero value */
#define CSK_F_ZERO_OK    (1U << 3) /* INT: value 0 accepted regardless of [min, max] */

struct cfg_enum_tokens {
	const char *const *tokens; /* index = enum value (contiguous from 0) */
	const char *valid;         /* comma-joined list for help / error output */
	uint8_t count;
};

struct cfg_shell_field {
	const char *key;
	uint16_t off;
	uint16_t size;
	uint8_t kind;
	uint8_t flags;
	uint8_t digits;
	int64_t min;
	int64_t max;
	const struct cfg_enum_tokens *tokens;
};

static uint32_t cfg_load32(const void *p, uint8_t size)
{
	uint32_t v = 0;

	memcpy(&v, p, size);
	return v;
}

static void print_bytes(const struct shell *shell, const char *key, const uint8_t *value,
			size_t size)
{
	char buf[2 * CMD_BYTES_MAX + 1];

	if (size > CMD_BYTES_MAX) {
		return;
	}

	int ret = bin2hex(value, size, buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " %s %s", key, buf);
}

static const char *const cfg_tokens_lrw_region[] = {
	"eu868",
	"us915",
	"au915",
};
static const struct cfg_enum_tokens cfg_enumtok_lrw_region = {
	cfg_tokens_lrw_region,
	"eu868, us915, au915",
	ARRAY_SIZE(cfg_tokens_lrw_region),
};
static const char *const cfg_tokens_lrw_network[] = {
	"public",
	"private",
};
static const struct cfg_enum_tokens cfg_enumtok_lrw_network = {
	cfg_tokens_lrw_network,
	"public, private",
	ARRAY_SIZE(cfg_tokens_lrw_network),
};
static const char *const cfg_tokens_lrw_activation[] = {
	"otaa",
	"abp",
};
static const struct cfg_enum_tokens cfg_enumtok_lrw_activation = {
	cfg_tokens_lrw_activation,
	"otaa, abp",
	ARRAY_SIZE(cfg_tokens_lrw_activation),
};
static const char *const cfg_tokens_motion_sensitivity[] = {
	"off",
	"low",
	"medium",
	"high",
};
static const struct cfg_enum_tokens cfg_enumtok_motion_sensitivity = {
	cfg_tokens_motion_sensitivity,
	"off, low, medium, high",
	ARRAY_SIZE(cfg_tokens_motion_sensitivity),
};

#define CFG_SHELL(_key, _member, _kind, _flags, _digits, _min, _max, _tok)                         \
	{(_key),                                                                                   \
	 offsetof(struct app_config, _member),                                                     \
	 sizeof(m_app_config._member),                                                             \
	 (_kind),                                                                                  \
	 (_flags),                                                                                 \
	 (_digits),                                                                                \
	 (_min),                                                                                   \
	 (_max),                                                                                   \
	 (_tok)}

static const struct cfg_shell_field m_app_config_shell[] = {
	CFG_SHELL("secret-key", secret_key, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("serial-number", serial_number, CSK_UINT, 0, 10, 0, UINT32_MAX, NULL),
	CFG_SHELL("nonce-counter", nonce_counter, CSK_UINT, 0, 0, 0, UINT32_MAX, NULL),
	CFG_SHELL("claim-token", claim_token, CSK_BYTES, CSK_F_WRITE_ONCE, 0, 0, 0, NULL),
	CFG_SHELL("calibration", calibration, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("interval-sample", interval_sample, CSK_INT, CSK_F_ZERO_OK, 0, 5, 3600, NULL),
	CFG_SHELL("interval-report", interval_report, CSK_INT, 0, 0, 60, 86400, NULL),
	CFG_SHELL("history-enable", history_enable, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("history-sensors", history_sensors, CSK_UINT, 0, 0, 0, UINT32_MAX, NULL),
	CFG_SHELL("battery-level", battery_level, CSK_INT, 0, 0, 1000, 3600, NULL),
	CFG_SHELL("alarm-limit", alarm_limit, CSK_INT, 0, 0, 0, 3600, NULL),
	CFG_SHELL("alarm-notif-time", alarm_notif_time, CSK_INT, 0, 0, 1, 60, NULL),
	CFG_SHELL("lrw-region", lrw_region, CSK_ENUM, 0, 0, 0, 0, &cfg_enumtok_lrw_region),
	CFG_SHELL("lrw-sub-band", lrw_sub_band, CSK_INT, 0, 0, 0, 8, NULL),
	CFG_SHELL("lrw-network", lrw_network, CSK_ENUM, 0, 0, 0, 0, &cfg_enumtok_lrw_network),
	CFG_SHELL("lrw-adr", lrw_adr, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-activation", lrw_activation, CSK_ENUM, 0, 0, 0, 0,
		  &cfg_enumtok_lrw_activation),
	CFG_SHELL("lrw-deveui", lrw_deveui, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-joineui", lrw_joineui, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-nwkkey", lrw_nwkkey, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-appkey", lrw_appkey, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-devaddr", lrw_devaddr, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-nwkskey", lrw_nwkskey, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-appskey", lrw_appskey, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("lrw-link-check-interval", lrw_link_check_interval, CSK_INT, 0, 0, 0, 255, NULL),
	CFG_SHELL("lrw-link-check-fail-rejoin", lrw_link_check_fail_rejoin, CSK_INT, 0, 0, 1, 255,
		  NULL),
	CFG_SHELL("cap-hall-left", cap_hall_left, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-hall-right", cap_hall_right, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-input-a", cap_input_a, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-input-b", cap_input_b, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-light-sensor", cap_light_sensor, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-barometer", cap_barometer, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-pir-detector", cap_pir_detector, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-w1-sensors", cap_w1_sensors, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("cap-accelerometer", cap_accelerometer, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("accel-motion-sensitivity", accel_motion_sensitivity, CSK_ENUM, 0, 0, 0, 0,
		  &cfg_enumtok_motion_sensitivity),
	CFG_SHELL("sensor1-rom", sensor1_rom, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("sensor2-rom", sensor2_rom, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("sensor3-rom", sensor3_rom, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("sensor4-rom", sensor4_rom, CSK_BYTES, 0, 0, 0, 0, NULL),
	CFG_SHELL("hall-left-counter", hall_left_counter, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("hall-right-counter", hall_right_counter, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("input-a-counter", input_a_counter, CSK_BOOL, 0, 0, 0, 0, NULL),
	CFG_SHELL("input-b-counter", input_b_counter, CSK_BOOL, 0, 0, 0, 0, NULL),
};

static void print_field(const struct shell *shell, const struct cfg_shell_field *f)
{
	const uint8_t *p = (const uint8_t *)&m_app_config + f->off;

	switch (f->kind) {
	case CSK_BYTES:
		print_bytes(shell, f->key, p, f->size);
		break;
	case CSK_BOOL:
		shell_print(shell, SETTINGS_PFX " %s %s", f->key,
			    *(const bool *)p ? "true" : "false");
		break;
	case CSK_ENUM: {
		uint32_t v = cfg_load32(p, f->size);
		const char *str = (v < f->tokens->count) ? f->tokens->tokens[v] : "unknown";

		shell_print(shell, SETTINGS_PFX " %s %s", f->key, str);
		break;
	}
	case CSK_INT:
		shell_print(shell, SETTINGS_PFX " %s %d", f->key, (int)cfg_load32(p, f->size));
		break;
	case CSK_UINT:
		/* `%0*u` folds "%u" (digits==0) and the zero-padded fixed-width form
		 * (e.g. serial-number's "%010u", digits==10) into one literal format. */
		shell_print(shell, SETTINGS_PFX " %s %0*u", f->key, f->digits,
			    (unsigned int)cfg_load32(p, f->size));
		break;
	}
}

static int cmd_bytes(const struct shell *shell, size_t argc, char **argv, uint8_t *value,
		     size_t size, bool write_once)
{
	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (size > CMD_BYTES_MAX || strlen(argv[1]) != 2 * size) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[CMD_BYTES_MAX];

	int ret = hex2bin(argv[1], strlen(argv[1]), tmp, size);
	if (ret != (int)size) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (write_once) {
		/* write-once (#170): refuse to overwrite a value that is already set. The
		 * all-zero state is the "unset" sentinel; once any byte is non-zero the
		 * field is locked (commission once, then immutable). */
		for (size_t i = 0; i < size; i++) {
			if (value[i] != 0) {
				shell_error(shell, "%s already set (immutable)", argv[0]);
				return -EACCES;
			}
		}
	}

	memcpy(value, tmp, size);

	return 0;
}

static int cmd_field(const struct shell *shell, size_t argc, char **argv)
{
	const struct cfg_shell_field *f = NULL;

	for (size_t i = 0; i < ARRAY_SIZE(m_app_config_shell); i++) {
		if (!strcmp(argv[0], m_app_config_shell[i].key)) {
			f = &m_app_config_shell[i];
			break;
		}
	}
	if (!f) {
		return -ENOENT; /* unreachable: the shell only dispatches known subcommands */
	}

	uint8_t *p = (uint8_t *)&m_app_config + f->off;

	/* A read-only field, or a bare `config <key>` (get): print and return. */
	if ((f->flags & CSK_F_READONLY) || argc == 1) {
		print_field(shell, f);
		return 0;
	}

	if (f->kind == CSK_BYTES) {
		return cmd_bytes(shell, argc, argv, p, f->size, (f->flags & CSK_F_WRITE_ONCE) != 0);
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	switch (f->kind) {
	case CSK_BOOL:
		if (!strcmp(argv[1], "true")) {
			*(bool *)p = true;
		} else if (!strcmp(argv[1], "false")) {
			*(bool *)p = false;
		} else {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
		shell_print(shell, "%s", m_msg_cmd_success);
		return 0;

	case CSK_INT: {
		char *endptr;
		long value = strtol(argv[1], &endptr, 10);

		if (*endptr != '\0' || endptr == argv[1]) {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
		if (!((f->flags & CSK_F_ZERO_OK) && value == 0) &&
		    (value < f->min || value > f->max)) {
			shell_error(shell, "%s", m_msg_invalid_range);
			return -EINVAL;
		}

		uint32_t v = (uint32_t)value;

		memcpy(p, &v, f->size);
		shell_print(shell, "%s", m_msg_cmd_success);
		return 0;
	}

	case CSK_UINT: {
		char *endptr;

		if (f->digits) {
			if (strlen(argv[1]) != f->digits) {
				shell_error(shell, "%s", m_msg_invalid_value);
				return -EINVAL;
			}
			for (size_t i = 0; argv[1][i] != '\0'; i++) {
				if (!isdigit((int)argv[1][i])) {
					shell_error(shell, "%s", m_msg_invalid_value);
					return -EINVAL;
				}
			}
		} else if (argv[1][0] == '-') {
			shell_error(shell, "%s", m_msg_invalid_range);
			return -EINVAL;
		}

		errno = 0;
		unsigned long long value = strtoull(argv[1], &endptr, 10);

		if (!f->digits && (*endptr != '\0' || endptr == argv[1])) {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
		/* errno==ERANGE catches strtoull saturating a giant input; the max
		 * bound then rejects values above the field width (e.g. > UINT32_MAX). */
		if (errno == ERANGE || value < (unsigned long long)f->min ||
		    value > (unsigned long long)f->max) {
			shell_error(shell, "%s",
				    f->digits ? m_msg_invalid_value : m_msg_invalid_range);
			return -EINVAL;
		}

		uint32_t v = (uint32_t)value;

		memcpy(p, &v, f->size);
		if (!f->digits) {
			shell_print(shell, "%s", m_msg_cmd_success);
		}
		return 0;
	}

	case CSK_ENUM:
		if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
			shell_print(shell, "valid values: %s", f->tokens->valid);
			return 0;
		}
		for (uint8_t i = 0; i < f->tokens->count; i++) {
			if (!strcmp(argv[1], f->tokens->tokens[i])) {
				uint32_t v = i;

				memcpy(p, &v, f->size);
				return 0;
			}
		}
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: %s", f->tokens->valid);
		return -EINVAL;
	}

	return -EINVAL;
}

static int cmd_show(const struct shell *shell, size_t argc, char **argv)
{
	for (size_t i = 0; i < ARRAY_SIZE(m_app_config_shell); i++) {
		if (!(m_app_config_shell[i].flags & CSK_F_HIDDEN)) {
			print_field(shell, &m_app_config_shell[i]);
		}
	}

	return 0;
}

static int print_help(const struct shell *shell, size_t argc, char **argv)
{
	if (argc > 1) {
		shell_error(shell, "command not found: %s", argv[1]);
		shell_help(shell);
		return -EINVAL;
	}

	shell_help(shell);

	return 0;
}

/* clang-format off */

SHELL_STATIC_SUBCMD_SET_CREATE(
	sub_config,

	SHELL_CMD_ARG(show, NULL,
	              "Show all configuration.",
	              cmd_show, 1, 0),

	SHELL_CMD_ARG(secret-key, NULL,
	              "Get/Set device secret key (32 hexadecimal digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(serial-number, NULL,
	              "Get/Set device serial number (10 decimal digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(nonce-counter, NULL,
	              "Get/Set nonce counter (unsigned integer).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(claim-token, NULL,
	              "Get/Set device claim token (32 hexadecimal digits); write-once at commissioning.",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(calibration, NULL,
	              "Get/Set calibration mode (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(interval-sample, NULL,
	              "Get/Set sample interval (range 5 to 3600 seconds; 0 = precede report).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(interval-report, NULL,
	              "Get/Set report interval (range 60 to 86400 seconds).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(history-enable, NULL,
	              "Get/Set sensor history store-and-forward (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(history-sensors, NULL,
	              "Get/Set history sensor selection bitmask (0 = all capability-available).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(battery-level, NULL,
	              "Get/Set low-battery alarm threshold in mV (default 2400; Li cells discharge non-linearly). Alarm on fPort 3 (source=battery) when supply drops below this.",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(alarm-limit, NULL,
	              "Get/Set minimum interval between alarm uplinks in seconds (0 = disabled).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(alarm-notif-time, NULL,
	              "Get/Set alarm red-LED hold time in seconds (both-mode and pulse sources).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-region, NULL,
	              "Get/Set LoRaWAN region (eu868/us915/au915).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-sub-band, NULL,
	              "Get/Set US915/AU915 sub-band (1-8, 0 = all channels). Default 2 matches TTN/Helium/ChirpStack.",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-network, NULL,
	              "Get/Set LoRaWAN network (public/private).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-adr, NULL,
	              "Get/Set LoRaWAN ADR (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-activation, NULL,
	              "Get/Set LoRaWAN activation (otaa/abp).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-deveui, NULL,
	              "Get/Set LoRaWAN DevEUI (16 hex digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-joineui, NULL,
	              "Get/Set LoRaWAN JoinEUI (16 hex digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-nwkkey, NULL,
	              "Get/Set LoRaWAN NwkKey (32 hex digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-appkey, NULL,
	              "Get/Set LoRaWAN AppKey (32 hex digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-devaddr, NULL,
	              "Get/Set LoRaWAN DevAddr (8 hex digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-nwkskey, NULL,
	              "Get/Set LoRaWAN NwkSKey (32 hexadecimal digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-appskey, NULL,
	              "Get/Set LoRaWAN AppSKey (32 hexadecimal digits).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-link-check-interval, NULL,
	              "Get/Set link-check cadence: request a LinkCheckReq every N-th uplink (0 = disabled).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(lrw-link-check-fail-rejoin, NULL,
	              "Get/Set link-check failures (while degraded) before an OTAA rejoin is attempted.",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-hall-left, NULL,
	              "Get/Set hall left capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-hall-right, NULL,
	              "Get/Set hall right capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-input-a, NULL,
	              "Get/Set input A capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-input-b, NULL,
	              "Get/Set input B capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-light-sensor, NULL,
	              "Get/Set light sensor capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-barometer, NULL,
	              "Get/Set barometer capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-pir-detector, NULL,
	              "Get/Set PIR detector capability (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-w1-sensors, NULL,
	              "Get/Set 1-Wire sensor bus capability — enables the bus + auto-detects attached sensors (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(cap-accelerometer, NULL,
	              "Get/Set accelerometer capability — orientation, motion and free-fall (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(accel-motion-sensitivity, NULL,
	              "Get/Set accelerometer motion detection sensitivity (off/low/medium/high).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(sensor1-rom, NULL,
	              "Get/Set 1-Wire slot 1 ROM (16 hex digits; all-zero = empty).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(sensor2-rom, NULL,
	              "Get/Set 1-Wire slot 2 ROM (16 hex digits; all-zero = empty).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(sensor3-rom, NULL,
	              "Get/Set 1-Wire slot 3 ROM (16 hex digits; all-zero = empty).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(sensor4-rom, NULL,
	              "Get/Set 1-Wire slot 4 ROM (16 hex digits; all-zero = empty).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(hall-left-counter, NULL,
	              "Get/Set hall left switch counter enabled (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(hall-right-counter, NULL,
	              "Get/Set hall right switch counter enabled (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(input-a-counter, NULL,
	              "Get/Set input A counter enabled (true/false).",
	              cmd_field, 1, 1),

	SHELL_CMD_ARG(input-b-counter, NULL,
	              "Get/Set input B counter enabled (true/false).",
	              cmd_field, 1, 1),

	SHELL_SUBCMD_SET_END
);

/* clang-format on */

SHELL_CMD_REGISTER(config, &sub_config, "Configuration commands.", print_help);

#endif /* defined(CONFIG_SHELL) */

struct app_config *app_config(void)
{
	return &m_app_config;
}

int app_config_factory_reset(void)
{
	int ret;

	/* Reset every parameter to its compiled-in default, but carry over the
	 * factory identity and network credentials (preserve_on_reset in the
	 * YAML) so the reset never un-provisions the device or drops it off the
	 * LoRaWAN network. A full wipe (incl. identity) stays shell-only via
	 * `settings erase`. Mirrors the migration restore in h_commit. */
	struct app_config preserved = m_app_config;

	m_app_config = m_app_config_defaults;
	memcpy(m_app_config.secret_key, preserved.secret_key, sizeof(m_app_config.secret_key));
	m_app_config.serial_number = preserved.serial_number;
	m_app_config.nonce_counter = preserved.nonce_counter;
	memcpy(m_app_config.claim_token, preserved.claim_token, sizeof(m_app_config.claim_token));
	m_app_config.lrw_region = preserved.lrw_region;
	m_app_config.lrw_sub_band = preserved.lrw_sub_band;
	m_app_config.lrw_network = preserved.lrw_network;
	m_app_config.lrw_adr = preserved.lrw_adr;
	m_app_config.lrw_activation = preserved.lrw_activation;
	memcpy(m_app_config.lrw_deveui, preserved.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	memcpy(m_app_config.lrw_joineui, preserved.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	memcpy(m_app_config.lrw_nwkkey, preserved.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	memcpy(m_app_config.lrw_appkey, preserved.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	memcpy(m_app_config.lrw_devaddr, preserved.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	memcpy(m_app_config.lrw_nwkskey, preserved.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	memcpy(m_app_config.lrw_appskey, preserved.lrw_appskey, sizeof(m_app_config.lrw_appskey));

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));

	ret = settings_save_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		return ret;
	}

	LOG_INF("Factory reset: config restored to defaults (identity + LoRaWAN kept)");
	return 0;
}

static int app_config_init(void)
{
	int ret;

	ret = settings_subsys_init();
	if (ret) {
		LOG_ERR("Call `settings_subsys_init` failed: %d", ret);
		return ret;
	}

	static struct settings_handler sh = {
		.name = SETTINGS_PFX,
		.h_set = h_set,
		.h_commit = h_commit,
		.h_export = h_export,
	};

	ret = settings_register(&sh);
	if (ret) {
		LOG_ERR("Call `settings_register` failed: %d", ret);
		return ret;
	}

	ret = settings_load_subtree(SETTINGS_PFX);
	if (ret) {
		/* H-4: do not silently swallow a load failure. SYS_INIT discards our
		 * return value, so returning here just lets the device boot on defaults
		 * (identity + provisioning gone) with no signal. Flag it instead so the
		 * app can show a distinct state; the in-RAM defaults keep the device
		 * running rather than dead. */
		LOG_ERR("Call `settings_load_subtree` failed: %d — booting on defaults", ret);
		m_app_config_load_failed = true;
	}

	if (m_app_config_migrated) {
		m_app_config_migrated = false;

		/* Persist the migrated config right away so the stored schema
		 * version is bumped and the migration does not repeat on every
		 * boot. A failure here is not fatal: the in-RAM config is valid
		 * and the migration simply runs again next boot. */
		ret = settings_save_subtree(SETTINGS_PFX);
		if (ret) {
			LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		} else {
			LOG_INF("Config migrated to version %u and persisted", APP_CONFIG_VERSION);
		}
	}

	return 0;
}

SYS_INIT(app_config_init, APPLICATION, 0);
