/* WARNING: This file is auto-generated by `west configen`. Do not modify manually. */

/*
 * Copyright (c) 2025 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "app_config.h"

/* Zephyr includes */
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/shell/shell.h>

/* Standard includes */
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config, LOG_LEVEL_DBG);

#define SETTINGS_PFX "config"

struct app_config g_app_config;

static const struct app_config m_app_config_defaults = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 0,
	.alarm_limit = 0,
	.alarm_notif_time = 10,
	.lrw_sub_band = 2,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
};

/* Set by h_commit when a schema version migration ran; init persists the
 * migrated config so the stored version is bumped exactly once. */
static bool m_app_config_migrated;

static struct app_config m_app_config = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.history_enable = false,
	.history_sensors = 0,
	.alarm_limit = 0,
	.alarm_notif_time = 10,
	.lrw_sub_band = 2,
	.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF,
};

static int h_set(const char *key, size_t len, settings_read_cb read_cb, void *cb_arg)
{
	int ret;
	const char *next;

#define SETTINGS_SET(_key, _var, _size)                                                            \
	do {                                                                                       \
		if (settings_name_steq(key, _key, &next) && !next) {                               \
			if (len != _size) {                                                        \
				return -EINVAL;                                                    \
			}                                                                          \
                                                                                                   \
			ret = read_cb(cb_arg, _var, len);                                          \
                                                                                                   \
			if (ret < 0) {                                                             \
				LOG_ERR("Call `read_cb` failed: %d", ret);                         \
				return ret;                                                        \
			}                                                                          \
                                                                                                   \
			return 0;                                                                  \
		}                                                                                  \
	} while (0)

	SETTINGS_SET("config-version", &m_app_config.config_version,
		     sizeof(m_app_config.config_version));
	SETTINGS_SET("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	SETTINGS_SET("serial-number", &m_app_config.serial_number,
		     sizeof(m_app_config.serial_number));
	SETTINGS_SET("nonce-counter", &m_app_config.nonce_counter,
		     sizeof(m_app_config.nonce_counter));
	SETTINGS_SET("calibration", &m_app_config.calibration, sizeof(m_app_config.calibration));
	SETTINGS_SET("interval-sample", &m_app_config.interval_sample,
		     sizeof(m_app_config.interval_sample));
	SETTINGS_SET("interval-report", &m_app_config.interval_report,
		     sizeof(m_app_config.interval_report));
	SETTINGS_SET("history-enable", &m_app_config.history_enable,
		     sizeof(m_app_config.history_enable));
	SETTINGS_SET("history-sensors", &m_app_config.history_sensors,
		     sizeof(m_app_config.history_sensors));
	SETTINGS_SET("alarm-limit", &m_app_config.alarm_limit, sizeof(m_app_config.alarm_limit));
	SETTINGS_SET("alarm-notif-time", &m_app_config.alarm_notif_time,
		     sizeof(m_app_config.alarm_notif_time));
	SETTINGS_SET("lrw-region", &m_app_config.lrw_region, sizeof(m_app_config.lrw_region));
	SETTINGS_SET("lrw-sub-band", &m_app_config.lrw_sub_band, sizeof(m_app_config.lrw_sub_band));
	SETTINGS_SET("lrw-network", &m_app_config.lrw_network, sizeof(m_app_config.lrw_network));
	SETTINGS_SET("lrw-adr", &m_app_config.lrw_adr, sizeof(m_app_config.lrw_adr));
	SETTINGS_SET("lrw-activation", &m_app_config.lrw_activation,
		     sizeof(m_app_config.lrw_activation));
	SETTINGS_SET("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	SETTINGS_SET("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	SETTINGS_SET("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	SETTINGS_SET("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	SETTINGS_SET("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	SETTINGS_SET("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	SETTINGS_SET("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	SETTINGS_SET("cap-hall-left", &m_app_config.cap_hall_left,
		     sizeof(m_app_config.cap_hall_left));
	SETTINGS_SET("cap-hall-right", &m_app_config.cap_hall_right,
		     sizeof(m_app_config.cap_hall_right));
	SETTINGS_SET("cap-input-a", &m_app_config.cap_input_a, sizeof(m_app_config.cap_input_a));
	SETTINGS_SET("cap-input-b", &m_app_config.cap_input_b, sizeof(m_app_config.cap_input_b));
	SETTINGS_SET("cap-light-sensor", &m_app_config.cap_light_sensor,
		     sizeof(m_app_config.cap_light_sensor));
	SETTINGS_SET("cap-barometer", &m_app_config.cap_barometer,
		     sizeof(m_app_config.cap_barometer));
	SETTINGS_SET("cap-pir-detector", &m_app_config.cap_pir_detector,
		     sizeof(m_app_config.cap_pir_detector));
	SETTINGS_SET("cap-w1-sensors", &m_app_config.cap_w1_sensors,
		     sizeof(m_app_config.cap_w1_sensors));
	SETTINGS_SET("cap-accelerometer", &m_app_config.cap_accelerometer,
		     sizeof(m_app_config.cap_accelerometer));
	SETTINGS_SET("hall-left-counter", &m_app_config.hall_left_counter,
		     sizeof(m_app_config.hall_left_counter));
	SETTINGS_SET("hall-right-counter", &m_app_config.hall_right_counter,
		     sizeof(m_app_config.hall_right_counter));
	SETTINGS_SET("input-a-counter", &m_app_config.input_a_counter,
		     sizeof(m_app_config.input_a_counter));
	SETTINGS_SET("input-b-counter", &m_app_config.input_b_counter,
		     sizeof(m_app_config.input_b_counter));
	SETTINGS_SET("temperature-corr", &m_app_config.temperature_corr,
		     sizeof(m_app_config.temperature_corr));
	SETTINGS_SET("t1-corr", &m_app_config.t1_corr, sizeof(m_app_config.t1_corr));
	SETTINGS_SET("t2-corr", &m_app_config.t2_corr, sizeof(m_app_config.t2_corr));
	SETTINGS_SET("accel-motion-sensitivity", &m_app_config.accel_motion_sensitivity,
		     sizeof(m_app_config.accel_motion_sensitivity));
	SETTINGS_SET("sensor1-rom", m_app_config.sensor1_rom, sizeof(m_app_config.sensor1_rom));
	SETTINGS_SET("sensor2-rom", m_app_config.sensor2_rom, sizeof(m_app_config.sensor2_rom));
	SETTINGS_SET("sensor3-rom", m_app_config.sensor3_rom, sizeof(m_app_config.sensor3_rom));
	SETTINGS_SET("sensor4-rom", m_app_config.sensor4_rom, sizeof(m_app_config.sensor4_rom));

#undef SETTINGS_SET

	return -ENOENT;
}

static int h_commit(void)
{
	LOG_DBG("Loaded settings in full");

	if (m_app_config.config_version != APP_CONFIG_VERSION) {
		LOG_WRN("Config version mismatch (stored=%u, expected=%u), migrating",
			m_app_config.config_version, APP_CONFIG_VERSION);

		/* Reset application parameters to defaults, but carry over factory
		 * identity and network credentials (preserve_on_migration in the
		 * YAML) so a schema bump never un-provisions a field device. */
		struct app_config stored = m_app_config;

		m_app_config = m_app_config_defaults;
		memcpy(m_app_config.secret_key, stored.secret_key, sizeof(m_app_config.secret_key));
		m_app_config.serial_number = stored.serial_number;
		m_app_config.nonce_counter = stored.nonce_counter;
		m_app_config.lrw_region = stored.lrw_region;
		m_app_config.lrw_sub_band = stored.lrw_sub_band;
		m_app_config.lrw_network = stored.lrw_network;
		m_app_config.lrw_adr = stored.lrw_adr;
		m_app_config.lrw_activation = stored.lrw_activation;
		memcpy(m_app_config.lrw_deveui, stored.lrw_deveui, sizeof(m_app_config.lrw_deveui));
		memcpy(m_app_config.lrw_joineui, stored.lrw_joineui,
		       sizeof(m_app_config.lrw_joineui));
		memcpy(m_app_config.lrw_nwkkey, stored.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
		memcpy(m_app_config.lrw_appkey, stored.lrw_appkey, sizeof(m_app_config.lrw_appkey));
		memcpy(m_app_config.lrw_devaddr, stored.lrw_devaddr,
		       sizeof(m_app_config.lrw_devaddr));
		memcpy(m_app_config.lrw_nwkskey, stored.lrw_nwkskey,
		       sizeof(m_app_config.lrw_nwkskey));
		memcpy(m_app_config.lrw_appskey, stored.lrw_appskey,
		       sizeof(m_app_config.lrw_appskey));

		m_app_config_migrated = true;
	}

	/* Clamp loaded values into their configured ranges so a corrupted or forged
	 * NVS record can't leave the device in a broken state (e.g. interval=0 ->
	 * K_SECONDS(0), or an out-of-range enum that no code path expects). */
	if (m_app_config.interval_sample < 5 && m_app_config.interval_sample != 0) {
		m_app_config.interval_sample = 5;
	}
	if (m_app_config.interval_sample > 3600) {
		m_app_config.interval_sample = 3600;
	}
	if (m_app_config.interval_report < 60) {
		m_app_config.interval_report = 60;
	}
	if (m_app_config.interval_report > 86400) {
		m_app_config.interval_report = 86400;
	}
	if (m_app_config.alarm_limit < 0) {
		m_app_config.alarm_limit = 0;
	}
	if (m_app_config.alarm_limit > 3600) {
		m_app_config.alarm_limit = 3600;
	}
	if (m_app_config.alarm_notif_time < 1) {
		m_app_config.alarm_notif_time = 1;
	}
	if (m_app_config.alarm_notif_time > 60) {
		m_app_config.alarm_notif_time = 60;
	}
	if ((int)m_app_config.lrw_region < 0 || (int)m_app_config.lrw_region > 2) {
		m_app_config.lrw_region = 0;
	}
	if (m_app_config.lrw_sub_band < 0) {
		m_app_config.lrw_sub_band = 0;
	}
	if (m_app_config.lrw_sub_band > 8) {
		m_app_config.lrw_sub_band = 8;
	}
	if ((int)m_app_config.lrw_network < 0 || (int)m_app_config.lrw_network > 1) {
		m_app_config.lrw_network = 0;
	}
	if ((int)m_app_config.lrw_activation < 0 || (int)m_app_config.lrw_activation > 1) {
		m_app_config.lrw_activation = 0;
	}
	if (m_app_config.temperature_corr < -5.0f) {
		m_app_config.temperature_corr = -5.0f;
	}
	if (m_app_config.temperature_corr > 5.0f) {
		m_app_config.temperature_corr = 5.0f;
	}
	if (m_app_config.t1_corr < -5.0f) {
		m_app_config.t1_corr = -5.0f;
	}
	if (m_app_config.t1_corr > 5.0f) {
		m_app_config.t1_corr = 5.0f;
	}
	if (m_app_config.t2_corr < -5.0f) {
		m_app_config.t2_corr = -5.0f;
	}
	if (m_app_config.t2_corr > 5.0f) {
		m_app_config.t2_corr = 5.0f;
	}
	if ((int)m_app_config.accel_motion_sensitivity < 0 ||
	    (int)m_app_config.accel_motion_sensitivity > 3) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF;
	}

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));
	return 0;
}

static int h_export(int (*export_func)(const char *name, const void *val, size_t val_len))
{
#define EXPORT_FUNC(_key, _var, _size)                                                             \
	do {                                                                                       \
		(void)export_func(SETTINGS_PFX "/" _key, _var, _size);                             \
	} while (0)

	EXPORT_FUNC("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	EXPORT_FUNC("serial-number", &m_app_config.serial_number,
		    sizeof(m_app_config.serial_number));
	EXPORT_FUNC("nonce-counter", &m_app_config.nonce_counter,
		    sizeof(m_app_config.nonce_counter));
	EXPORT_FUNC("calibration", &m_app_config.calibration, sizeof(m_app_config.calibration));
	EXPORT_FUNC("interval-sample", &m_app_config.interval_sample,
		    sizeof(m_app_config.interval_sample));
	EXPORT_FUNC("interval-report", &m_app_config.interval_report,
		    sizeof(m_app_config.interval_report));
	EXPORT_FUNC("history-enable", &m_app_config.history_enable,
		    sizeof(m_app_config.history_enable));
	EXPORT_FUNC("history-sensors", &m_app_config.history_sensors,
		    sizeof(m_app_config.history_sensors));
	EXPORT_FUNC("alarm-limit", &m_app_config.alarm_limit, sizeof(m_app_config.alarm_limit));
	EXPORT_FUNC("alarm-notif-time", &m_app_config.alarm_notif_time,
		    sizeof(m_app_config.alarm_notif_time));
	EXPORT_FUNC("lrw-region", &m_app_config.lrw_region, sizeof(m_app_config.lrw_region));
	EXPORT_FUNC("lrw-sub-band", &m_app_config.lrw_sub_band, sizeof(m_app_config.lrw_sub_band));
	EXPORT_FUNC("lrw-network", &m_app_config.lrw_network, sizeof(m_app_config.lrw_network));
	EXPORT_FUNC("lrw-adr", &m_app_config.lrw_adr, sizeof(m_app_config.lrw_adr));
	EXPORT_FUNC("lrw-activation", &m_app_config.lrw_activation,
		    sizeof(m_app_config.lrw_activation));
	EXPORT_FUNC("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	EXPORT_FUNC("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	EXPORT_FUNC("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	EXPORT_FUNC("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	EXPORT_FUNC("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	EXPORT_FUNC("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	EXPORT_FUNC("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	EXPORT_FUNC("cap-hall-left", &m_app_config.cap_hall_left,
		    sizeof(m_app_config.cap_hall_left));
	EXPORT_FUNC("cap-hall-right", &m_app_config.cap_hall_right,
		    sizeof(m_app_config.cap_hall_right));
	EXPORT_FUNC("cap-input-a", &m_app_config.cap_input_a, sizeof(m_app_config.cap_input_a));
	EXPORT_FUNC("cap-input-b", &m_app_config.cap_input_b, sizeof(m_app_config.cap_input_b));
	EXPORT_FUNC("cap-light-sensor", &m_app_config.cap_light_sensor,
		    sizeof(m_app_config.cap_light_sensor));
	EXPORT_FUNC("cap-barometer", &m_app_config.cap_barometer,
		    sizeof(m_app_config.cap_barometer));
	EXPORT_FUNC("cap-pir-detector", &m_app_config.cap_pir_detector,
		    sizeof(m_app_config.cap_pir_detector));
	EXPORT_FUNC("cap-w1-sensors", &m_app_config.cap_w1_sensors,
		    sizeof(m_app_config.cap_w1_sensors));
	EXPORT_FUNC("cap-accelerometer", &m_app_config.cap_accelerometer,
		    sizeof(m_app_config.cap_accelerometer));
	EXPORT_FUNC("hall-left-counter", &m_app_config.hall_left_counter,
		    sizeof(m_app_config.hall_left_counter));
	EXPORT_FUNC("hall-right-counter", &m_app_config.hall_right_counter,
		    sizeof(m_app_config.hall_right_counter));
	EXPORT_FUNC("input-a-counter", &m_app_config.input_a_counter,
		    sizeof(m_app_config.input_a_counter));
	EXPORT_FUNC("input-b-counter", &m_app_config.input_b_counter,
		    sizeof(m_app_config.input_b_counter));
	EXPORT_FUNC("temperature-corr", &m_app_config.temperature_corr,
		    sizeof(m_app_config.temperature_corr));
	EXPORT_FUNC("t1-corr", &m_app_config.t1_corr, sizeof(m_app_config.t1_corr));
	EXPORT_FUNC("t2-corr", &m_app_config.t2_corr, sizeof(m_app_config.t2_corr));
	EXPORT_FUNC("accel-motion-sensitivity", &m_app_config.accel_motion_sensitivity,
		    sizeof(m_app_config.accel_motion_sensitivity));
	EXPORT_FUNC("sensor1-rom", m_app_config.sensor1_rom, sizeof(m_app_config.sensor1_rom));
	EXPORT_FUNC("sensor2-rom", m_app_config.sensor2_rom, sizeof(m_app_config.sensor2_rom));
	EXPORT_FUNC("sensor3-rom", m_app_config.sensor3_rom, sizeof(m_app_config.sensor3_rom));
	EXPORT_FUNC("sensor4-rom", m_app_config.sensor4_rom, sizeof(m_app_config.sensor4_rom));
	/* Export config-version LAST: settings_save is per-key atomic, so writing
	 * the schema marker after every value means a brownout mid-save leaves an
	 * old version with a partial new payload rather than a new version flagging
	 * data as fully migrated. Paired with the migration restore in h_commit. */
	EXPORT_FUNC("config-version", &m_app_config.config_version,
		    sizeof(m_app_config.config_version));

#undef EXPORT_FUNC

	return 0;
}

#if defined(CONFIG_SHELL)

static const char m_msg_invalid_args[] = "invalid number of arguments";
static const char m_msg_invalid_range[] = "invalid argument range";
static const char m_msg_invalid_value[] = "invalid argument value";
static const char m_msg_cmd_success[] = "command succeeded";

typedef void (*print_func_t)(const struct shell *shell);

static int cmd_bool(const struct shell *shell, size_t argc, char **argv, bool *param,
		    print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "true")) {
		*param = true;
	} else if (!strcmp(argv[1], "false")) {
		*param = false;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_int(const struct shell *shell, size_t argc, char **argv, int *param, int min,
		   int max, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	long value = strtol(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < min || value > max) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	*param = (int)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_float(const struct shell *shell, size_t argc, char **argv, float *param, float min,
		     float max, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	float value = strtof(argv[1], &endptr);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < min || value > max) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	*param = value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static void print_secret_key(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.secret_key) + 1];

	int ret =
		bin2hex(m_app_config.secret_key, sizeof(m_app_config.secret_key), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " secret-key %s", buf);
}

static void print_serial_number(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " serial-number %010u", m_app_config.serial_number);
}

static void print_nonce_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " nonce-counter %u", m_app_config.nonce_counter);
}

static void print_calibration(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " calibration %s",
		    m_app_config.calibration ? "true" : "false");
}

static void print_interval_sample(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-sample %d", m_app_config.interval_sample);
}

static void print_interval_report(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-report %d", m_app_config.interval_report);
}

static void print_history_enable(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " history-enable %s",
		    m_app_config.history_enable ? "true" : "false");
}

static void print_history_sensors(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " history-sensors %u", m_app_config.history_sensors);
}

static void print_alarm_limit(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-limit %d", m_app_config.alarm_limit);
}

static void print_alarm_notif_time(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-notif-time %d", m_app_config.alarm_notif_time);
}

static void print_lrw_region(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_region) {
	case APP_CONFIG_LRW_REGION_EU868:
		str = "eu868";
		break;
	case APP_CONFIG_LRW_REGION_US915:
		str = "us915";
		break;
	case APP_CONFIG_LRW_REGION_AU915:
		str = "au915";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-region %s", str);
}

static void print_lrw_sub_band(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-sub-band %d", m_app_config.lrw_sub_band);
}

static void print_lrw_network(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_network) {
	case APP_CONFIG_LRW_NETWORK_PUBLIC:
		str = "public";
		break;
	case APP_CONFIG_LRW_NETWORK_PRIVATE:
		str = "private";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-network %s", str);
}

static void print_lrw_adr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-adr %s", m_app_config.lrw_adr ? "true" : "false");
}

static void print_lrw_activation(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_activation) {
	case APP_CONFIG_LRW_ACTIVATION_OTAA:
		str = "otaa";
		break;
	case APP_CONFIG_LRW_ACTIVATION_ABP:
		str = "abp";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-activation %s", str);
}

static void print_lrw_deveui(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_deveui) + 1];

	int ret =
		bin2hex(m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-deveui %s", buf);
}

static void print_lrw_joineui(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_joineui) + 1];

	int ret = bin2hex(m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-joineui %s", buf);
}

static void print_lrw_nwkkey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_nwkkey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-nwkkey %s", buf);
}

static void print_lrw_appkey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_appkey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-appkey %s", buf);
}

static void print_lrw_devaddr(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_devaddr) + 1];

	int ret = bin2hex(m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-devaddr %s", buf);
}

static void print_lrw_nwkskey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_nwkskey) + 1];

	int ret = bin2hex(m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-nwkskey %s", buf);
}

static void print_lrw_appskey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_appskey) + 1];

	int ret = bin2hex(m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-appskey %s", buf);
}

static void print_cap_hall_left(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-left %s",
		    m_app_config.cap_hall_left ? "true" : "false");
}

static void print_cap_hall_right(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-right %s",
		    m_app_config.cap_hall_right ? "true" : "false");
}

static void print_cap_input_a(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-a %s",
		    m_app_config.cap_input_a ? "true" : "false");
}

static void print_cap_input_b(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-b %s",
		    m_app_config.cap_input_b ? "true" : "false");
}

static void print_cap_light_sensor(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-light-sensor %s",
		    m_app_config.cap_light_sensor ? "true" : "false");
}

static void print_cap_barometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-barometer %s",
		    m_app_config.cap_barometer ? "true" : "false");
}

static void print_cap_pir_detector(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-pir-detector %s",
		    m_app_config.cap_pir_detector ? "true" : "false");
}

static void print_cap_w1_sensors(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-w1-sensors %s",
		    m_app_config.cap_w1_sensors ? "true" : "false");
}

static void print_cap_accelerometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-accelerometer %s",
		    m_app_config.cap_accelerometer ? "true" : "false");
}

static void print_hall_left_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-left-counter %s",
		    m_app_config.hall_left_counter ? "true" : "false");
}

static void print_hall_right_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-right-counter %s",
		    m_app_config.hall_right_counter ? "true" : "false");
}

static void print_input_a_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-a-counter %s",
		    m_app_config.input_a_counter ? "true" : "false");
}

static void print_input_b_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-b-counter %s",
		    m_app_config.input_b_counter ? "true" : "false");
}

static void print_temperature_corr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " temperature-corr %.2f",
		    (double)m_app_config.temperature_corr);
}

static void print_t1_corr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " t1-corr %.2f", (double)m_app_config.t1_corr);
}

static void print_t2_corr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " t2-corr %.2f", (double)m_app_config.t2_corr);
}

static void print_accel_motion_sensitivity(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.accel_motion_sensitivity) {
	case APP_CONFIG_MOTION_SENSITIVITY_OFF:
		str = "off";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_LOW:
		str = "low";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_MEDIUM:
		str = "medium";
		break;
	case APP_CONFIG_MOTION_SENSITIVITY_HIGH:
		str = "high";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " accel-motion-sensitivity %s", str);
}

static void print_sensor1_rom(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.sensor1_rom) + 1];

	int ret = bin2hex(m_app_config.sensor1_rom, sizeof(m_app_config.sensor1_rom), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " sensor1-rom %s", buf);
}

static void print_sensor2_rom(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.sensor2_rom) + 1];

	int ret = bin2hex(m_app_config.sensor2_rom, sizeof(m_app_config.sensor2_rom), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " sensor2-rom %s", buf);
}

static void print_sensor3_rom(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.sensor3_rom) + 1];

	int ret = bin2hex(m_app_config.sensor3_rom, sizeof(m_app_config.sensor3_rom), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " sensor3-rom %s", buf);
}

static void print_sensor4_rom(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.sensor4_rom) + 1];

	int ret = bin2hex(m_app_config.sensor4_rom, sizeof(m_app_config.sensor4_rom), buf,
			  sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " sensor4-rom %s", buf);
}

static int cmd_show(const struct shell *shell, size_t argc, char **argv)
{
	print_secret_key(shell);
	print_serial_number(shell);
	print_nonce_counter(shell);
	print_calibration(shell);
	print_interval_sample(shell);
	print_interval_report(shell);
	print_history_enable(shell);
	print_history_sensors(shell);
	print_alarm_limit(shell);
	print_alarm_notif_time(shell);
	print_lrw_region(shell);
	print_lrw_sub_band(shell);
	print_lrw_network(shell);
	print_lrw_adr(shell);
	print_lrw_activation(shell);
	print_lrw_deveui(shell);
	print_lrw_joineui(shell);
	print_lrw_nwkkey(shell);
	print_lrw_appkey(shell);
	print_lrw_devaddr(shell);
	print_lrw_nwkskey(shell);
	print_lrw_appskey(shell);
	print_cap_hall_left(shell);
	print_cap_hall_right(shell);
	print_cap_input_a(shell);
	print_cap_input_b(shell);
	print_cap_light_sensor(shell);
	print_cap_barometer(shell);
	print_cap_pir_detector(shell);
	print_cap_w1_sensors(shell);
	print_cap_accelerometer(shell);
	print_hall_left_counter(shell);
	print_hall_right_counter(shell);
	print_input_a_counter(shell);
	print_input_b_counter(shell);
	print_temperature_corr(shell);
	print_t1_corr(shell);
	print_t2_corr(shell);
	print_accel_motion_sensitivity(shell);
	print_sensor1_rom(shell);
	print_sensor2_rom(shell);
	print_sensor3_rom(shell);
	print_sensor4_rom(shell);

	return 0;
}

static int cmd_secret_key(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_secret_key(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.secret_key)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.secret_key)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.secret_key, tmp, sizeof(tmp));

	return 0;
}

static int cmd_serial_number(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_serial_number(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	size_t len = strlen(argv[1]);

	if (len != 10) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	for (size_t i = 0; i < len; i++) {
		if (!isdigit((int)argv[1][i])) {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
	}

	errno = 0;
	unsigned long value = strtoul(argv[1], NULL, 10);

	if (errno == ERANGE || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	m_app_config.serial_number = (uint32_t)value;

	return 0;
}

static int cmd_nonce_counter(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_nonce_counter(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (argv[1][0] == '-') {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	char *endptr;

	errno = 0;
	unsigned long value = strtoul(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* errno==ERANGE catches strtoul saturating an out-of-range input to
	 * ULONG_MAX on 32-bit (e.g. a giant nonce-counter), which would otherwise
	 * slip past the max check when max is itself UINT32_MAX. */
	if (errno == ERANGE || value < 0 || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.nonce_counter = (uint32_t)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_calibration(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.calibration, print_calibration);
}

static int cmd_interval_sample(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_interval_sample(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	int a = strtol(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (a != 0 && (a < 5 || a > 3600)) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.interval_sample = a;

	return 0;
}

static int cmd_interval_report(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.interval_report, 60, 86400,
		       print_interval_report);
}

static int cmd_history_enable(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.history_enable, print_history_enable);
}

static int cmd_history_sensors(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_history_sensors(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (argv[1][0] == '-') {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	char *endptr;

	errno = 0;
	unsigned long value = strtoul(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* errno==ERANGE catches strtoul saturating an out-of-range input to
	 * ULONG_MAX on 32-bit (e.g. a giant nonce-counter), which would otherwise
	 * slip past the max check when max is itself UINT32_MAX. */
	if (errno == ERANGE || value < 0 || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.history_sensors = (uint32_t)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_alarm_limit(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.alarm_limit, 0, 3600, print_alarm_limit);
}

static int cmd_alarm_notif_time(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.alarm_notif_time, 1, 60,
		       print_alarm_notif_time);
}

static int cmd_lrw_region(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_region(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: eu868, us915, au915");
		return 0;
	}

	if (!strcmp(argv[1], "eu868")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_EU868;
	} else if (!strcmp(argv[1], "us915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_US915;
	} else if (!strcmp(argv[1], "au915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_AU915;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: eu868, us915, au915");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_sub_band(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.lrw_sub_band, 0, 8, print_lrw_sub_band);
}

static int cmd_lrw_network(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_network(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: public, private");
		return 0;
	}

	if (!strcmp(argv[1], "public")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PUBLIC;
	} else if (!strcmp(argv[1], "private")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PRIVATE;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: public, private");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_adr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.lrw_adr, print_lrw_adr);
}

static int cmd_lrw_activation(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_activation(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: otaa, abp");
		return 0;
	}

	if (!strcmp(argv[1], "otaa")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_OTAA;
	} else if (!strcmp(argv[1], "abp")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_ABP;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: otaa, abp");
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_deveui(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_deveui(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_deveui)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_deveui)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_deveui, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_joineui(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_joineui(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_joineui)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_joineui)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_joineui, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_nwkkey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_nwkkey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_nwkkey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_nwkkey)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_nwkkey, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_appkey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_appkey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_appkey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_appkey)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_appkey, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_devaddr(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_devaddr(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_devaddr)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_devaddr)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_devaddr, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_nwkskey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_nwkskey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_nwkskey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_nwkskey)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_nwkskey, tmp, sizeof(tmp));

	return 0;
}

static int cmd_lrw_appskey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_appskey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_appskey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.lrw_appskey)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.lrw_appskey, tmp, sizeof(tmp));

	return 0;
}

static int cmd_cap_hall_left(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_left, print_cap_hall_left);
}

static int cmd_cap_hall_right(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_right, print_cap_hall_right);
}

static int cmd_cap_input_a(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_a, print_cap_input_a);
}

static int cmd_cap_input_b(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_b, print_cap_input_b);
}

static int cmd_cap_light_sensor(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_light_sensor, print_cap_light_sensor);
}

static int cmd_cap_barometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_barometer, print_cap_barometer);
}

static int cmd_cap_pir_detector(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_pir_detector, print_cap_pir_detector);
}

static int cmd_cap_w1_sensors(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_w1_sensors, print_cap_w1_sensors);
}

static int cmd_cap_accelerometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_accelerometer,
			print_cap_accelerometer);
}

static int cmd_hall_left_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_left_counter,
			print_hall_left_counter);
}

static int cmd_hall_right_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_right_counter,
			print_hall_right_counter);
}

static int cmd_input_a_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_a_counter, print_input_a_counter);
}

static int cmd_input_b_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_b_counter, print_input_b_counter);
}

static int cmd_temperature_corr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.temperature_corr, -5.0f, 5.0f,
			 print_temperature_corr);
}

static int cmd_t1_corr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.t1_corr, -5.0f, 5.0f, print_t1_corr);
}

static int cmd_t2_corr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.t2_corr, -5.0f, 5.0f, print_t2_corr);
}

static int cmd_accel_motion_sensitivity(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_accel_motion_sensitivity(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	/* `help`/`?` lists the accepted tokens. */
	if (!strcmp(argv[1], "help") || !strcmp(argv[1], "?")) {
		shell_print(shell, "valid values: off, low, medium, high");
		return 0;
	}

	if (!strcmp(argv[1], "off")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_OFF;
	} else if (!strcmp(argv[1], "low")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_LOW;
	} else if (!strcmp(argv[1], "medium")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_MEDIUM;
	} else if (!strcmp(argv[1], "high")) {
		m_app_config.accel_motion_sensitivity = APP_CONFIG_MOTION_SENSITIVITY_HIGH;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		shell_print(shell, "valid values: off, low, medium, high");
		return -EINVAL;
	}

	return 0;
}

static int cmd_sensor1_rom(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_sensor1_rom(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.sensor1_rom)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.sensor1_rom)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.sensor1_rom, tmp, sizeof(tmp));

	return 0;
}

static int cmd_sensor2_rom(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_sensor2_rom(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.sensor2_rom)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.sensor2_rom)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.sensor2_rom, tmp, sizeof(tmp));

	return 0;
}

static int cmd_sensor3_rom(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_sensor3_rom(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.sensor3_rom)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.sensor3_rom)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.sensor3_rom, tmp, sizeof(tmp));

	return 0;
}

static int cmd_sensor4_rom(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_sensor4_rom(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.sensor4_rom)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	/* Decode into a temp buffer first. hex2bin writes byte-by-byte straight
	 * into the destination and bails (returning 0) on the first invalid nibble,
	 * so decoding into the config would leave a half-overwritten key that a
	 * later `save` would persist. Commit only on a fully valid decode. */
	uint8_t tmp[sizeof(m_app_config.sensor4_rom)];

	ret = hex2bin(argv[1], strlen(argv[1]), tmp, sizeof(tmp));
	if (ret != sizeof(tmp)) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	memcpy(m_app_config.sensor4_rom, tmp, sizeof(tmp));

	return 0;
}

static int print_help(const struct shell *shell, size_t argc, char **argv)
{
	if (argc > 1) {
		shell_error(shell, "command not found: %s", argv[1]);
		shell_help(shell);
		return -EINVAL;
	}

	shell_help(shell);

	return 0;
}

/* clang-format off */

SHELL_STATIC_SUBCMD_SET_CREATE(
	sub_config,

	SHELL_CMD_ARG(show, NULL,
	              "Show all configuration.",
	              cmd_show, 1, 0),

	SHELL_CMD_ARG(secret-key, NULL,
	              "Get/Set device secret key (32 hexadecimal digits).",
	              cmd_secret_key, 1, 1),

	SHELL_CMD_ARG(serial-number, NULL,
	              "Get/Set device serial number (10 decimal digits).",
	              cmd_serial_number, 1, 1),

	SHELL_CMD_ARG(nonce-counter, NULL,
	              "Get/Set nonce counter (unsigned integer).",
	              cmd_nonce_counter, 1, 1),

	SHELL_CMD_ARG(calibration, NULL,
	              "Get/Set calibration mode (true/false).",
	              cmd_calibration, 1, 1),

	SHELL_CMD_ARG(interval-sample, NULL,
	              "Get/Set sample interval (range 5 to 3600 seconds; 0 = precede report).",
	              cmd_interval_sample, 1, 1),

	SHELL_CMD_ARG(interval-report, NULL,
	              "Get/Set report interval (range 60 to 86400 seconds).",
	              cmd_interval_report, 1, 1),

	SHELL_CMD_ARG(history-enable, NULL,
	              "Get/Set sensor history store-and-forward (true/false).",
	              cmd_history_enable, 1, 1),

	SHELL_CMD_ARG(history-sensors, NULL,
	              "Get/Set history sensor selection bitmask (0 = all capability-available).",
	              cmd_history_sensors, 1, 1),

	SHELL_CMD_ARG(alarm-limit, NULL,
	              "Get/Set minimum interval between alarm uplinks in seconds (0 = disabled).",
	              cmd_alarm_limit, 1, 1),

	SHELL_CMD_ARG(alarm-notif-time, NULL,
	              "Get/Set alarm red-LED hold time in seconds (both-mode and pulse sources).",
	              cmd_alarm_notif_time, 1, 1),

	SHELL_CMD_ARG(lrw-region, NULL,
	              "Get/Set LoRaWAN region (eu868/us915/au915).",
	              cmd_lrw_region, 1, 1),

	SHELL_CMD_ARG(lrw-sub-band, NULL,
	              "Get/Set US915/AU915 sub-band (1-8, 0 = all channels). Default 2 matches TTN/Helium/ChirpStack.",
	              cmd_lrw_sub_band, 1, 1),

	SHELL_CMD_ARG(lrw-network, NULL,
	              "Get/Set LoRaWAN network (public/private).",
	              cmd_lrw_network, 1, 1),

	SHELL_CMD_ARG(lrw-adr, NULL,
	              "Get/Set LoRaWAN ADR (true/false).",
	              cmd_lrw_adr, 1, 1),

	SHELL_CMD_ARG(lrw-activation, NULL,
	              "Get/Set LoRaWAN activation (otaa/abp).",
	              cmd_lrw_activation, 1, 1),

	SHELL_CMD_ARG(lrw-deveui, NULL,
	              "Get/Set LoRaWAN DevEUI (16 hex digits).",
	              cmd_lrw_deveui, 1, 1),

	SHELL_CMD_ARG(lrw-joineui, NULL,
	              "Get/Set LoRaWAN JoinEUI (16 hex digits).",
	              cmd_lrw_joineui, 1, 1),

	SHELL_CMD_ARG(lrw-nwkkey, NULL,
	              "Get/Set LoRaWAN NwkKey (32 hex digits).",
	              cmd_lrw_nwkkey, 1, 1),

	SHELL_CMD_ARG(lrw-appkey, NULL,
	              "Get/Set LoRaWAN AppKey (32 hex digits).",
	              cmd_lrw_appkey, 1, 1),

	SHELL_CMD_ARG(lrw-devaddr, NULL,
	              "Get/Set LoRaWAN DevAddr (8 hex digits).",
	              cmd_lrw_devaddr, 1, 1),

	SHELL_CMD_ARG(lrw-nwkskey, NULL,
	              "Get/Set LoRaWAN NwkSKey (32 hexadecimal digits).",
	              cmd_lrw_nwkskey, 1, 1),

	SHELL_CMD_ARG(lrw-appskey, NULL,
	              "Get/Set LoRaWAN AppSKey (32 hexadecimal digits).",
	              cmd_lrw_appskey, 1, 1),

	SHELL_CMD_ARG(cap-hall-left, NULL,
	              "Get/Set hall left capability (true/false).",
	              cmd_cap_hall_left, 1, 1),

	SHELL_CMD_ARG(cap-hall-right, NULL,
	              "Get/Set hall right capability (true/false).",
	              cmd_cap_hall_right, 1, 1),

	SHELL_CMD_ARG(cap-input-a, NULL,
	              "Get/Set input A capability (true/false).",
	              cmd_cap_input_a, 1, 1),

	SHELL_CMD_ARG(cap-input-b, NULL,
	              "Get/Set input B capability (true/false).",
	              cmd_cap_input_b, 1, 1),

	SHELL_CMD_ARG(cap-light-sensor, NULL,
	              "Get/Set light sensor capability (true/false).",
	              cmd_cap_light_sensor, 1, 1),

	SHELL_CMD_ARG(cap-barometer, NULL,
	              "Get/Set barometer capability (true/false).",
	              cmd_cap_barometer, 1, 1),

	SHELL_CMD_ARG(cap-pir-detector, NULL,
	              "Get/Set PIR detector capability (true/false).",
	              cmd_cap_pir_detector, 1, 1),

	SHELL_CMD_ARG(cap-w1-sensors, NULL,
	              "Get/Set 1-Wire sensor bus capability — enables the bus + auto-detects attached sensors (true/false).",
	              cmd_cap_w1_sensors, 1, 1),

	SHELL_CMD_ARG(cap-accelerometer, NULL,
	              "Get/Set accelerometer capability — orientation, motion and free-fall (true/false).",
	              cmd_cap_accelerometer, 1, 1),

	SHELL_CMD_ARG(hall-left-counter, NULL,
	              "Get/Set hall left switch counter enabled (true/false).",
	              cmd_hall_left_counter, 1, 1),

	SHELL_CMD_ARG(hall-right-counter, NULL,
	              "Get/Set hall right switch counter enabled (true/false).",
	              cmd_hall_right_counter, 1, 1),

	SHELL_CMD_ARG(input-a-counter, NULL,
	              "Get/Set input A counter enabled (true/false).",
	              cmd_input_a_counter, 1, 1),

	SHELL_CMD_ARG(input-b-counter, NULL,
	              "Get/Set input B counter enabled (true/false).",
	              cmd_input_b_counter, 1, 1),

	SHELL_CMD_ARG(temperature-corr, NULL,
	              "Get/Set temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_temperature_corr, 1, 1),

	SHELL_CMD_ARG(t1-corr, NULL,
	              "Get/Set T1 temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_t1_corr, 1, 1),

	SHELL_CMD_ARG(t2-corr, NULL,
	              "Get/Set T2 temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_t2_corr, 1, 1),

	SHELL_CMD_ARG(accel-motion-sensitivity, NULL,
	              "Get/Set accelerometer motion detection sensitivity (off/low/medium/high).",
	              cmd_accel_motion_sensitivity, 1, 1),

	SHELL_CMD_ARG(sensor1-rom, NULL,
	              "Get/Set 1-Wire slot 1 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor1_rom, 1, 1),

	SHELL_CMD_ARG(sensor2-rom, NULL,
	              "Get/Set 1-Wire slot 2 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor2_rom, 1, 1),

	SHELL_CMD_ARG(sensor3-rom, NULL,
	              "Get/Set 1-Wire slot 3 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor3_rom, 1, 1),

	SHELL_CMD_ARG(sensor4-rom, NULL,
	              "Get/Set 1-Wire slot 4 ROM (16 hex digits; all-zero = empty).",
	              cmd_sensor4_rom, 1, 1),

	SHELL_SUBCMD_SET_END
);

/* clang-format on */

SHELL_CMD_REGISTER(config, &sub_config, "Configuration commands.", print_help);

#endif /* defined(CONFIG_SHELL) */

struct app_config *app_config(void)
{
	return &m_app_config;
}

static int app_config_init(void)
{
	int ret;

	ret = settings_subsys_init();
	if (ret) {
		LOG_ERR("Call `settings_subsys_init` failed: %d", ret);
		return ret;
	}

	static struct settings_handler sh = {
		.name = SETTINGS_PFX,
		.h_set = h_set,
		.h_commit = h_commit,
		.h_export = h_export,
	};

	ret = settings_register(&sh);
	if (ret) {
		LOG_ERR("Call `settings_register` failed: %d", ret);
		return ret;
	}

	ret = settings_load_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_load_subtree` failed: %d", ret);
		return ret;
	}

	if (m_app_config_migrated) {
		m_app_config_migrated = false;

		/* Persist the migrated config right away so the stored schema
		 * version is bumped and the migration does not repeat on every
		 * boot. A failure here is not fatal: the in-RAM config is valid
		 * and the migration simply runs again next boot. */
		ret = settings_save_subtree(SETTINGS_PFX);
		if (ret) {
			LOG_ERR("Call `settings_save_subtree` failed: %d", ret);
		} else {
			LOG_INF("Config migrated to version %u and persisted", APP_CONFIG_VERSION);
		}
	}

	return 0;
}

SYS_INIT(app_config_init, APPLICATION, 0);
